### ISSUE TITLE
界面截图

### ISSUE THREAD

**Issue by 88250** [b3log/solo#11987]
* **Index - Skin (ease)**
![skin-ease](https://cloud.githubusercontent.com/assets/873584/5584735/e1634c80-90d1-11e4-80a9-bae4ca8eb37d.png)
* **Admin - Index**
![admin-index](https://cloud.githubusercontent.com/assets/873584/5584727/855ab0ea-90d1-11e4-8504-c485a8f791df.png)
* **Admin - Post (TinyMCE)**
![post_tinymce](https://cloud.githubusercontent.com/assets/873584/5584725/848cdf58-90d1-11e4-8d8a-f186e05db2cd.png)
* **Admin - Post (Markdown)**
![post_markdown](https://cloud.githubusercontent.com/assets/873584/5585055/6bf35892-90da-11e4-986c-c80e4df5dde1.png)
* **Admin - Preference**
![pref](https://cloud.githubusercontent.com/assets/873584/5584724/8484c8c2-90d1-11e4-9e28-71c30dc8bfda.png)
* **Admin - Skins**
![admin-skins](https://cloud.githubusercontent.com/assets/873584/9975917/994d9e02-5f00-11e5-8a6d-fe652ac3e75e.png)

**Comment by 88250** [comment]
![guitar_solo](https://cloud.githubusercontent.com/assets/873584/6803932/cbe02f64-d275-11e4-9192-b6a4b8ba837f.jpg)

**Comment by 88250** [comment]
![qq 20150927152244](https://cloud.githubusercontent.com/assets/873584/10121705/d04d34b8-652b-11e5-8ee7-91b0ee0c4500.jpg)

**Comment by garyrothchild** [comment]
是不是文章插入图片功能用不了？

**Comment by 88250** [comment]
@garyrothchild 可以用的，目前仅支持使用七牛云存储。

**Comment by garyrothchild** [comment]
Not allowed to load local resource: file:///C:/Users/wacai/Desktop/QQ%E5%9B%BE%E7%89%8720160311130508.png

**Comment by 88250** [comment]
@garyrothchild 需要先配置一下七牛：https://hacpai.com/article/1442418791213

**Comment by garyrothchild** [comment]
已经配置好了，但是还是之前的错误。

**Comment by garyrothchild** [comment]
但是附件可以用了

**Comment by 88250** [comment]
@garyrothchild 你换个其他目录的图片试试，理论上应该都可以才对

**Comment by garyrothchild** [comment]
@88250 ，换个图片也不行，是不是需要重启一下服务?

**Comment by 88250** [comment]
@garyrothchild 重启一下试试，对了，还有强制刷新一下管理后台页面

**Comment by garyrothchild** [comment]
@88250 还是报错

image.htm:1 Not allowed to load local resource: file:///C:/Users/Public/Pictures/Sample%20Pictures/%E4%BC%81%E9%B9%85.jpg
admin-index.do:1 Not allowed to load local resource: file:///C:/Users/Public/Pictures/Sample%20Pictures/%E4%BC%81%E9%B9%85.jpg

**Comment by 88250** [comment]
你用的浏览器是？换个浏览器试试看？

**Comment by 88250** [comment]
@garyrothchild 你用的浏览器是？换个浏览器试试看？

**Comment by garyrothchild** [comment]
@88250 用的chrome

**Comment by garyrothchild** [comment]
@88250 换了其他浏览器也是不行

**Comment by garyrothchild** [comment]
Not allowed to load local resource: file:///C:/Users/wacai/Desktop/QQ%E5%9B%BE%E7%89%8720160311130508.png tiny_mce.js:1(anonymous function) tiny_mce.js:1e.create.run tiny_mce.js:1e.create.setHTML tiny_mce.js:1ImageDialog.showPreviewImage image.js:489onchange

**Comment by 88250** [comment]
@garyrothchild 你用的是 Solo 哪个版本？

**Comment by garyrothchild** [comment]
拉的master分支

**Comment by 88250** [comment]
@garyrothchild 那应该是最新的代码了，好奇怪..

**Comment by garyrothchild** [comment]
我感觉是代码中不支持本地图片上传

**Comment by 88250** [comment]
@garyrothchild 支持的，其他用户都没有反馈过有问题..

**Comment by csq39** [comment]
是不是和中文路径有关，推测～



发自 网易邮箱大师
在2016年03月14日 18:58，Liang Ding 写道:

@garyrothchild 支持的，其他用户都没有反馈过有问题..

**Comment by zh-h** [comment]
我想换个编辑器，需要改数据库字段吗？

**Comment by 88250** [comment]
@zh-h 什么意思？

**Comment by zh-h** [comment]
@88250 内置的那个markdown编辑器实在不好用

**Comment by 88250** [comment]
@zh-h 理论上可以换的，不用改数据库结构，研究一下代码吧。

**Comment by zh-h** [comment]
@88250 里面存了原始文本和渲染后的HTML

**Comment by 88250** [comment]
@zh-h 没有，目前只会保存原始文本（用 MD 编辑器就是 MD，用 HTML 编辑器就是 HTML），最终渲染的时候是根据一个字段判断是否使用 MD 渲染。
