### ISSUE TITLE
加入开发者、贡献者名单

### ISSUE THREAD

**Issue by 88250** [b3log/solo#12020]
放在后台“关于”页里。

#### 开发者

* [D](http://88250.b3log.org)
* [V](http://vanessa.b3log.org)
* [mainlove](mailto:wmainlove@gmail.com)
* [DX](http://people.apache.org/~dongxu)
* [大叔](http://mizhichashao.com)
* [javen.jiang](http://www.jiangzezhou.com)

#### 贡献者

* [An Shen](http://www.ansen.org)
* [Chevo](http://www.bestck.net)
* [破生](https://github.com/paul-luo)
* [宋诗献](http://xxk.b3log.org)
* [Lamb](http://www.mynah.org)

**Comment by xiaomogui** [comment]
开发者列表放到资源文件里，项目启动的时候读取到内存好不好

**Comment by 88250** [comment]
不加配置文件了，别人升级麻烦。

**Comment by xiaomogui** [comment]
静态页嘛？

**Comment by 88250** [comment]
页面已经有了：admin-about.ftl
