### ISSUE TITLE
独立模式

### ISSUE THREAD

**Issue by 88250** [b3log/solo#12037]
### 独立模式

从 Solo 1.2.0 版本开始，加入独立（standalone）模式，只要已经安装好了 Java 环境，一个命令就能启动！

1. 不依赖 MySQL 数据库，而是使用内嵌的 H2 数据库，数据文件默认保存在 ${user.home}/b3log_solo_h2 目录下
2. 不依赖外置 Servlet 容器，而是使用内嵌 Jetty 进行启动

### 配置

1. `latke.props` 按需修改，比如修改域名、端口等
2. `local.props` 将 `#### MySQL runtime ####` 段落注释掉，打开 `#### H2 runtime ####` 段落

### 运行

在 Solo 解压目录下执行：

* Windows: `java -cp WEB-INF/lib/*;WEB-INF/classes org.b3log.solo.Starter`
* Unix-like: `java -cp WEB-INF/lib/*:WEB-INF/classes org.b3log.solo.Starter`

**Comment by wzh154710510** [comment]
[ERROR]-[2018-06-28 10:50:05]-[org.b3log.solo.service.UpgradeService:151]: Attempt to skip more than one version to upgrade. Expected: 2.9.0, Actually: 2.4.0
请问这个是什么错？
