### ISSUE TITLE
Docker 方式启动

### ISSUE THREAD

**Issue by 88250** [b3log/solo#12048]
加入 Dockerfile，通过 Docker Hub 和 GitHub 的连接，自动构建镜像。

**Comment by 88250** [comment]
https://github.com/b3log/solo/wiki/docker

**Comment by TianxinWeng** [comment]
我从本地中 pull 下您的源码，并构建docker镜像， docker build . 时，并未是想象般那样成功， 是maven install 过程中 ，有很多依赖是无法解析的，不知道为何会出现这样的情况 The following artifacts could not be resolved: ...

**Comment by 88250** [comment]
@TianxinWeng 麻烦把构建输出贴一下

**Comment by TianxinWeng** [comment]
@88250  

嗯呢。十分感谢您能回复我。

不知道为什么， 有时不论是在dockerfile中 `RUN mvn (clean or package or install) `还是 在bash命令行中`docker run maven mvn clean(package)` 时，总是停留在 downloading 后报出下面的错误，但有时候却能正常执行。 

`![image](https://cloud.githubusercontent.com/assets/15177852/14409319/544cca1c-ff41-11e5-9e84-93adb5df1007.png)`

**Comment by 88250** [comment]
@TianxinWeng 解析依赖不行的时候停止了重新 build 吧，我国的网络情况你是知道的..

**Comment by TianxinWeng** [comment]
@88250  嗯嗯~ 很感谢您的解答， 最后发现确实是网络的原因。
