### ISSUE TITLE
MySQL数据库表

### ISSUE THREAD

**Issue by lucifercd** [b3log/solo#12049]
我想看MySQL数据表是怎么设计的，在哪里能看到数据表结构？

**Comment by 88250** [comment]
初始化以后就可以看了，如果用的是独立模式，那需要用 H2 的客户端看。

**Comment by lucifercd** [comment]
我没有办法初始化，不知道wiki文档和git clone的文件不一样。怎么解决

![qq20151203-0](https://cloud.githubusercontent.com/assets/13402671/11551603/c3dffa58-99b5-11e5-918e-ded62ae105c9.png)

**Comment by 88250** [comment]
`git clone` 下来的是源代码，需要自己编译打包才能生成 solo.war 文件的。

你可以直接下载我们做的安装包：http://pan.baidu.com/share/link?shareid=541735&uk=3255126224
