### ISSUE TITLE
简化配置

### ISSUE THREAD

**Issue by 88250** [b3log/solo#12058]
简化配置文件 latke.props。

`scanPath` 应该是固化在 Solo 代码里的，不应该留给用户作为配置，故去除。

最终只包含如下 4 个配置项：

* `serverScheme`
* `serverHost`
* `serverPort`
* `runtimeMode`

其余的配置项为可选项，如果存在则使用。

**Comment by leogong** [comment]
staticPath 如果有用CDN，静态资源是可以指定其它domain的吧？这个还是需要的

**Comment by 88250** [comment]
@leogong 可以配置的，如果显示配置了，就用配置的，没有配置的情况下才会自动获取。
