### ISSUE TITLE
yilia皮肤

### ISSUE THREAD

**Issue by zhaorenjie110** [b3log/solo#12078]
这个皮肤在IE下兼容性很差，在chrome和firefox下是正确的。
![image](https://cloud.githubusercontent.com/assets/9960574/12575288/530aad08-c446-11e5-892a-43f8d8c83659.png)
我的是IE11浏览器。
我的博客是http://zhaorenjie.xyz

**Comment by 88250** [comment]
多谢反馈！

@Vanessa219

**Comment by Vanessa219** [comment]
@zhaorenjie110 你是不是启用了兼容模式
![image](https://cloud.githubusercontent.com/assets/970828/12606316/655da778-c507-11e5-8770-6b1ac959d853.png)

**Comment by 88250** [comment]
我这里也重现不了，我先关闭这个问题了哦，还需要支持的话就重开~
