### ISSUE TITLE
文章日期修改后，归档时间没有变

### ISSUE THREAD

**Issue by zhaodedong** [b3log/solo#12080]
我最近准备使用咱们的solo博客，但是在本地测试的时候发现一个地方和我理解的不太一样：
我有很多博客是在之前就写过的，因此在迁过来之后，我会考虑修改每篇博客的日期，但是发现咱们没这个修改的功能，因此我就去了数据库修改，但是把createTime修改完之后，它的归档日期没有变，这个有没有方式变通一下，我修改完博客的日期之后，相应的归档日期也改变一下？？？？
我相信这种应用场景应该不在少数吧？还是我没有发现它的正确使用方式？望告知~~~~

**Comment by 88250** [comment]
你是手动导入以前的文章么？

建议通过 MetaWeblog API 方式进行导入，这样就可以选择发布日期啦~

**Comment by zhaodedong** [comment]
MetaWeblog API 是通过自己敲代码调用吗？还是在网页里面能找到相应的接口？我在yilia中没有找到相关的操作，另外Markdown编辑器也没有找到，请指教~



zhaodedong91@gmail.com
 
发件人： Liang Ding
发送时间： 2016-01-27 11:43
收件人： b3log/solo
抄送： zhaodedong
主题： Re: [solo] 文章日期修改后，归档时间没有变 (#12080)
你是手动导入以前的文章么？
建议通过 MetaWeblog API 方式进行导入，这样就可以选择发布日期啦~

**Comment by 88250** [comment]
1. MetaWeblog 可以使用很多客户端软件，比如 [WLW](https://www.microsoft.com/en-us/download/details.aspx?id=8621)，顺便帮忙测试一下 Solo~
2. 要使用 MD 编辑器的话可以在偏好设定里面设置
