### ISSUE TITLE
Can't not init default skin, please init Solo first

### ISSUE THREAD

**Issue by chenzhikaida** [b3log/solo#12085]
用maven install构建后 启动start.class 总是提示Can't not init default skin, please init Solo first 是什么意思呀

**Comment by chenzhikaida** [comment]
文档上说访问http://${server}:${port}/${contextPath} 进行初始化 但是我进入这个url是空白的

**Comment by 88250** [comment]
你好，如果你是这样启动的：

* 使用独立模式
* 没有加任何参数

那么直接访问 http://localhost:8080 就可以看到初始化向导页面了。

**Comment by chenzhikaida** [comment]
大哥我万分崇拜您 能不能加个微信 qq什么的

**Comment by 88250** [comment]
加 Q 群：13139268 :smirk:
