### ISSUE TITLE
如何上传文件到自己的服务器，而不是七牛

### ISSUE THREAD

**Issue by dengjunwen** [b3log/solo#12083]
你好：
         我是下载war包，部署到自己的vps上，如何上传文件到本地的vps上呢？如我blog中需要添加一张图片，我选择上传文件，提示上传失败。

**Comment by 88250** [comment]
Solo 目前只能上传到七牛。

这一点主要是为了以后迁移博客的时候方便，二进制文件不用动，请理解啦！

**Comment by dengjunwen** [comment]
谢谢！那只有去七牛注册号了
> 在 2016年1月27日，下午10:20，Liang Ding <notifications@github.com> 写道：
> 
> 目前只能上传到七牛。
> 
> 这一点主要是为了以后迁移博客的时候方便，二进制文件不用动，请理解啦！
>
