### ISSUE TITLE
文章内容一开始如果是标题级，显示会有问题

### ISSUE THREAD

**Issue by nivalsoul** [b3log/solo#12095]
文章内容一开始如果就是h1或者h2等内容格式，发表后显示正文会自动多出一些h1或者h2部分的内容。见：http://demo.b3log.org/articles/2016/04/28/1461833401379.html和http://demo.b3log.org/articles/2016/04/28/1461833281776.html

**Comment by 88250** [comment]
你好~

这个不是 bug，是个特性：#11976

**Comment by nivalsoul** [comment]
@88250 原来如此
