### ISSUE TITLE
评论 XSS 漏洞 

### ISSUE THREAD

**Issue by zjhch123** [b3log/solo#12091]
就是说在评论的时候URL没有过滤…
在评论的URL里像这样输入
`"><script>alert(/xss/)</script><a`

后台代码我没有看过，我做了简单的防范，给b3_solo_comment这张表加了一个trigger
```
DELIMITER $
create trigger antiXSS
before insert on b3_solo_comment
for each row
begin
if locate("<",new.commentURL)>0 then
       set new.commentURL = 'https://www.baidu.com';
end if;
end$
DELIMITER ;
```
反正一个URL里是肯定不会带<的…如果有<说明肯定是有人想干坏事了，所以我就直接把他替换成百度了……
我好惶恐

**Comment by Vanessa219** [comment]
谢谢提醒。

@88250 出来补洞了，bug 小王子。
