### ISSUE TITLE
关于因内存分配失败而导致jdbc未注销问题

### ISSUE THREAD

**Issue by TiSongWen** [b3log/solo#12126]
### 运行环境：
因为是部署在阿里云的学生机，所有总共是有1G的内存。我是将solo.war放到tomcat的docker容器中，并链接另一个mysql的docker容器。

### 程序出现问题原因：
> Native memory allocation (malloc) failed to allocate 5246976 bytes for committing reserved memory. （我想这个问题应该是和我内存问题过小有关，因为我本地机器运行一直是没有问题的）

### 重启tomcat后
> 日志中出现了 WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.的情况

### 个人猜测
我想会不会是 因为之前内存问题导致程序意外结束时，jdbc并没有 registered 的问题。
 
（也有可能是其他原因，^ ^。谢谢大家的解答）

**Comment by 88250** [comment]
看上去是因为 MySQL 驱动因为内存不足导致的，后面 Tomcat 日志中报错我猜想也是和这个有关，我的想法和你最后提到的是一样的。

加点内存吧，Java 挺吃内存的，虽然 Solo 的框架已经足够小了....

**Comment by 88250** [comment]
这个 issue 我先关闭了，如果还发现有问题你再 reopen。
