### ISSUE TITLE
markdown 增强

### ISSUE THREAD

**Issue by leogong** [b3log/solo#12123]
现在的markdown功能性不是很强（前端JS和后端JAVA），不少语法不支持如果~~~ ``` ，并且使用markdown现在代码还不能高亮；
建议JAVA端换成pegdown，前端JS也可以换一个对应功能强一些的
现在大家写文章严重依赖markdown特性，建议把markdown的功能完善一些，多谢了

**Comment by 88250** [comment]
已经调整了，请参考 #12107 。
