### ISSUE TITLE
调整文章目录

### ISSUE THREAD

**Issue by leogong** [b3log/solo#12122]
现在文章的目录太丑了，能换成toc或者bootstrap的吗？

**Comment by leogong** [comment]
最好目录可以在左右两边，并且可以跟随滚动

**Comment by 88250** [comment]
谢谢反馈，我们会考虑的，如果改动简单下个版本就加上，如果复杂就延迟到以后版本实现。

@Vanessa219

**Comment by 88250** [comment]
后续版本实现吧，赶不及在 1.4.0 里面实现了。

@Vanessa219

**Comment by leogong** [comment]
这个准备在哪个版本上面添加呢？

**Comment by 88250** [comment]
所有皮肤都调整的话工作量太大，你需求的是哪一款皮肤做这个调整呢？

**Comment by leogong** [comment]
finding & yilia are my favourite. 多谢了 @88250

**Comment by leogong** [comment]
这个什么时候加呀？

**Comment by 88250** [comment]
@leogong 这两个皮肤已经调整好了，可以先到 https://github.com/b3log/solo-skins 下载体验。

**Comment by leogong** [comment]
好多，thx
