### ISSUE TITLE
yilia皮肤左侧side的footer样式问题

### ISSUE THREAD

**Issue by 1102568869** [b3log/solo#12121]
footer里面的元素在title所在div没有到达228px宽度之前,整体内容不会居中显示
目前在footer元素上加了行内样式margin-left:36px;width:228px;text-align:center;零时性解决!

**Comment by 88250** [comment]
收到，下个版本解决，多谢啦！

**Comment by Vanessa219** [comment]
@1102568869 没太看懂说的是什么，可以截个图给我看看么？

**Comment by 88250** [comment]
问题描述不明确，推迟到 1.4.0 以后解决。

@Vanessa219

**Comment by 1102568869** [comment]
囧  更新到1.4.0之后 发现这个问题已经被解决了啊,我看到css文件有对应的变动

**Comment by 88250** [comment]
好的，那我关闭这个 issue 了，多谢反馈。
