### ISSUE TITLE
是否可以直接用war包运行？

### ISSUE THREAD

**Issue by kran** [b3log/solo#12138]
希望可以通过一个war包+一个配置文件+数据库文件，这样的方式走起来。
当然这个不是很重要，算是强迫症。：）

**Comment by 88250** [comment]
[独立模式](https://github.com/b3log/solo/wiki/standalone_mode) 是这个节奏，试试看？

**Comment by kran** [comment]
@88250 可以不解压吗?

**Comment by 88250** [comment]
不解压应该不行哦

**Comment by kran** [comment]
没怎么用过java, 我记得它是可以直接运行jar包的, 有什么办法吗?

**Comment by 88250** [comment]
我不大理解为什么你要不解压就运行哦

**Comment by kran** [comment]
没什么啦, 开头也说了, 这个不重要.
算啦, 我就不添乱了, 谢谢
