### ISSUE TITLE
b3log跑起来隔一段时间之后   nginx就开始拒绝访问了  说socket连接达到上限!把b3log停掉后,恢复正常(可长期持续正常访问)

### ISSUE THREAD

**Issue by 1102568869** [b3log/solo#12133]
`2016/07/17 06:37:55 [crit] 1608#1620: *5173 connect() to 127.0.0.1:8090 failed (10055: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full) while connecting to upstream, client: ****, server:****, request: "GET /index.html HTTP/1.1", upstream: "http://127.0.0.1:8090/blog/index.html", host: "blog.washmore.tech"
`

**Comment by 1102568869** [comment]
nginx相关配置
`	server {
        listen       80;
        server_name  ****;

        error_page  404              /404.html;
		
		
        error_page   500 502 503 504  /50x.html;
      
        location = /50x.html {
            root   html;
        }

		
		location / {  
			proxy_pass http://127.0.0.1:8090/;  
			proxy_set_header   Host    $host;  
			proxy_set_header   X-Real-IP   $remote_addr;  
			proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;  
			limit_conn  beat_fast 8; 
		}  
	}`

**Comment by 88250** [comment]
你用的 Solo 是最新版吗？

**Comment by 88250** [comment]
Solo 用的是什么容器启动的？

PS：是 Solo，不是 B3log，B3log 是开源组织的名字。

**Comment by 1102568869** [comment]
tomcat 默认配置 未作任何修改

**Comment by 88250** [comment]
不应该啊，是不是 Tomcat 还跑了其他应用影响的？

**Comment by 1102568869** [comment]
目前来看 是新加入solo之后出现这个问题的,等我再观察一段时间,排查一下日志  再来确认吧,最近木有太多业余时间```

**Comment by 88250** [comment]
好的，谢谢反馈，有空时请帮忙跟进确认。我这边长期运行下来目前没有发现资源泄露的问题。

**Comment by 88250** [comment]
你好，还有在跟进这个问题么？

**Comment by 88250** [comment]
先关闭了，如果以后发现再看吧 :)
