### ISSUE TITLE
是否可以增加一个Markdown文章的目录悬浮视图

### ISSUE THREAD

**Issue by eurry** [b3log/solo#12131]
类似于黑客派社区的那种效果，
例如 [文章示例](https://hacpai.com/article/1464144427761) 中，右侧的目录悬浮视图

**Comment by 88250** [comment]
目前不是悬浮的，是直接拼接在文章开头部分。这个要改好多皮肤，我怕 @Vanessa219 改不动....

**Comment by leogong** [comment]
慢慢改吧，可以先把比较热门的主题改了，其它的后面有时间再改

**Comment by leogong** [comment]
类似这样的文章目录更好看，bootstrap的也可以
https://segmentfault.com/a/1190000006011003

**Comment by Vanessa219** [comment]
#12122
