### ISSUE TITLE
新版 Markdown 编辑器

### ISSUE THREAD

**Issue by 88250** [b3log/solo#12159]
* 支持全屏模式
* 支持 Emoji 自动完成（快捷键 `Ctrl-/`）
* 支持复制粘贴时自动将 HTML 转换为 Markdown

![qq 20161109000909](https://cloud.githubusercontent.com/assets/873584/20106661/e4b04b76-a610-11e6-9a62-831da8af090d.png)

**Comment by Vanessa219** [comment]
支持全屏模式 & emoji
![image](https://cloud.githubusercontent.com/assets/970828/20104068/7e57376c-a607-11e6-8333-f3014d9b5fe2.png)
