### ISSUE TITLE
staticServePath 配置错误

### ISSUE THREAD

**Issue by mamacmm** [b3log/solo#12168]
刚刚下载的源码，部署到tomcat7下面，启动后，直接访问，报错：

staticServePath 配置错误

**Comment by 88250** [comment]
latke.props 里 host 和 port 的配置需要和浏览器访问时候配置成一样。

**Comment by mamacmm** [comment]
那个已经按文档配置好了

比如我现在访问：http://localhost:9085/solo

latke.props 的配置如下：

serverScheme=http
serverHost=localhost
serverPort=9085

**Comment by 88250** [comment]
麻烦浏览器 F12 看下网络里面的请求

**Comment by mamacmm** [comment]
好像端口 还是  8080




2016-09-10 

mamacmm 



发件人：D <notifications@github.com>
发送时间：2016-09-10 12:08
主题：Re: [b3log/solo] staticServePath 配置错误 (#12168)
收件人："b3log/solo"<solo@noreply.github.com>
抄送："mamacmm"<mamacmm@126.com>,"Author"<author@noreply.github.com>

麻烦浏览器 F12 看下网络里面的请求

**Comment by 88250** [comment]
部署目录 webapps/solo 下面改吧，原来的 war 包先删了，改完记得重启。
