### ISSUE TITLE
关于自动升级与css引用的小问题

### ISSUE THREAD

**Issue by TiSongWen** [b3log/solo#12165]
您好哦～

1. solo 版本的升级是需要自己重新将最新版本的 项目打包然后部署吗？ 还是有自动升级的功能？

2. 关于 css 样式表引用时返回 HTTP状态码 502的问题。
是Next皮肤或者 Finding 皮肤中， 在首页中以及文章中都会引用到该 外部 css样式，http://fonts.useso.com/css?family=Merriweather:300,700,700itali
但不幸的是 结果返回502，所以影响了服务器的响应时间。（大约10s的时间才能加载页面，基本上都是在等待该css样式的响应）

**Comment by 88250** [comment]
1. 需要下载最新版然后修改配置文件部署，现在暂时没有自动升级功能，抱歉啦
2. 这个是因为以前引用了 360 的字体库 CDN，可能这个 CDN 现在没人维护了，所以不可用，最新版 1.6.0 里面已经修复这个问题了，你可以下载最新版使用

多谢反馈 :-p

**Comment by TiSongWen** [comment]
恩恩。感谢您的解答哦～

**Comment by 88250** [comment]
客气啦，我关闭这个 issue 了 :-p

PS 欢迎加入社区 https://hacpai.com
