### ISSUE TITLE
关于如何博客更换头像的问题

### ISSUE THREAD

**Issue by TiSongWen** [b3log/solo#12176]
在后台界面中没有找到更换头像的功能。然后去找文件夹下的图片，似乎也没有找到对应的图片文件。所以博客的头像是如何生成的呢？

**Comment by ZephyrJung** [comment]
我记得好像是上传到七牛云的
可以换头像的吧？

**Comment by 88250** [comment]
默认是使用 Gavatar，可以在【用户管理】里面更新，通过外链方式 :-p
