### ISSUE TITLE
新皮肤 9IPHP

### ISSUE THREAD

**Issue by zxhprogram** [b3log/solo#12180]
参考http://9iphp.com/  
和http://www.zifangsky.cn

**Comment by 88250** [comment]
@Vanessa219 http://www.zifangsky.cn/ 这个看上去挺清爽的，有空就来一发吧~

**Comment by Vanessa219** [comment]
@zxhprogram http://www.zifangsky.cn 这个做皮肤好像更好一点，你倾向那一个呢？

**Comment by 88250** [comment]
![9iphp](https://cloud.githubusercontent.com/assets/873584/23152149/ec70a898-f83a-11e6-8fc7-66bcf5a9b149.jpg)
