### ISSUE TITLE
同步到 Symphony 测试记录

### ISSUE THREAD

**Issue by Vanessa219** [b3log/solo#12207]
同步文章：Solo & Symphony 同步测试 【微信小程序是在歧视 Android 用户么？】

solo 文章地址：http://vanessa.b3log.org/articles/2016/11/10/1478758307077.html
sym 文章地址：https://hacpai.com/article/1478758987965

1. solo -> sym 标签同步错误
solo 标签：同步,Test,微信小程序
symphony 标签：B3log， 同步， Test， 微信

2.  sym -> solo 摘要同步错误
solo 摘要中，标题没有截断。所有摘要都为标题的样式了。

3. sym -> solo 标签同步错误
solo 原有标签：同步,Test,微信小程序
solo 同步后标签：B3log, 同步, 微信, Test

**Comment by 88250** [comment]
1. Sym 做了标签规范化处理，所以`微信小程序` -> `微信`这个是对的
2. 留观
3. 同一
