### ISSUE TITLE
启动端口不正确

### ISSUE THREAD

**Issue by mamacmm** [b3log/solo#12209]
我右键 Starter 运行后，提示：

`[INFO ]-[2016-11-12 17:18:13]-[org.b3log.solo.SoloServletListener:149]: Solo is running [http://localhost:9085]`

但是这个地址打不开程序，试了试 http://localhost:8080  能打开

这提示的端口不正确啊

**Comment by 88250** [comment]
请看一下这里 https://hacpai.com/article/1474087427032
