### ISSUE TITLE
评论编辑器改进

### ISSUE THREAD

**Issue by Vanessa219** [b3log/solo#12204]
- 评论编辑器换为 markdown

**Comment by 88250** [comment]
后台已经处理过 markdown 和 emoji 了，前端我觉得这个需求不大..没必要引入一个完整的编辑器。

**Comment by Vanessa219** [comment]
要换也是找几个皮肤来换。不会全部一起换。。。。

**Comment by 88250** [comment]
从 1.8 里面取消了，以后再看吧。

**Comment by Vanessa219** [comment]
先这样吧。移动端的 codemirror 支持不太好
