### ISSUE TITLE
请问，重新部署solo.war的时候会重新初始化是么？

### ISSUE THREAD

**Issue by smuyyh** [b3log/solo#12208]
我是删掉原来解压的solo文件夹，替换solo.war，重启tomcat，第一次试的时候又要求要初始化，第二次同样操作，不需要初始化。是为什么呢？

**Comment by 88250** [comment]
判断初始化是看是否有数据，现在已经解决了吧？

**Comment by smuyyh** [comment]
是看数据库的数据吧。我忘了我切换了数据库，谢谢你。

**Comment by 88250** [comment]
嗯，看数据库数据。没有问题就好 :)
