### ISSUE TITLE
提几个需求

### ISSUE THREAD

**Issue by royburns** [b3log/solo#12214]
1. 支持第三方登录
2. 加入支付模块
3. 支持文章导入
4. 表情更新一下？
5. 后台增加统计：文章、评论、访客、在线用户等
6. 编辑模式下支持粘贴图片

**Comment by royburns** [comment]
第二条忽略吧

**Comment by 88250** [comment]
1. 暂时不考虑了，个人博客这个需求没必要嘛
2. 忽略了
3. 可以通过 MetaWeblog API 导入
4. @Vanessa219 
5. 这个数据前台页面也有的，感觉后台没必要再重复了
6. @Vanessa219 

多谢反馈。

**Comment by 88250** [comment]
1.7.0 里面已经完成了， Emoji 可以使用字符，发布后会自动转为图片的。
