### ISSUE TITLE
MarkDown编译器bug

### ISSUE THREAD

**Issue by undersky** [b3log/solo#12212]
solo版本1.7
使用上传文件上次图片成功后，会返回Markdown图片格式: `![1.pic](http://xxx.pic)` ， 我将这个格式直接复制到文章的Markdown编辑器时，编辑器会**再次**添加格式，最终变成这样: `![[1.pic]](http://xxx.pic)(http://xxx.pic)`

**Comment by 88250** [comment]
谢谢反馈！

 @Vanessa219

**Comment by Vanessa219** [comment]
在 Markdown 编辑器还不完善的时候，是想方便的点击链接就可以查看附件内容了。那现在就改为附件上传后只显示原有地址，不封装为 A 标签了。

后期将会把上传也继承到编辑器中
