### ISSUE TITLE
图片上传改进

### ISSUE THREAD

**Issue by wells1013** [b3log/solo#12219]
在markdown 下粘贴图片 很不友好，贴了后等半天，在上传文件列表里才有贴的图片，而markdown 编辑器里没有自动填写上图片链接。
希望能够有个上传的动画，然后自动填充markdown 编辑器里。如果能够将七牛的图片处理逻辑在家上来那就完美了

**Comment by 88250** [comment]
谢谢反馈，后面会做改进的。

**Comment by 88250** [comment]
1. 剪贴板存在图片的处理
2. 手动上传时的处理

@Vanessa219

**Comment by leogong** [comment]
Mark

**Comment by wells1013** [comment]
1.8 什么时候出啊？

**Comment by 88250** [comment]
@wells1013 预计明年 1 月份，快了

**Comment by Vanessa219** [comment]
@leogong @wells1013

**Comment by Vanessa219** [comment]
@leogong @wells1013
