### ISSUE TITLE
七牛上传支持改进

### ISSUE THREAD

**Issue by undersky** [b3log/solo#12210]
当使用写文章界面的上传文件功能上传到七牛返回的地址在solo1.7中是这个形式的`![](http:// domain.com)`,
在 **http://** 后面多了一个空格.如果直接拷到编译器中，文章图片显示不了。

另外，这个上传文件感觉功能不稳定啊，慢而且失败率高。我VPS是日本的。

**Comment by 88250** [comment]
这个问题应该是因为在 Solo 配置七牛时域名一栏有个首空格。需要加强一下程序，来个去除首尾空格的 trim，程序实现细节没注意，多谢反馈了，1.8 修复 :)

七牛的海外支持我没有测试过，有可能会出现你说的情况，可以看下七牛后台有没有什么配置可以打开之类的。

感谢你的反馈！
