### ISSUE TITLE
400 No URI for HttpChannelOverHttp

### ISSUE THREAD

**Issue by DarkRake** [b3log/solo#12215]
[WARN ]-[2016-11-17 13:30:42]-[org.eclipse.jetty.http.HttpParser:1347]: badMessage: 400 No URI for HttpChannelOverHttp@3d33184b{r=0,c=false,a=IDLE,uri=-}
昨晚在使用的时候，我首先通过git clone了一份到我的服务器上
通过mvn package编译了一次，配置完成之后，我修改了latke配置，修改为80端口和指定的域名，但通过域名进行访问时出现上述错误
使用nohup java -cp WEB-INF/lib/*:WEB-INF/classes org.b3log.solo.Starter &进行启动的，后台启动，启动过程正常

**Comment by 88250** [comment]
latke.props 里面的端口不是容器启动监听的端口，监听端口得带个参数 -lp，具体参数详解 -h

另外，关于 latke 相关的配置详解请看这里 https://hacpai.com/article/1474087427032
