### ISSUE TITLE
markdown导入导出

### ISSUE THREAD

**Issue by maobaolong** [b3log/solo#12223]
强烈建议增加markdown导入导出，参考csdn博客

**Comment by 88250** [comment]
麻烦贴个图说明一下，我刚刚在 CSDN 博客找了下没找到这个功能哦。

**Comment by ljf1172361058** [comment]
作者好,后台有没有markdown编辑器哇?感觉这个比较方便写文章

**Comment by 88250** [comment]
@ljf1172361058 偏好设定里面可以切换为 Markdown 编辑器的

**Comment by ljf1172361058** [comment]
多谢 @88250 
另外,能否提个小建议?
就是页面超时了再次进入就变成403的错误提示,感觉不是很友好,第一次看到这信息我还以为是服务器的问题,去服务器找了半天未果,发现原来只是页面超时了

**Comment by 88250** [comment]
@ljf1172361058 嗯，我看看换个文案应该会好一些，谢谢！

**Comment by maobaolong** [comment]
@88250 咱们solo还是有markdown编辑模式的。
目前我的需求是:
我写了很多markdown文章,希望导入solo博客，而不是一个个的贴进来。
每个markdown可以有固定的注释头部，可以获取文章主题、时间、作者、分类、keyword。
就像这样：  [linux 常用命令.md](https://github.com/maobaolong/mblnote/blob/master/public/_posts/%E6%8A%80%E6%9C%AF%E5%AD%A6%E4%B9%A0/linux/linux%20%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.md)
```
---
title: git
date: 2016-11-09 15:13:48
tags: [工具使用,git]
categories: 工具使用
keywords: 工具使用,git
description: 记录git的常用命令。
---
```

**Comment by maobaolong** [comment]
第一个目标：单文件的导入导出。
[csdn导入博客](http://write.blog.csdn.net/mdeditor)
![image](https://cloud.githubusercontent.com/assets/17329931/21979025/24e86902-dc18-11e6-9da4-eee91631dee8.png)

第二个目标：批量导入包含github技术博客头部注释格式的markdown文章,就是使用hexo生成技术博客

**Comment by maobaolong** [comment]
有了这个功能，以后就离不开solo了～ @88250  加油，大牛！

**Comment by ZephyrJung** [comment]
楼上说的这个功能不错哦
我经常使用Typora写东西，如果支持批量导入的话，的确会很方便

**Comment by 88250** [comment]
这....我感觉没什么用啊，不支持啦楼主。

**Comment by maobaolong** [comment]
这个可以有，如果退而求其次的话，至少支持solo导入导出md文件就可以了。你行的，看好你呦👍

**Comment by 88250** [comment]
@maobaolong 用手拷贝吧..因为这个不是大众需求，如果你急需，就自己改下代码吧 :)

**Comment by maobaolong** [comment]
好 我改好后提个PR,希望大神指点一下

**Comment by 88250** [comment]
@maobaolong 好的，你先试下吧

**Comment by maobaolong** [comment]
#关于markdown导出功能的必要性和可行性
## 必要性
现在博客网站众多，大家写日志笔记的地方有`CSDN博客(markdown)`、`github技术博客(markdown+hexo)`、`ITeye博客`、`印象笔记`、`有道云笔记`、`马克飞象`等等众多方法途径。

很久以前，大家比较喜欢在新浪博客和搜狐博客写文章，之后又在人人网、qq空间写文章。so，问题来了。如何把一个网站写的文章迁移到另一个博文系统呢，难道要一个个复制粘贴吗？正在写的博客网站数据丢失或停止维护怎么办？

答案只有一个，用markdown编写笔记文件。发布到多个日志博客系统。这样一个倒下了，另一个还可以导出原始markdown文件。

我的方法是，自己写很多markdown文件，传到github工程中保存，自己搭建seafile个人云进行备份存储。
使用hexo生成静态网页传到github的个人技术博客，以及把一些文章发布到csdn博客中。

## 可行性
**目前使用solo的markdown编辑器写的文章，在数据库中存储的日志记录，存储的是转换后的结果，这样从根本上就不能导出。要实现导出功能、的前提是服务器区分markdown日志，并存储原文。**

**Comment by 88250** [comment]
博客的接口有技术标准的，很多客户端都支持，搜索一下 MetaWeblog API 看看 :)

**Comment by ljf1172361058** [comment]
@maobaolong 但是同样的markdown博客发布到不同的平台会造成排版的错乱,我在hexo网站写了一篇markdown博客,放到csdn,solo都乱版了

**Comment by maobaolong** [comment]
## 实现方法

要实现导出功能的前提是服务器区分markdown日志，并**存储md原文**。参考**CSDN**，如果你写的是markdown文件，则直接存储原文，支持下载；如果写的不是markdown文件，则不支持下载。

如果solo实现这一点，可能需要新建一个数据库表存储上传的markdown文件。这样查看博客时读取文件，最好架缓存，把markdown原文传给markdown界面控件。

## 难点

需要在现有的存储日志方法上增加markdown的存储方法。

**Comment by maobaolong** [comment]
@ljf1172361058 同样的markdown，会有同样的结构，展现不同是不同的markdown插件支持不同造成的。

不过目前的solo已经支持markdown编辑器了，只是没有存储markdown原文，导致无法下载原文。

**Comment by 88250** [comment]
https://github.com/b3log/solo/issues/12293
