### ISSUE TITLE
deploy on wildfly 10

### ISSUE THREAD

**Issue by mmghasemi** [b3log/solo#12228]
Hi
I deploy solo on wildfly, but take this error:
`Unexpected HTTP response: 500 Request { "operation" => "add", "address" => [("deployment" => "solo.war")], "name" => "solo.war", "runtime-name" => "solo.war", "enabled" => true, "content" => [{ "path" => "/project/solo/target/solo.war", "archive" => false }] } Response Internal Server Error { "outcome" => "failed", "failure-description" => { "WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"solo.war\".POST_MODULE" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"solo.war\".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of deployment \"solo.war\" Caused by: java.lang.NoClassDefFoundError: Failed to link com/alibaba/druid/support/spring/stat/DruidStatInterceptor (Module \"deployment.solo.war:main\" from Service Module Loader): org/aopalliance/intercept/MethodInterceptor"}, "WFLYCTL0412: Required services that are not installed:" => ["jboss.deployment.unit.\"solo.war\".POST_MODULE"], "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined }, "rolled-back" => true }`

**Comment by 88250** [comment]
Please use Tomcat or Jetty, or standalone mode: 

Windows: `java -cp WEB-INF/lib/*;WEB-INF/classes org.b3log.solo.Starter`
Unix-like: `java -cp WEB-INF/lib/*:WEB-INF/classes org.b3log.solo.Starter`
