### ISSUE TITLE
next 皮肤细节改进

### ISSUE THREAD

**Issue by zjhch123** [b3log/solo#12240]
在手机模式下，代码块会丢失换行符
![image](https://cloud.githubusercontent.com/assets/12215513/22691786/056454cc-ed77-11e6-8462-48e8ada896ce.png)

把这个CSS取消掉可以解决
![image](https://cloud.githubusercontent.com/assets/12215513/22691812/1576aae0-ed77-11e6-8030-eb15142c2e22.png)

还有在手机模式下似乎没有办法能进后台，希望能提供一个入口…

**Comment by 88250** [comment]
@Vanessa219
