### ISSUE TITLE
关于前端源码中中后台文章管理如何获取文章列表的小疑问

### ISSUE THREAD

**Issue by TiSongWen** [b3log/solo#12249]
后台文章管理的链接是:  <a href="#article/article-list>文章管理</a>，当点击它时，就可以获取文章列表。

获取文章列表的源码在  [articleList.js](https://github.com/b3log/solo/blob/master/src/main/webapp/js/admin/articleList.js) 87行的 getList方法实现

**问题**
1.  谁调用了 getList方法
2.  包围文章列表的是 table标签，那是谁生成的table标签呢？

@Vanessa219  嘻嘻。希望您抽空解答下一个后台工程师的小困惑（实习的时候导师让自己一个人写完一整个项目，之前很少写前端，所以才仿照您的写法，不过关于admin中js的设计读起来是很吃力的）

**Comment by TiSongWen** [comment]
前端代码思路还是很清晰的，在浏览器上调试了一下便找到答案了。
执行顺序：
1.  Admin() 作为javascirpt的对象被初始化
2.  会绑定每个子功能js的函数功能
3.  当URL改变时，window下的hash值会改变，所以根据分析其hash可以拿到当前的URL，然后再去调用 与子功能绑定的 refresh 或是 init 方法
代码逻辑给100分。非常清晰的结构和思路

**Comment by 88250** [comment]
这几天一直在外面旅游，😺
