### ISSUE TITLE
Local data/image storage required!

### ISSUE THREAD

**Issue by beckno9** [b3log/solo#12257]
Because my server is in US Los Angleas, so I don't think QiNiu is a good choice to storage images and datas, recently I need to upload something to my blog, but I have no idea to connect to QiNiu, so I hope developpers add local data/image storage support.  
Also it seems that developpers should upgrade the version of TinyMCE, a new version is better than the older version in Solo.  
That's all what I want to say, I hope these problems can be solved soon!

**Comment by 88250** [comment]
1. About file upload please watch this issue https://github.com/b3log/solo/issues/12124
2. Editor using Markdown is recommended

Thank you!

**Comment by beckno9** [comment]
@88250 The editor's markdown support is not so good.
