### ISSUE TITLE
支持文章分类

### ISSUE THREAD

**Issue by lovexiaov** [b3log/solo#12256]
比如写了一个系列的文章，想把这部分文章独立成集，标签的功能太弱了，目前想到的做法是在后台【导航管理】中新建一个页面，手动添加文章链接，但这样有点麻烦，望考虑。
![image](https://cloud.githubusercontent.com/assets/5959755/24130678/0d37a34c-0e25-11e7-997c-e91513c53e49.png)

**Comment by 88250** [comment]
收到。以前曾经讨论过(#107)，看来是时候加入这个特性了，2.0 将进行实现 :)

**Comment by 88250** [comment]
目前考虑使用标签自动聚合的实现：

1. 后台定义分类，并配置该分类包含的标签
2. 查询某个分类文章列表时通过`分类->标签集->标签关联的文章`进行聚合

也就是说一篇文章在编辑时仍然是只需要打标签，访问分类时会根据该分类包含的标签将文章筛选出来。这是一个自底向上的信息架构，更灵活一些。

**Comment by blague** [comment]
为什么会说标签比分类弱？
分类比标签更局限。

**Comment by 88250** [comment]
@blague 我觉得是标签的粒度可能太细，有的用户习惯粒度粗一些，所以这个需求还是正常的。只是传统的分类太固定，编辑文章的时候还需要选，明显不科学。

**Comment by lovexiaov** [comment]
@88250 
D 大威武，想法很巧妙，赞一下。

@blague 
你把整句话联系起来读就好理解了，我说的是`**想把这部分文章独立成集，标签的功能太弱了**`。比如说我写了很多方面与 Android 相关的文章，有这么几个标签 `Android, Testing, Tricks, Resource`，那么我打算写一系列关于 Android 开发技巧的文章，有两个标签 `Android, Tricks`。如果我想单独展示这个系列的文章，用标签来过滤是不是弱了一点？我可能还会有 Python 方面的文章包含 `Tricks` 标签呢，JS 文章也可能包含 `Tricks` 标签呢？

**Comment by 88250** [comment]
@lovexiaov 社区的信息架构就是这样设计的，我觉得很好用，so copy to Solo！

**Comment by lovexiaov** [comment]
@88250 D 大棒棒哒~

**Comment by 88250** [comment]
这两天再测试一下，准备发布 2.0.0 了 :p

**Comment by lovexiaov** [comment]
等你好消息。

**Comment by 88250** [comment]
最新文档可参考[《Solo 标签聚合分类》](https://hacpai.com/article/1558320086126)。
