### ISSUE TITLE
关于前端 admin-lib.min.js 的问题

### ISSUE THREAD

**Issue by TiSongWen** [b3log/solo#12250]
在只引用了这个js文件的时候，调用 $("#tabs").tabs("setCurrent")函数的使用提示未找到 setting 属性

1. 这个js文件的作用是什么呢？ 
2. 它是依赖了哪些其他js库呢？
3. 我该如何直接使用它呢？

**Comment by Vanessa219** [comment]
1. 管理后台依赖的 JS 压缩合并
2. 依赖
        './src/main/webapp/js/lib/jquery/jquery.min.js',
        './src/main/webapp/js/lib/jquery/file-upload-9.10.1/vendor/jquery.ui.widget.js',
        './src/main/webapp/js/lib/jquery/file-upload-9.10.1/jquery.iframe-transport.js',
        './src/main/webapp/js/lib/jquery/file-upload-9.10.1/jquery.fileupload.js',
        './src/main/webapp/js/lib/jquery/jquery.bowknot.min.js',
        // codemirror
        './src/main/webapp/js/lib/CodeMirrorEditor/codemirror.js',
        './src/main/webapp/js/lib/CodeMirrorEditor/placeholder.js',
        './src/main/webapp/js/overwrite/codemirror/addon/hint/show-hint.js',
        './src/main/webapp/js/lib/CodeMirrorEditor/editor.js',
        './src/main/webapp/js/lib/to-markdown.js',
        './src/main/webapp/js/lib/highlight.js-9.6.0/highlight.pack.js'

3. 可直接使用，如依赖文件有改动，可以参照根目录的 gulp 进行使用

**Comment by Vanessa219** [comment]
欢迎到社区提问，可以直接 @Vanessa 哦

注册链接：https://hacpai.com/register?r=Vanessa
