### ISSUE TITLE
初始化耗时太久了

### ISSUE THREAD

**Issue by zongwu233** [b3log/solo#12267]
10分钟过去了。。 solo.log 的日志信息：
[INFO ]-[2017-04-17 16:50:16]-[org.b3log.solo.Starter:145]: Standalone mode, see [https://github.com/b3log/solo/wiki/standalone_mode] for more details.
[INFO ]-[2017-04-17 16:50:19]-[org.b3log.solo.SoloServletListener:229]: Please open browser and visit [http://localhost:8090] to init your Solo, and then enjoy it :-p
[INFO ]-[2017-04-17 16:50:19]-[org.b3log.solo.SoloServletListener:150]: Solo is running [http://localhost:8090]
[INFO ]-[2017-04-17 16:53:53]-[org.b3log.solo.Starter:145]: Standalone mode, see [https://github.com/b3log/solo/wiki/standalone_mode] for more details.
[INFO ]-[2017-04-17 16:53:56]-[org.b3log.solo.SoloServletListener:229]: Please open browser and visit [http://localhost:8080] to init your Solo, and then enjoy it :-p
[INFO ]-[2017-04-17 16:53:56]-[org.b3log.solo.SoloServletListener:150]: Solo is running [http://localhost:8080]

**Comment by 88250** [comment]
[INFO ]-[2017-04-17 16:53:56]-[org.b3log.solo.SoloServletListener:229]: Please open browser and visit [http://localhost:8080] to init your Solo, and then enjoy it :-p

你访问 http://localhost:8080 了吗？

**Comment by 88250** [comment]
我先关闭这个 issue 了，如果还有问题你直接回复就好 :)

**Comment by zongwu233** [comment]
是进入了 http://localhost:8080 之后，按照界面的指示点击初始化 等了N久没反应

**Comment by 88250** [comment]
你用的是 MySQL 还是 H2？
