### ISSUE TITLE
无法初始化

### ISSUE THREAD

**Issue by xavier-zy** [b3log/solo#12268]
在命令行进入solo目录，运行java -cp WEB-INF/lib/*:WEB-INF/classes org.b3log.solo.Starter，总是报错：错误: 找不到或无法加载主类 org.b3log.solo.Starter。WHY？？！！

**Comment by 88250** [comment]
你用的是我们打好的包还是自己构建的？

**Comment by xavier-zy** [comment]
我是直接将solo下载解压后，在终端里跑那个命令的，一直显示找不到Starter类。Mac OSX

获取 Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by 88250** [comment]
刚刚在 Mac 上面试了下，可以启动的。。你的 JDK 是 8 么？

**Comment by 88250** [comment]
我先关闭这个 issue 了，有情况直接回复就好。
