### ISSUE TITLE
回复提醒邮件模板无效

### ISSUE THREAD

**Issue by iTanken** [b3log/solo#12266]
#### 在 Solo 后台管理中修改了 `回复提醒邮件模板`，如图：
> ![reply-mail-template](https://thumbnail0.baidupcs.com/thumbnail/9f1afe8cd0184bc6966b358bf0ccc35f?fid=591244744-250528-496399946034293&time=1492236000&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-RwxcRpdQnx7PzTTRKGlgIfLBMTo%3d&expires=8h&chkbd=0&chkv=0&dp-logid=2425888599863306198&dp-callid=0&size=c1440_u900&quality=90)

#### 但是在回复后收到的邮件内容是这样的：
> ![mail-content](https://thumbnail0.baidupcs.com/thumbnail/0909473538bf82be4ca59f38c58c237e?fid=591244744-250528-803840442525498&time=1492236000&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-CGVx63j3uphzLtVw7rPfkUvG5HQ%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=2425754330047795160&dp-callid=0&size=c1440_u900&quality=90)

所以说回复提醒的邮件模板没有生效，希望在下个版本能够修复这个问题，谢谢。

**Comment by iTanken** [comment]
同时还有一个问题就是，回复的邮件没有发送到回帖时留下的邮箱，而是发送到了管理员的邮箱。

**Comment by iTanken** [comment]
搞不懂，有的时候可以，有的时候不可以，还老报错

> ![屏幕快照 2017-04-15 下午7.08.27.jpg](//ohwkskjbt.bkt.clouddn.com/b23a8f18232e43d39eca15c1195f87b3.jpg)

> ![屏幕快照 2017-04-15 下午7.08.06.jpg](//ohwkskjbt.bkt.clouddn.com/d9c55f28e143492cb9b29653e5090a2b.jpg)

**Comment by 88250** [comment]
收到，稍后排查一下，谢谢反馈！

**Comment by 88250** [comment]
1. A 回复 B 的时候是肯定会发给管理员的，因为回复也是一个评论，需要提醒管理员的
2. A 回复 B 而 B 没有收到邮件可能是不稳定，被邮件提供商过滤了
3. 邮件模版不生效的问题我这里试了下，没有重现

我先关闭这个 issue 了，如果你那里能重新再 reopen，谢谢！

**Comment by iTanken** [comment]
那好吧
