### ISSUE TITLE
支持全文搜索

### ISSUE THREAD

**Issue by sealake** [b3log/solo#12261]
如题。
部署了1.9.0 之后，发现部分主题带了搜索框，但是使用的是百度站内搜索，并不能达到检索目的。
希望能够实现全文检索的功能。

令，solo是非常赞的项目，多谢。

**Comment by 88250** [comment]
收到。只是实现方式有点纠结：

* 使用 ES 之类的引擎：会增加搭建成本
* 使用 MySQL 全文检索/like：似乎比较折中，只是不清楚 H2 的支持如何
* 使用全内存缓存：会增加内存使用量

你有什么建议么？

**Comment by LightlyFly** [comment]
使用Solr搭建

**Comment by 88250** [comment]
@LightlyFly 这样用户用起来比较麻烦，目前我还是觉得进行全量内存缓存比较可行

**Comment by sealake** [comment]
H2支持 fulltext 检索. 
mysql 和 es 原生都是不支持中文分词的, 需要安装中文分词插件.
建议使用 es. 部署成本的话,可以考虑提供 docker 镜像的方式.

**Comment by iTanken** [comment]
刚刚试了一下 H2，支持 like 模糊查询，简单的查询在 0~20ms 之间：
![H2-like.jpg](https://img.hacpai.com/file/2017/6/3ec26ba701d24e8e931427723a3bd629-2017060510.57.01.jpg) 
不过是区分大小写的，用 Java 和 JAVA 查出来的结果是不同的：
SELECT OID, ARTICLETITLE, ARTICLEPERMALINK FROM B3_SOLO_ARTICLE where ARTICLETITLE like '%Java%' or ARTICLECONTENT  like '%JAVA%'

**Comment by user20161119** [comment]
楼上的建议都太复杂了。搜索框跳转到google，百度 site:xx.solo.com keywords怎么样？

**Comment by 88250** [comment]
开始使用 like 进行实现了。

**Comment by Adrift001** [comment]
全内存缓存也用不了多少内存...1000篇博客能有5M?

**Comment by 88250** [comment]
@Adrift001 木已成舟

**Comment by zh-h** [comment]
wordpress 就是用like吧？
