### ISSUE TITLE
Markdown 编辑器中的 icon 添加 tooltip

### ISSUE THREAD

**Issue by LyZane** [b3log/solo#12276]
这些个icon啥意思全靠猜，点了个像是upload的icon，然后选了张图片，确定，弹出个error，啥意思？

这些个icon干啥的？

**Comment by Vanessa219** [comment]
你满血复活了么

**Comment by LyZane** [comment]
不是我说你们，要不是我有这么多年独立BUG制作人的经验，这博客系统我都不一定能搞懂怎么用。
