### ISSUE TITLE
用mysql 数据库的时候有BUG，我已经本地fix

### ISSUE THREAD

**Issue by winjeg** [b3log/solo#12279]
repository.json 中option 是mysql 关键字， 你用这个关键字做表明本身就是禁忌的， 
如果非要用关键字做表明，需要加反引号来表示它不是关键字，否则会抛语法错误，
如果要最快的fix， 需要改文(repository.json)件中的一段为
     "name": "`option`",
及java文件中 Option.java 第36行需要改为： 
      public static final String OPTION = "`option`";

还有个建议:
你们Mysql的表设计的性能会非常糟糕，
mysql语法本身是不区分大小写的， 你们给出的大小写的字段名字意义不大
现在流行的与mysql 进行交互的组件是mybatis 等...
很多表都没有索引... 这在数据量大的时候必定成为性能问题....

btw 注册你们Bbs竟然还要邀请码...

**Comment by 88250** [comment]
有表前缀的，不用担心保留字问题 :)

性能问题等碰到再解决了，多谢多谢！！

**Comment by winjeg** [comment]
我吧表前缀设置为空了，哈哈。。
