### ISSUE TITLE
Logo 更新

### ISSUE THREAD

**Issue by winjeg** [b3log/solo#12278]
![3123](https://cloud.githubusercontent.com/assets/7270177/25376660/9172bf84-29d7-11e7-8aac-cdbee73f0906.png)

**Comment by 88250** [comment]
看上去蛮不错啊！我找点人来围观！

**Comment by AngongerLee** [comment]
看我头像，而且是不是有点污啊

**Comment by pencilso** [comment]
有种怪异的感觉

**Comment by 88250** [comment]
@AngongerLee 你怎么看出污点的？
@pencilso 有种宗教相关的感觉？

**Comment by AngongerLee** [comment]
@winjeg 换换色怎么样，我觉得会更好

**Comment by 09apple** [comment]
把S斜靠在L上会不会好点

**Comment by wangtonghe** [comment]
把两个圈去掉会不会好些？

**Comment by AngongerLee** [comment]
@88250 因为我想起来了3%的那张图

**Comment by smart-coding** [comment]
把S弄小一些，会协调一点吧，让它看上去是一个人倚靠在墙角的感觉，现在S太大不好看...

**Comment by gfafei** [comment]
看着我有点晕。。。

**Comment by 88250** [comment]
@AngongerLee 我 get 不到你说的 😓

**Comment by winjeg** [comment]
logo 这个东西， 其实如果不是考虑到在较小尺寸的情况下可以做的比较好看， 最基本的就是要体现
项目， 或者项目的主要内容。
然后就是尽量简单，色彩可以单调或多，但一定要简单不能复杂，否则别人不好记。
大公司的logo 基本都是很简单的图形比附 facebook google,  qq, twitter, 之类的

**Comment by AngongerLee** [comment]
@88250 这个 
![image](https://cloud.githubusercontent.com/assets/12672392/25385784/ae013ff2-29f7-11e7-8f82-c4a1fa6256e3.png)

**Comment by VirtualPier** [comment]
觉得奇怪的肯定不止我一个

**Comment by hao-lee** [comment]
跟蛇一样，感觉不好看。

**Comment by 88250** [comment]
https://hacpai.com/article/1493367433362

**Comment by Vanessa219** [comment]
来2发
![solo-logo2](https://cloud.githubusercontent.com/assets/970828/25862344/43a30860-351a-11e7-8296-c5b1213d0541.png)
![solo-logo1](https://cloud.githubusercontent.com/assets/970828/25862394/7a9fe342-351a-11e7-845a-68f29907459f.png)

**Comment by usherzhao** [comment]
怎么感觉都是跟 俄罗斯方块一样....是不是小时候玩多了?

**Comment by meikaiyipian** [comment]
第一个不错。。。
不过也许可以做成太极图那种样子？
实在想不出什么好点子。。。

**Comment by iiiyu** [comment]
![1](https://cloud.githubusercontent.com/assets/1130144/25903459/0b5ac6ea-35cf-11e7-894e-8067c5b929dc.png)
![2](https://cloud.githubusercontent.com/assets/1130144/25903466/0f222d7c-35cf-11e7-9b04-a0e724453a89.png)
![4](https://cloud.githubusercontent.com/assets/1130144/25903472/1251be2c-35cf-11e7-9a69-a21142484d35.png)
![3](https://cloud.githubusercontent.com/assets/1130144/25903473/12906c9e-35cf-11e7-97a7-ffa286ed1930.png)

**Comment by mindfocus** [comment]
搞个独占的吉祥物吧

**Comment by 88250** [comment]
@Vanessa219 新鲜出炉


![solo-mid](https://cloud.githubusercontent.com/assets/873584/26024667/c031e40a-3808-11e7-9176-f2c9af01bd64.png)

**Comment by ZephyrJung** [comment]
楼上那个好奇怪啊
确定把这个issue关了么。。

**Comment by 88250** [comment]
@ZephyrJung 关了，这个 logo 感觉还行。

**Comment by iTanken** [comment]
说实话，真的不太协调

**Comment by 88250** [comment]
@iTanken 先这么着吧，也许过一久就习惯了呢。
