### ISSUE TITLE
域名访问

### ISSUE THREAD

**Issue by LeslieVickllny** [b3log/solo#12271]
前缀加上www时error: Font from origin 'http://vickllny.top' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.vickllny.top' is therefore not allowed access.

没有前缀www时  font icon可以正常显示

**Comment by 88250** [comment]
抱歉现在才看到这个 issue.... 最新版本应该解决这个问题了。
