### ISSUE TITLE
更新分类标签计数错误

### ISSUE THREAD

**Issue by 1102568869** [b3log/solo#12274]
CategoryConsole类中updateCategory方法355行-365行
```          
categoryMgmtService.updateCategory(categoryId, category);
            categoryMgmtService.removeCategoryTags(categoryId); // remove old relations

            // add new relations
            for (final JSONObject tag : tags) {
                final JSONObject categoryTag = new JSONObject();
                categoryTag.put(Category.CATEGORY + "_" + Keys.OBJECT_ID, categoryId);
                categoryTag.put(Tag.TAG + "_" + Keys.OBJECT_ID, tag.optString(Keys.OBJECT_ID));

                categoryMgmtService.addCategoryTag(categoryTag);
            }
```
没有细看整体逻辑,但是大体看来更新分类和标签关联表记录的实现做法是先删掉所有关联记录,然后重新添加新的所有关联tag;但是在categoryMgmtService.addCategoryTag(categoryTag)操作中有 category.put(Category.CATEGORY_TAG_CNT, category.optInt(Category.CATEGORY_TAG_CNT) + 1);一句话,而在  categoryMgmtService.updateCategory(categoryId, category);
            categoryMgmtService.removeCategoryTags(categoryId); 两个逻辑中没有将计数置零的操作,导致每次更新分类就会将分类的tags计数再次累加tags的个数;

看到 categoryMgmtService.updateCategory(categoryId, category);逻辑中有 category.put(Category.CATEGORY_TAG_CNT, oldCategory.optInt(Category.CATEGORY_TAG_CNT));这样一个操作,初步看了一下 没有被其他地方引用,建议修改为category.put(Category.CATEGORY_TAG_CNT, 0);

**Comment by 88250** [comment]
修复方案是在每次添加分类标签时现查关联表来获取标签计数，这样可以将老数据的错误进行订正。非常感谢你的帮助！

**Comment by 1102568869** [comment]
其实我觉得最奇怪的是 这个count为什么不是统计这个分类下所有标签的文章总数?而是标签总数~hammm后面括号挂个2结果下面文章一大堆,感觉很奇怪诶~你的标签后面的括号不是文章数量嘛~

**Comment by 88250** [comment]
标签数也可以的嘛，我觉得。
