### ISSUE TITLE
改进 B3log Key 设置

### ISSUE THREAD

**Issue by LyZane** [b3log/solo#12277]
这个东西太懵逼了，几年过去了一点改善都没有，还是实验室状态的感觉，不像个运营了几年的产品。

你们得在填这个东西的边上加点说明，我都帮你们写好了：

> 有一个叫做黑客派（此处加链接，跳到注册页，账号/邮箱 直接帮人填好）的程序员社区，挺不错的，Solo可以与该社区做关联，使得在Solo中发布的文章自动同步到社区中去，让更多人分享你的智慧。
> **在注册黑客派账号时，请务必使用与当前B3log账号相同的邮箱。**

@88250  写的“[开放 API，欢迎各位独立博客主进行连接](https://hacpai.com/article/1457158841475)” 太抽象了，不到我这么牛逼根本不知道发生了什么事。

你们对新用户太不友好了！

另外，B3log Key这个东西就不该让用户自己输入，没必要，生成个GUID，边上放个“复制”button，倍贴心。

**Comment by 88250** [comment]
改善还是有点的：现在 Solo 会自动同步账号到社区
key 的生成确实应该有个按钮 @Vanessa219

**Comment by 88250** [comment]
呃，等等，Solo 这边的 key 是自动生成的，不能更新的。只有社区那边可以更新。

**Comment by LyZane** [comment]
诶？什么时候改的~

**Comment by 88250** [comment]
应该有两年了，所以 key 设置其实只能在社区做。
