### ISSUE TITLE
签名档预览

### ISSUE THREAD

**Issue by LyZane** [b3log/solo#12275]
年纪大了，不太记得三个签名档都写的是啥了，又懒得切出去看~

**Comment by Vanessa219** [comment]
我记得以前有的，后面又给去掉了。。。

**Comment by 88250** [comment]
的确，以前有的，后来去掉了，原因：可能存在脚本

**Comment by iTanken** [comment]
> 的确，以前有的，后来去掉了，原因：可能存在脚本

所以因此也不能把签名档同步到社区是吧？

**Comment by 88250** [comment]
@iTanken 嗯。
