### ISSUE TITLE
Xml的标记粘贴不到solo的编辑器

### ISSUE THREAD

**Issue by pencilso** [b3log/solo#12282]
本想粘贴Android的权限到solo的，因为是拿MarkdownPad编写的文档。
然后从MarkdownPad复制到solo的时候复制不过来，在电脑上新建文本文档，先粘贴到文本文档，再从文本文档粘贴到solo后就可以了。
MarkdownPad里的样子：
![qq 20170427134854](https://cloud.githubusercontent.com/assets/16483654/25469722/9fb1e53c-2b50-11e7-9aa3-4e17691de97f.png)
粘贴到solo的样子:
![qq 20170427134947](https://cloud.githubusercontent.com/assets/16483654/25469734/b2235098-2b50-11e7-8ff3-5858a14dce0b.png)
原文:
```
<uses-permission android:name="android.permission.BLUETOOTH" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```

**Comment by 88250** [comment]
谢谢反馈， @Vanessa219 诊断一下
