### ISSUE TITLE
移除 HTML 编辑器

### ISSUE THREAD

**Issue by 88250** [b3log/solo#12285]
目前支持的 HTML 编辑器（TinyMCE/KindEditor）比较老，存在一些安全隐患，并且目前主流的编辑器是 Markdown，所以将在 2.1.0 版本中移除 HTML 编辑器支持，只提供 Markdown 编辑器。

**Comment by meikaiyipian** [comment]
如果想要在编辑器里加额外的功能，可以怎么做呢

**Comment by 88250** [comment]
@meikaiyipian 比如加什么功能

**Comment by meikaiyipian** [comment]
@88250 呃。。。其实我是想在 sym 的编辑器里加一个排盘的功能，但在这说似乎有点不合适
