### ISSUE TITLE
markdown 没有脚注功能实在说不过去啊

### ISSUE THREAD

**Issue by docong** [b3log/solo#12290]
脚注[^footnote] 不支持，不行啊

**Comment by 88250** [comment]
收到，等研究一下看看，谢谢反馈

**Comment by 88250** [comment]
MD 引擎没支持，所以暂时实现不了，抱歉了。

**Comment by jueshali** [comment]
使用这个假装有吧<sup>1</sup>

**Comment by jueshali** [comment]
`<sup>1</sup>`

**Comment by 88250** [comment]
@jueshali 后续会考虑在 Lute 引擎中实现 https://github.com/b3log/lute/issues/21
