### ISSUE TITLE
大V，来领Bug了。

### ISSUE THREAD

**Issue by pencilso** [b3log/solo#12298]
![qq 20170523120720](https://cloud.githubusercontent.com/assets/16483654/26338205/d60bd772-3fb0-11e7-8a6b-8eb87eae5058.png)
预览的时候，代码xia显示成这样子了，按浏览器的刷新按钮刷几次又正常了
![qq 20170523121100](https://cloud.githubusercontent.com/assets/16483654/26338216/ec63589c-3fb0-11e7-8e5b-aec948e5291e.png)

**Comment by Vanessa219** [comment]
highlight 没有下载下来。

**Comment by 88250** [comment]
那应该是网络问题，我关闭了。
