### ISSUE TITLE
solo的91PHP皮肤

### ISSUE THREAD

**Issue by pencilso** [b3log/solo#12292]
一更新91PHP的皮肤后，https的小绿锁就没了，Finding 和 yilia主题 都可以有小绿锁，但是一还上91PHP 小绿锁就没了

**Comment by 88250** [comment]
麻烦帮忙看下 F12

**Comment by Vanessa219** [comment]
@pencilso 看了一下没有什么 http 的请求，如果还有问题，可以把博客地址发我一下

**Comment by pencilso** [comment]
javac.io

**Comment by Vanessa219** [comment]
@pencilso Mixed Content: The page at 'https://javac.io/' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://zhannei.baidu.com/cse/site'. This endpoint should be made available over a secure connection.

**Comment by pencilso** [comment]
咦   怎么把这玩意去了？ http://zhannei.baidu.com/cse/site'

**Comment by 88250** [comment]
看上去是百度的站内搜索

**Comment by pencilso** [comment]
是博客上的一个搜索按钮所导致的，但是瞅了半天，一脸无奈，不知道到哪里把去把这个给删了

**Comment by 88250** [comment]
全局搜索这个字符串
