### ISSUE TITLE
solo用户指南的url失效了？

### ISSUE THREAD

**Issue by winer632** [b3log/solo#12291]
https://hacpai.com/article/1492881378588
失效了？

**Comment by 88250** [comment]
访问报错么还是？

**Comment by winer632** [comment]
500 Internal Server Error!

![image](https://cloud.githubusercontent.com/assets/4931801/25792611/21139010-33fa-11e7-96df-0e9bca97b598.png)

**Comment by 88250** [comment]
看来是 [Sym](https://github.com/b3log/symphony) 的 bug，谢谢反馈。你先注册一下，登录状态下访问应该是 OK 的。
