### ISSUE TITLE
初次访问加载不了js图片等静态资源

### ISSUE THREAD

**Issue by peng051410** [b3log/solo#12306]
您好，我在使用solo中，初次访问发现js图片等静态资源找不到，截图如下：
![image](https://cloud.githubusercontent.com/assets/5512326/26769443/a9f4c2d0-49e1-11e7-803b-4e3cced3c297.png)
请问一下是什么问题？我需要进行其它的配置吗？

**Comment by 88250** [comment]
请看下 https://hacpai.com/article/1474087427032
