### ISSUE TITLE
小菜鸟前来请教大牛，关于404的问题~

### ISSUE THREAD

**Issue by 1078715125** [b3log/solo#12301]
如题，小弟有个疑问，如下有两个连接，
a: **http://www.guoyaxin.club/solo/js/1.jsp**
b: **http://www.guoyaxin.club/solo/js/1.js**
这a和b的404的效果不一样！！！
初步怀疑解析ant风格路径将b解析成静态文件内部转发后404，a是主动设置status为404。。

**特来请教大牛，为啥这两个404效果不一样？**

**Comment by 88250** [comment]
b 命中了静态资源解析模式（在 WEB-INF/static-resources.xml 中配置），静态资源会交给容器 `default servlet` 进行处理，404 就看容器的实现了。
