### ISSUE TITLE
一篇博客生成了两个目录

### ISSUE THREAD

**Issue by xinzhongtianxia** [b3log/solo#12316]
![image](https://user-images.githubusercontent.com/16996964/27221128-17200802-52ba-11e7-840a-1d1e43acbd72.png)

**Comment by 88250** [comment]
这个确实是个 bug，但是非常幽灵，小概率出现。临时解决可以禁用再启用 TOC 插件，如果不行就重启一下服务。

后面有空我会仔细看看的，谢谢反馈！

**Comment by 88250** [comment]
对了，你是使用独立模式还是容器模式启动的？

**Comment by liweiwei** [comment]
这 bug 一直都存在我居然没发现。
我用的 容器模式。

**Comment by xinzhongtianxia** [comment]
我用的也是容器模式

**Comment by 88250** [comment]
这个 bug 很有可能要成为永久的谜了....

**Comment by jetablezhu** [comment]
看下数据库中保存的目录有没有重复，如果没有就是渲染部分的bug，如果有就是生成目录的bug

**Comment by 88250** [comment]
@jetablezhu 估计是插件机制有问题，触发了两次，谢谢关注，后面我尽量修复。
