### ISSUE TITLE
安装solo出现问题

### ISSUE THREAD

**Issue by Mark110** [b3log/solo#12310]
执行java -cp WEB-INF/lib/*;WEB-INF/classes org.b3log.solo.Starter出现了错误: 找不到或无法加载主类 org.b3log.solo.Starter

**Comment by 88250** [comment]
你是用的我们打好的包么？

**Comment by 88250** [comment]
请先看一下[用户手册](https://hacpai.com/article/1492881378588)，还有问题随时欢迎交流 :)

**Comment by Mark110** [comment]
你说的是war包吗？还是什么包？

**Comment by 88250** [comment]
嗯，war 包啊。

**Comment by user20161119** [comment]
这个问题，我在Windows下也有，后来切到Linux折腾了，就没管了。
