### ISSUE TITLE
关于WordPrss博客对接

### ISSUE THREAD

**Issue by aaaol** [b3log/solo#12324]
一直有一个想法 WP作为博客是很好的选择 但是它有一个缺陷那就是没有社区板块，为了解决这个问题刚好这个开源程序可以搞定，对接用户注册数据免去重新注册 希望能够采纳

**Comment by 88250** [comment]
没有看明白你的意思，请详细描述一下需求和使用场景。

**Comment by aaaol** [comment]
就是用户注册信息对接   WP站点注册后 到solo这里无需再次注册

**Comment by 88250** [comment]
哦，这个可以改一下 WP，然后调用 Solo 的注册接口。
