### ISSUE TITLE
部分皮肤导航目录调优

### ISSUE THREAD

**Issue by genericyzh** [b3log/solo#12325]
请问这个网站http://88250.b3log.org/
是用最新版的solo吗？发现【菜单导航消失后要回到最顶部点击才显示回来 】的问题；
而且点击文章内容也会把菜单导航去掉，体验太不好了。

**Comment by 88250** [comment]
嗯，目前是这样的，你的建议是？

**Comment by genericyzh** [comment]
觉得用户自己点击关闭菜单导航的按钮才关闭比较好；
而且菜单导航的按钮应该悬浮，不然每次都要滚到最上面才能点出来，然后再翻到刚才看到的内容，太麻烦；
当前内容最好能跟菜单导航高亮对应；
这种效果体验好挺多的：
http://tedhacker.top/2016/12/23/Mybatis%E4%BD%BF%E7%94%A8%E7%AE%80%E8%AE%B0/

**Comment by 88250** [comment]
好的，谢谢。 

@Vanessa219 麻烦帮忙修改一下。

**Comment by Vanessa219** [comment]
收到
* 对 http://88250.b3log.org/?skin=next 皮肤目录进行高亮
* 对 http://88250.b3log.org/?skin=finding 皮肤进行以下修改
 1. 菜单和关闭按钮悬浮
 2. 点击文章页面目录不消失
 3. 目录进行高亮

**Comment by Vanessa219** [comment]
https://github.com/b3log/solo-skins/commit/679cfbe392ff67f9b3091652a7b8327cdf37ef00
