### ISSUE TITLE
solo首页文章列表和文章详情没有标识文章作者

### ISSUE THREAD

**Issue by xiaojunj** [b3log/solo#12320]
列表和详情 应该有一个文章的作者标识位

**Comment by Vanessa219** [comment]
请问是那一个皮肤呢？

**Comment by xiaojunj** [comment]
默认皮肤






------------------ 原始邮件 ------------------
发件人: "Vanesssa";<notifications@github.com>;
发送时间: 2017年7月14日(星期五) 下午2:45
收件人: "b3log/solo"<solo@noreply.github.com>; 
抄送: "___少 2.3。"<89065056@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [b3log/solo] solo首页文章列表和文章详情没有标识文章作者 (#12320)




请问是那一个皮肤呢？

**Comment by Vanessa219** [comment]
@xiaojunj 每个版本的默认皮肤都不一样，请访问 admin-index.do#tools/preference/skins 这个路径后把高亮的皮肤下的名字发我。谢谢

**Comment by 88250** [comment]
我先关闭这个 issue 了，如有需要 @xiaojunj 你直接 reopen 就行。
