### ISSUE TITLE
How to solve this problem？

### ISSUE THREAD

**Issue by apples398** [b3log/solo#12322]
When package the solo.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project solo: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: There was an error in the forked process
[ERROR] java.lang.UnsupportedClassVersionError: org/b3log/latke/repository/Repository : Unsupported major.minor version 52.0
![20170718144058](https://user-images.githubusercontent.com/19383199/28303746-2ccee6e8-6bc7-11e7-81eb-28d37dfe741c.png)

**Comment by 88250** [comment]
Please use JDK8.

**Comment by apples398** [comment]
I changed the JDK8.
But...
![image](https://user-images.githubusercontent.com/19383199/28304565-c8d92b04-6bca-11e7-93ef-25fd0813fca1.png)

<p>The first: &#39; <br/> The second: &AElig;</p>
http://gravatar.duoshuo.com/avatar/bd7e4673cf7fa4b4777353008c86e093?s=128
[ERROR]-[2017-07-18 14:59:59]-[org.b3log.latke.servlet.renderer.freemarker.AbstractFreeMarkerRenderer:115]: Not found template[author-articles.ftl]
[WARN ]-[2017-07-18 15:00:16]-[org.b3log.solo.service.CommentMgmtService:819]: Can not fetch thumbnail from Gravatar[commentEmail=d@hacpai.com]
[WARN ]-[2017-07-18 15:00:17]-[org.b3log.solo.service.CommentMgmtService:819]: Can not fetch thumbnail from Gravatar[commentEmail=d@hacpai.com]
[ERROR]-[2017-07-18 15:00:28]-[org.b3log.latke.mail.local.LocalMailService:44]: Sends mail failed
javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials r9sm2756673pfi.114 - gsmtp

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:826)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:761)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:685)
	at javax.mail.Service.connect(Service.java:317)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)
	at org.b3log.latke.mail.local.MailSender.sendMail(MailSender.java:159)
	at org.b3log.latke.mail.local.LocalMailService$1.run(LocalMailService.java:42)
	at java.lang.Thread.run(Thread.java:745)
[WARN ]-[2017-07-18 15:00:33]-[org.b3log.solo.api.metaweblog.MetaWeblogAPI:370]: Parses article create date failed with ISO8601, retry to parse with pattern[yyyy-MM-dd'T'HH:mm:ss, yyyyMMdd'T'HH:mm:ss'Z']
xxxxxcontent:<?xml version="1.0" encoding="UTF-8"?><methodResponse><params><param><value><string>1500361233065</string></value></param></params></methodResponse>
{
    "archiveDateArticleCount": 1,
    "archiveDatePublishedArticleCount": 1,
    "archiveTime": 1322668800000,
    "oId": "1500361233465"
}
[WARN ]-[2017-07-18 15:00:56]-[org.b3log.solo.service.CommentMgmtService:819]: Can not fetch thumbnail from Gravatar[commentEmail=comment email]
[WARN ]-[2017-07-18 15:00:56]-[org.b3log.solo.service.CommentMgmtService:819]: Can not fetch thumbnail from Gravatar[commentEmail=comment email]

**Comment by 88250** [comment]
Just disregard this warning messages.

**Comment by apples398** [comment]
Thanks...
