### ISSUE TITLE
solo 启动报错

### ISSUE THREAD

**Issue by user20161119** [b3log/solo#12332]
参考的：https://hacpai.com/article/1492881378588
windows 环境 使用文中的命令:``` java -cp WEB-INF/lib/*;WEB-INF/classes/ org.b3log.solo.Starter```
报错:
```错误: 找不到或无法加载主类 WEB-INF.lib.autolink-0.6.0.jar
bash: WEB-INF/classes: Is a directory
```
使用命令：``` java -cp WEB-INF/lib/*;WEB-INF/classes/* org.b3log.solo.Starter```
报错：
```
错误: 找不到或无法加载主类 WEB-INF.lib.autolink-0.6.0.jar
WEB-INF/classes/b3log.properties: line 23: rhythm.servePath=http://rhythm.b3log.org:80: No such file or directory
WEB-INF/classes/b3log.properties: line 24: symphony.servePath=https://hacpai.com:443: No such file or directory
```
从百度网盘下的war包和本地自己maven build的war包都是一样的错误

**Comment by user20161119** [comment]
Linux 下修改Jetty端口为8090了，还是报8080端口被占，还需要在哪修改端口配置？
`
https://github.com/b3log/solo/issues/12037] for more details.
[INFO ]-[2017-08-13 17:43:59]-[org.b3log.solo.SoloServletListener:240]: Please open browser and visit [http://localhost:8090] to init your Solo, and then enjoy it :-p
[INFO ]-[2017-08-13 17:43:59]-[org.b3log.solo.SoloServletListener:158]: Solo is running [http://localhost:8090]
[WARN ]-[2017-08-13 17:43:59]-[org.eclipse.jetty.util.component.AbstractLifeCycle:212]: FAILED ServerConnector@791d1f8b{HTTP/1.1}{0.0.0.0:8080}: java.net.BindException: Address already in use
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.b
`

**Comment by 88250** [comment]
你是需要使用独立模式还是容器模式？

**Comment by user20161119** [comment]
稍微解释一下我服务器的环境：
目前服务器上已经跑了一个tomcat（8080端口），solo打算使用独立模式运行，不放在现有tomcat环境中。
所以需要修改jetty的端口号（8090），但是启动还是报错了。

**Comment by 88250** [comment]
带参数 '-lp 8090' 了吗？具体可以 `-h` 看下帮助

**Comment by user20161119** [comment]
jetty端口，我通过修改latke.properties
`
# Browser visit port, 80 as usual, THIS IS NOT SERVER LISTEN PORT!
serverPort=8090`
这样不可以？

**Comment by 88250** [comment]
那个和监听端口不是一个东西，latke.props 的配置详解请看 https://hacpai.com/article/1474087427032

**Comment by user20161119** [comment]
可以启动了，但是启动日志令人费解，latke.properties中serverPort我改回8080了。
```
java -cp WEB-INF/lib/*:WEB-INF/classes org.b3log.solo.Starter -lp 8090
[INFO ]-[2017-08-14 13:10:20]-[org.b3log.solo.Starter:150]: Standalone mode, see [https://github.com/b3log/solo/issues/12037] for more details.
[INFO ]-[2017-08-14 13:10:24]-[org.b3log.solo.SoloServletListener:240]: Please open browser and visit [http://localhost:8080] to init your Solo, and then enjoy it :-p
[INFO ]-[2017-08-14 13:10:24]-[org.b3log.solo.SoloServletListener:158]: Solo is running [http://localhost:8080]
```
log中还是告诉用户solo跑在8080端口。

**Comment by 88250** [comment]
没有用反代的话监听端口和 latke.props 的必须一致。

**Comment by user20161119** [comment]
谢谢，我是能看明白这里面的配置和目录log的问题，blog也已经启动了，谢谢支持。

**Comment by 88250** [comment]
好的，还有什么问题的话随时提 😄

**Comment by user20161119** [comment]
`nohup java -cp WEB-INF/lib/*:WEB-INF/classes org.b3log.solo.Starter -lp 8090 `
nohup不是这么用吗？ctrl+c后process还是没了

**Comment by 88250** [comment]
1. nohup 后面还得加 `&` 具体你搜索一下
2. 日志看 log4j.props

**Comment by 88250** [comment]
试试 `nohup java -cp WEB-INF/lib/*:WEB-INF/classes org.b3log.solo.Starter >/dev/null 2>&1 &`

**Comment by 88250** [comment]
试试 `nohup java -cp WEB-INF/lib/*:WEB-INF/classes org.b3log.solo.Starter >/dev/null 2>&1 &`

**Comment by user20161119** [comment]
多谢，可以了

**Comment by user20161119** [comment]
@88250 有没有solo相关的qq群啊？solo怎么发音？

**Comment by 88250** [comment]
Q群 242561391；发音就是 Solo 😋
