### ISSUE TITLE
部署在服务器之后，启动之后访问不了，日志里面是这样写的，什么意思。

### ISSUE THREAD

**Issue by Johnnyww** [b3log/solo#12337]
16-Aug-2017 13:15:19.396 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/9.0.0.M26
16-Aug-2017 13:15:19.397 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Aug 2 2017 20:29:05 UTC
16-Aug-2017 13:15:19.398 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         9.0.0.0
16-Aug-2017 13:15:19.398 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
16-Aug-2017 13:15:19.398 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            3.10.0-514.26.2.el7.x86_64
16-Aug-2017 13:15:19.398 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
16-Aug-2017 13:15:19.398 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/java/jdk1.8.0_144/jre
16-Aug-2017 13:15:19.398 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_144-b01
16-Aug-2017 13:15:19.398 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
16-Aug-2017 13:15:19.398 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomact/apache-tomcat-9.0.0.M26
16-Aug-2017 13:15:19.398 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomact/apache-tomcat-9.0.0.M26
16-Aug-2017 13:15:19.398 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomact/apache-tomcat-9.0.0.M26/conf/logging.properties
16-Aug-2017 13:15:19.399 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
16-Aug-2017 13:15:19.399 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
16-Aug-2017 13:15:19.399 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
16-Aug-2017 13:15:19.399 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomact/apache-tomcat-9.0.0.M26
16-Aug-2017 13:15:19.399 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomact/apache-tomcat-9.0.0.M26
16-Aug-2017 13:15:19.399 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomact/apache-tomcat-9.0.0.M26/temp
16-Aug-2017 13:15:19.399 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
16-Aug-2017 13:15:19.632 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
16-Aug-2017 13:15:19.654 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
16-Aug-2017 13:15:19.679 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
16-Aug-2017 13:15:19.680 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
16-Aug-2017 13:15:19.693 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 931 ms
16-Aug-2017 13:15:19.722 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
16-Aug-2017 13:15:19.722 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/9.0.0.M26
16-Aug-2017 13:15:19.768 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomact/apache-tomcat-9.0.0.M26/webapps/solo-2.2.0.war]
16-Aug-2017 13:15:19.790 WARNING [main] org.apache.catalina.startup.SetContextPropertiesRule.begin [SetContextPropertiesRule]{Context} Setting property 'antiJARLocking' to 'true' did not find a matching property.
16-Aug-2017 13:15:21.546 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
16-Aug-2017 13:15:22.528 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
16-Aug-2017 13:17:34.052 WARNING [main] org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [131,524] milliseconds.
16-Aug-2017 13:17:34.064 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/solo-2.2.0] startup failed due to previous errors
16-Aug-2017 13:17:34.101 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomact/apache-tomcat-9.0.0.M26/webapps/solo-2.2.0.war] has finished in [134,334] ms

**Comment by 88250** [comment]
没看出哪里报错。

**Comment by Johnnyww** [comment]
[root@izwz93xjwyedbm6ctkzyzbz apache-tomcat-9.0.0.M26]# cd logs/
[root@izwz93xjwyedbm6ctkzyzbz logs]# tail -f ./catalina.out
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:657)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:355)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:495)
17-Aug-2017 20:36:30.502 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
17-Aug-2017 20:39:30.422 WARNING [main] org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [179,920] milliseconds.
**17-Aug-2017 20:39:30.433 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/solo-2.2.0] startup failed due to previous errors**
[INFO ]-[2017-08-17 20:39:30]-[org.b3log.solo.SoloServletListener:168]: Destroyed the context

加粗那里。。

**Comment by 88250** [comment]
没看出来怎么出错的。

**Comment by liweiwei** [comment]
我貌似遇到过这个问题，试试我的解决方案，看行不行？
关键点在于：
org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [179,920] milliseconds.

这个是解决方案的链接：
https://stackoverflow.com/questions/26431922/tomcat7-starts-too-late-on-ubuntu-14-04-x64-digitalocean#
