### ISSUE TITLE
切换皮肤问题

### ISSUE THREAD

**Issue by Johnnyww** [b3log/solo#12341]
之前自己拉整个项目下来，再下载皮肤的目录，打包之后，切换了finding皮肤，直接右上角的Menu不显示。。。
  然后现在下载了发布版本的包，切换了findding皮肤，现在Menu是显示了，但是点击没反应。。。
![111](https://user-images.githubusercontent.com/19776814/29738592-f2ddaf68-8a58-11e7-8ae4-d47ddede1160.PNG)

**Comment by 88250** [comment]
F12 看一下网络请求

**Comment by Johnnyww** [comment]
别的皮肤换了之后浏览器控制台没东西，finding输出了下面信息：
![222](https://user-images.githubusercontent.com/19776814/29738650-04ce21ce-8a5b-11e7-91f3-cb4a9956d954.PNG)

**Comment by 88250** [comment]
咦，我用的也是 finding，但没有出现你说的情况，要不你访问我的博客看看： http://88250.b3log.org/

**Comment by 88250** [comment]
我先关闭这个 issue 了，有问题的话直接跟帖艾特我吧。
