### ISSUE TITLE
checkout代码自己打包Solo.war部署启动报错

### ISSUE THREAD

**Issue by faylz** [b3log/solo#12342]
环境：tomcat7+jdk1.8.0_131
第一次启动时，报SEVERE: Error configuring application listener of class org.b3log.solo.SoloServletListener
java.lang.UnsupportedClassVersionError: org/b3log/solo/SoloServletListener : Unsupported major.minor version 52.0 (unable to load class org.b3log.solo.SoloServletListener)
后来我把 eclipse的complier 换成了1.7再编译重新打包，
第二次启动时，报Caused by: java.lang.UnsupportedClassVersionError: org/b3log/latke/servlet/renderer/AbstractHTTPResponseRenderer : Unsupported major.minor version 52.0 (unable to load class org.b3log.latke.servlet.renderer.AbstractHTTPResponseRenderer)
	at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2892)

AbstractHTTPResponseRenderer这个类是在latke-2.3.15.jar中的，怎么处理比较好？

**Comment by 88250** [comment]
1. 使用 JDK8
2. 使用最新版 Tomcat 试试
