### ISSUE TITLE
自定义导航增加图标配置

### ISSUE THREAD

**Issue by javmain** [b3log/solo#12345]
目前自定义导航没有图标，是否可以实现自定义某些图标。以导到自定义导航美观的效果。 @Vanessa219

**Comment by 88250** [comment]
有道理，等看下什么时候实现，这个要改表结构。

**Comment by javmain** [comment]
我发现这个网站有很多图标 http://fontawesome.io/，只需要引入css就可以，不过没有java图标，很遗憾。。。

**Comment by 88250** [comment]
* 将在表 page 中加入一个列 `pageIcon`，用于保存导航对应的图标链接，默认为空字符串
* 导航管理里面加入该字段编辑功能
* 皮肤需要判断该字段是否为空，不空的话显示图标

**Comment by javmain** [comment]
厉害
