### ISSUE TITLE
文章保存失败

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/solo#12340]
![2017-08-24 13-37-20](https://user-images.githubusercontent.com/2569600/29651094-694da4c0-88d1-11e7-8bd7-c2ca0a3cb72a.png)

V大说疑似emoji的问题
黑客派能够发表成功——https://hacpai.com/article/1503549518434 此处可get到原文

**Comment by 88250** [comment]
帖子里面用的字符 emoji，不应该会出现这个问题嘛。

**Comment by ZephyrJung** [comment]
对了，我不是直接在那里写的，是从typora写好后拷贝过去的，估计这里引起什么问题了

**Comment by 88250** [comment]
从帖子里面 copy 呢？

**Comment by ZephyrJung** [comment]
可以，就是emoji变得好大

**Comment by ZephyrJung** [comment]
http://zephyr.b3log.org/articles/2017/08/24/1503556502211.html 这是拷贝过来后的效果

**Comment by 88250** [comment]
从编辑的内容拷贝，不要前台拷贝啊。

**Comment by ZephyrJung** [comment]
:joy: 没事，大emoji我喜欢

**Comment by 88250** [comment]
那这个问题咋搞，没重现啊 😲

**Comment by ZephyrJung** [comment]
我自觉关闭

**Comment by Vanessa219** [comment]
@ZephyrJung 我觉得你应该自己坚持复现一下

**Comment by ZephyrJung** [comment]
下次再碰到了我再reOpen，反正不着急
