### ISSUE TITLE
通过NGINX使用HTTPS方式部署solo，图片无法显示

### ISSUE THREAD

**Issue by imxuelei** [b3log/solo#12348]
配置文件配置HTTPS协议
文章中的图片<img src="//xxx.xx/file/xx.png">
没指定协议默认使用了当前页面的协议，但七牛云图片地址是http的，导致访问异常。
不改代码修复该问题的方式：
配置自己二级域名文件服务器，Nginx拦截重定向到七牛http协议。（开始使用代理方式，后觉得纯属浪费流量）
location / {
            rewrite ^(.*) http://ovcmva1yy.bkt.clouddn.com$1 permanent;
           # proxy_pass http://ovcmva1yy.bkt.clouddn.com/;

        }

**Comment by 88250** [comment]
七牛那边绑定 https 域名应该就行了。

**Comment by imxuelei** [comment]
嗯，绑定https应该是没问题的，不过收费，，，

**Comment by 88250** [comment]
程序上面好像没法搞这个事情。

**Comment by 1102568869** [comment]
我每次是先把图片位置预留...然后跑到hacpai编辑文章...😄
