### ISSUE TITLE
Tomcat 9?

### ISSUE THREAD

**Issue by beckno9** [b3log/solo#12354]
我是用OneinStack安装服务器的，也就是最高只能安装Tomcat 8，但是安装手册上说要Tomcat 9？  
(img:黑人问号)

**Comment by 88250** [comment]
最好用 9，你试下 8 有没有问题，没有的话应该也可以。。

**Comment by beckno9** [comment]
@88250 我在8下试过，因为我之前是从老版本过度而来的，换了个VPS，以前的旧版可以在8下正常工作，但是现在的版本直接404，我觉得没有必要把版本要求搞得那么高

**Comment by 88250** [comment]
如果你的 tomcat 没有部署其他应用的话可以用独立模式运行 solo，这样更方便。

**Comment by beckno9** [comment]
@88250 提个建议啊，以后还是最好把Tomcat/Jetty要求改成8吧，要不然很麻烦

**Comment by 88250** [comment]
木已成舟了..

**Comment by beckno9** [comment]
@88250 总算能在浏览器中打开了，但是需要麻烦你帮忙解决一下这个
![img](https://image.ibb.co/kRjKBG/7_I2_O7_AB_6_WW_OHLFO_R9.png)

**Comment by beckno9** [comment]
latke.properties
![1](https://image.ibb.co/gRYwrG/latke.png)
local.properties
![2](https://image.ibb.co/kHFWQb/local.png)

**Comment by 88250** [comment]
请参考 https://hacpai.com/article/1474087427032

**Comment by beckno9** [comment]
@88250 我已经按照教程所写的完成了配置，但是还是这样的错误，求解

**Comment by 88250** [comment]
浏览器访问的时候带上端口 8080

**Comment by beckno9** [comment]
@88250 我已经做了nginx反向代理了，直接访问8080会523

**Comment by 88250** [comment]
你是不是改完配置没重启啊？

**Comment by beckno9** [comment]
@88250 我加你QQ聊吧

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/31383530-f92095e4-aded-11e7-87dc-eaae6a72b195.png)

这里还是 localhost，说明是 latke.props 没有生效啊。
