### ISSUE TITLE
首页初始化后无法登入后台.....

### ISSUE THREAD

**Issue by stateIs0** [b3log/solo#12365]
使用阿里云服务器, 使用 命令java -cp WEB-INF/lib/*:WEB-INF/classes org.b3log.solo.Starter启动.
配置 mysql 数据库, 开启了8080 ,80 端口. 发现登录时会发送一个OPTIONS 请求:

Request URL:http://thinkinjava.cn:8080/login
Request Method:OPTIONS
Status Code:404
Remote Address:47.93.205.234:8080
Referrer Policy:no-referrer-when-downgrade

报404, 然后我将接口改为可兼容 OPTIONS请求的接口, 服务器报500错误:
[ERROR]-[2017-11-07 22:49:07]-[org.b3log.solo.processor.LoginProcessor:230]: JSONObject["userEmail"] not found.

本地跑,调试都是可以的.不知道是什么问题????

**Comment by 88250** [comment]
开 F12 看请求，然后参考 https://hacpai.com/article/1474087427032 进行配置调整。
