### ISSUE TITLE
数学公式和流程图的展示

### ISSUE THREAD

**Issue by xiaodeshan** [b3log/solo#12360]
能否添加数学公式和流程图的展示功能，诸如[cmd markdown](https://www.zybuluo.com/mdeditor)可以展示数学公式和流程图

**Comment by 88250** [comment]
这个需求比较小众，暂时不添加了，请理解一下 😅

**Comment by xiaodeshan** [comment]
好的谢谢

**Comment by 88250** [comment]
v2.5.0 里面实现。

* 数学公式：https://github.com/mathjax/MathJax
* 流程图：https://github.com/adrai/flowchart.js

@Vanessa219

**Comment by Vanessa219** [comment]
@xiaodeshan 已在 2.5 分支实现

**Comment by xiaoyao2102** [comment]
您好请问一下，我之前用1.8.0，自己引入的mathjax。现在升级到了2.9.1，可以直接写公式了么？

**Comment by 88250** [comment]
@xiaoyao2102 现在支持数学公式了，升级的话你需要一个版本一个版本来，有点麻烦，不过建议升级，每个版本都跟上主线。

**Comment by 88250** [comment]
@xiaoyao2102 你参考下 https://github.com/b3log/solo/issues/12474 中提交的代码。
