### ISSUE TITLE
Markdown 渲染改进

### ISSUE THREAD

**Issue by xiaodeshan** [b3log/solo#12369]
当内容中有下划线"\_"时，文章后面的内容都会变成斜体，经查阅，“\_”需要进行转义为“\\\_”，但是转义后仍无法取消斜体。而且在代码片段中，如果有"_"存在，也会出现斜体的问题。

**Comment by 88250** [comment]
请给出一段 md 原文以方便测试。

**Comment by xiaodeshan** [comment]
md:
Transaction\_CHAINCODE\_DEPLOY
这是斜体文字

加转义字符也不可以
效果
![2.png](http://oy0bv3xen.bkt.clouddn.com/dee6fcc26fcd4f04892a28f344ce599d.png)
文本
![1.png](http://oy0bv3xen.bkt.clouddn.com/0230dfddfbcd416aa41424fa50b58b77.png)
第三方显示
![3.png](http://oy0bv3xen.bkt.clouddn.com/0f2fa15bb9d14b0c8124ac8218b26680.png)

**Comment by 88250** [comment]
收到，晚上我看一下代码，谢谢先。

**Comment by 88250** [comment]
在 v2.5.0 修复。
