### ISSUE TITLE
无法登录, F12是一个 options 请求,而源码中根本没有 login 相关的 option 请求.所以404

### ISSUE THREAD

**Issue by stateIs0** [b3log/solo#12366]
#### 以下是配置文件:

[<img width="511" alt="2017-11-08 12 08 58" src="https://user-images.githubusercontent.com/24973360/32503903-154e6cfc-c3a4-11e7-92f0-c7959234c70a.png">
](url)

#### 以下是 F12:

[
<img width="485" alt="2017-11-08 12 08 24" src="https://user-images.githubusercontent.com/24973360/32503956-3cfb675a-c3a4-11e7-970e-583c2936f660.png">
](url)

#### 以下是错误状况: 无法登录???
[
<img width="707" alt="2017-11-08 12 08 34" src="https://user-images.githubusercontent.com/24973360/32503993-54915582-c3a4-11e7-9b1e-04983872f2de.png">
](url)

很无奈.....如果修改源码, 让原本的 post 请求的 login 接口兼容 options, 就会报错.

**Comment by 88250** [comment]
我看你已经发布一篇文章了，应该没有问题了吧。

**Comment by 88250** [comment]
下个版本（v2.5.0）对 MD 渲染做了些改进，发布后记得升级 :)
