### ISSUE TITLE
markdown html支持

### ISSUE THREAD

**Issue by xiaodeshan** [b3log/solo#12374]
下面的md显示有异常，然后刚刚大概看了一下以前的问题，貌似移除了html的支持，请问solo以后重新会支持html标签吗？还是已经支持但是有bug..
[md文件](http://oy0bv3xen.bkt.clouddn.com/9fb67199f0cf450ea3b5337990f35cf3.md)

**Comment by 88250** [comment]
你好，HTML 标签是支持的，你给的文件我刚刚试了一下，`<span>` 标签可以正常渲染。
