### ISSUE TITLE
编辑器会出现乱码，不知道什么原因，求助

### ISSUE THREAD

**Issue by SmileHui** [b3log/solo#12379]
![qq 20171205201305](https://user-images.githubusercontent.com/11692730/33606585-e6f2b46a-d9f8-11e7-8a77-89efa8789ab3.jpg)

**Comment by 88250** [comment]
运行在 Linux 还是 Windows 上？容器模式还是独立模式？容器模式的话是 Tomcat 么？

**Comment by SmileHui** [comment]
运行在Linux上的用的Tomcat，Nginx做的反向代理，不知道是不是跟开了marked有关系，是时不时出现的

**Comment by 88250** [comment]
和 marked 应该没关系，估计是 tomcat 什么地方的配置不大对劲。你用独立模式启动看看？

**Comment by SmileHui** [comment]
我试试

**Comment by SmileHui** [comment]
应该是tomcat的问题，tomcat用服务启动的，手动启动就好像就正常了。。我再去查查。。

**Comment by 88250** [comment]
好的，谢谢反馈。
