### ISSUE TITLE
麻烦看一下，写文章的时候，总有一个乱码在这里

### ISSUE THREAD

**Issue by leihuazhe** [b3log/solo#12386]
![image.png](http://upload-images.jianshu.io/upload_images/6393906-7fb7578f2d557882.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by 88250** [comment]
这个乱码能删除么，提交后更新文章还有乱码吗？

另外麻烦给一下如下信息：

* 操作系统版本
* Tomcat/Jetty 版本

**Comment by leihuazhe** [comment]
tomcat9的版本，就是写文章的时候每行都有一个，但是写出来了，发布文章后没有。

**Comment by leihuazhe** [comment]
乱码不能删除

**Comment by 88250** [comment]
Tomcat 9 具体是哪个版本，我尝试本地重现一下。

**Comment by leihuazhe** [comment]
9.0.2

**Comment by 88250** [comment]
操作系统是 Linux 还是 Windows？

**Comment by leihuazhe** [comment]
Windows

**Comment by 88250** [comment]
好的，谢谢反馈。我现在在外面，估计要过几天才能具体看下，有进展会第一之间更新的。

**Comment by geyingauv** [comment]
我部署的时候也有乱码
下载的源代码自己打得war包
tomcat9.02
java 1.8.0_151
//*[@id="tabsPanel_article"]/div/div[2]/div/div[2]/div[6]/div[1]/div/div/div/div[5]/pre/span/span
![](https://i.loli.net/2018/01/06/5a50b65f1cc39.jpg)

奇怪的是在ide跑的时候并没有乱码同位置是
`<span cm-text="">&#8203;</span>`

不止这里,还有编辑器的按钮说明文本也是乱码
![](https://i.loli.net/2018/01/06/5a50b7f00e262.jpg)

**Comment by 88250** [comment]
看来这个问题主要就是出现在 Tomcat9 上，目前已知 Jetty 不会出现该问题。

**Comment by geyingauv** [comment]
我的乱码问题刚找到了
webapp/js/lib/compress/admin-lib.min.js
文件里command 和shift 使用的是特殊字符,还有光标和回车的地方是一个空占位符,字符也没有,不知道改用哪个字符集显示了  我开发环境是mac所以没有显示乱码
@88250

**Comment by 88250** [comment]
@geyingauv 收到，我再看看

**Comment by 88250** [comment]
Tomcat 9 中这样配置一下就可以解决：编辑 Tomcat 目录下 conf/web.xml，将 default servlet 加入初始参数：

```
<init-param>
    <param-name>fileEncoding</param-name>
    <param-value>utf-8</param-value>
</init-param>
```
