### ISSUE TITLE
不支付Mweb的语法

### ISSUE THREAD

**Issue by peng051410** [b3log/solo#12384]
您好，我在使用MWEB写博客时，文章上传至solo服务器上，有些markdown的标签没有被识别，而是直接显示出来了，请问有什么方法可以解决？

![markdown](https://user-images.githubusercontent.com/5512326/34397610-230b6780-eb3d-11e7-9ccd-e54e07af1e35.png)

==YES==这个是想高亮文字的样子！

**Comment by javmain** [comment]
建议换博客系统，底层不支持吧。

**Comment by 88250** [comment]
你是想加粗么？可以用 `**YES**` ，效果 **YES**
