### ISSUE TITLE
yilia 皮肤问题

### ISSUE THREAD

**Issue by 18053112850** [b3log/solo#12394]
![jps _v 7ia05 8 gu 1k3](https://user-images.githubusercontent.com/34642400/35468379-4ab44edc-0357-11e8-87b8-a1922bbb7503.png)
![utqyxyu o1xq11w3hu o n](https://user-images.githubusercontent.com/34642400/35468380-4ec0c622-0357-11e8-8483-59663e547c5f.png)
这种情况是什么原因呢

**Comment by Vanessa219** [comment]
@18053112850 已修复，请到 https://github.com/b3log/solo-skins 下载最新皮肤
