### ISSUE TITLE
Solo 2.5.0 的后台管理在最新的 Chrome 里无法展开工具菜单：

### ISSUE THREAD

**Issue by iTanken** [b3log/solo#12391]
Solo 2.5.0 的后台管理在最新的 Chrome 里无法展开工具菜单，文章菜单可以正常展开，如图所示：
![sologif](https://img.hacpai.com/file/2018/01/b6923ccf04804a33903cad8490c4628e_solo.gif)

浏览器版本：
![chrome](https://img.hacpai.com/file/2018/01/7f04ef88039540ecb6c18f938153ee5f_image.png)

在 QQ 浏览器里工具菜单可以正常展开：
![soloqgif](https://img.hacpai.com/file/2018/01/16dade17d51c46c3acafd04f354d25bc_soloq.gif)
![imagepng](https://img.hacpai.com/file/2018/01/17a6dd5f84e44ba8b018e845afba6c09_image.png)

**Comment by 88250** [comment]
强制刷新一下试试？

**Comment by iTanken** [comment]
![imagepng](https://img.hacpai.com/file/2018/01/5866ef691c6c4dcbb95fbabf16c06348_image.png)
清空缓存也不行，在 火狐、IE、Edge 里都是正常的，就在我这个 Chrome 里会这样，ul > li 里面都是空的。我用的 Chrome 可能是假的😂

**Comment by Vanessa219** [comment]
@iTanken 我在官网下了最新的 mac Chrome 版本 64.0.3282.119（正式版本） （64 位）。重现不了，看了下代码，找不到移除 li 内容的。。。 要不你换个 chrome 版本？

**Comment by iTanken** [comment]
![imagepng](https://img.hacpai.com/file/2018/01/331d38fa0bdc478ba1fa43720c0c5d20_image.png)

@Vanessa219 嗯嗯，可能就是我浏览器的问题 😂😂😂，我在浏览器快捷方式后面加上 --disable-web-security --user-data-dir="C:\Chrome" 就正常了

**Comment by 88250** [comment]
先关闭这个 issue 了，多谢反馈。

**Comment by iTanken** [comment]
@88250 嗯嗯，不好意思，找到问题了，是我登录的用户角色的问题：
![imagepng](https://img.hacpai.com/file/2018/01/44f520afe38c4c38bd29046918b9fba7_image.png)

😂😂😂 我也是醉了

**Comment by Vanessa219** [comment]
吓到我了
