### ISSUE TITLE
点击注册账号的时候，验证码看不清

### ISSUE THREAD

**Issue by He-Jin** [b3log/solo#12406]
点击注册账号的时候，验证码看不清，看不清写的啥
![image](https://user-images.githubusercontent.com/25659990/37198242-a6263434-23b8-11e8-94b6-06dc81f29b3d.png)

**Comment by 88250** [comment]
麻烦贴个图。

**Comment by wangchencom** [comment]
经过我的鉴定 你这张图是p的

**Comment by He-Jin** [comment]
已解决，字体库的问题，cenos7.4默认没带微软的字体，而源码指定的微软的字体，系统加入微软的字体后解决此问题，以下是正常后的截图

![tim 20180309170402](https://user-images.githubusercontent.com/25659990/37199233-fd7f1072-23bb-11e8-9d19-e98e5519858e.png)
