### ISSUE TITLE
浏览器打开控制台后,底部设置上移。导致样式重叠

### ISSUE THREAD

**Issue by lemon0310** [b3log/solo#12402]
![qq 20180302175519](https://user-images.githubusercontent.com/25683372/36893402-e7651ddc-1e42-11e8-866c-5520f846c51e.png)

**Comment by battlesteed** [comment]
这问题可以忽略吧,一般用户浏览网页谁会去开控制台啊

**Comment by 88250** [comment]
我也觉得.... 先忽略了， @Vanessa219 有空的话稍微修一下。

**Comment by iTanken** [comment]
![autogif](https://img.hacpai.com/file/2018/03/a602419ff24f4a4291a7d3fd54fda905_auto.gif)

可以参考一下这个 🌺 🐔

**Comment by 88250** [comment]
先不管了吧。
![image](https://user-images.githubusercontent.com/873584/37318306-b68435ee-26a4-11e8-9488-6744d4e5a7ec.png)
