### ISSUE TITLE
独立模式启动命令问题

### ISSUE THREAD

**Issue by JiangKunbo** [b3log/solo#12410]
使用 java -cp WEB-INF/lib/*:WEB-INF/classes org.b3log.solo.Starter运行
然后报错：zsh: no matches found: WEB-INF/lib/*:WEB-INF/classes
解决办法： java -cp "WEB-INF/lib/*:WEB-INF/classes" org.b3log.solo.Starter

**Comment by 88250** [comment]
感谢反馈，这个是文档问题，v2.8.0 修正。
