### ISSUE TITLE
后台管理页面层级异常

### ISSUE THREAD

**Issue by zjhch123** [b3log/solo#12419]
稍小一点的屏幕显示效果不是很理想：
![image](https://user-images.githubusercontent.com/12215513/37965259-0b58a9b2-31f7-11e8-94a1-4ea097fd662e.png)
似乎是给#tabs加上`z-index: 999`就可以解决

**Comment by Vanessa219** [comment]
请关注 https://github.com/b3log/solo/issues/12400
