### ISSUE TITLE
配置文件改为80端口后，启动后还是8080

### ISSUE THREAD

**Issue by huangqinquan** [b3log/solo#12416]
netstat -ntlp查看也是运行在8080，但是日志输出是运行在80端口上，结果无法访问

**Comment by 88250** [comment]
latke.props 配置文件中的端口和域名配置不是监听地址配置。如果你用独立模式的话，可以看下 `-h`。

**Comment by huangqinquan** [comment]
了解，加上-lp 80后解决问题，感谢您这么晚的回复！

**Comment by 88250** [comment]
撤了，晚安 😴
