### ISSUE TITLE
登陆失败，一直显示loading 

### ISSUE THREAD

**Issue by hiquanta** [b3log/solo#12422]
我是同一台服务器 用nginx 反向代理80，可以正常访问，登陆页面也正常，但是登陆一直卡在loading，f12 日志 显示
`
XMLHttpRequest cannot load http://hiquanta.com/login. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.hiquanta.com' is therefore not allowed access. The response had HTTP status code 404.
`

**Comment by 88250** [comment]
latke.props 里面配置一下，详见 https://hacpai.com/article/1474087427032

**Comment by hiquanta** [comment]
找到原因了  线上环境一定要使用 PRODUCTION
