### ISSUE TITLE
ToC hit twice

### ISSUE THREAD

**Issue by Joan114** [b3log/solo#12436]
[WARN ]-[2018-04-19 12:05:07]-[org.b3log.solo.plugin.list.ListHandler:60]: ToC hit twice, please report this "ghosty" issue to developer team: https://github.com/b3log/solo/issues/new

**Comment by 88250** [comment]
麻烦提供一下如下信息：

* 运行模式：独立模式 or 容器模式
* 数据库

**Comment by f987002856** [comment]
@88250 你好，我也遇到了这个提示，使用的是源码运行 Starter 类，数据库使用的 MySQL

**Comment by 88250** [comment]
@f987002856 谢谢反馈，这个报错目前不会引起使用问题，代码已经做了补偿处理，只是一直没找到根源。

**Comment by 88250** [comment]
https://github.com/b3log/solo/issues/12511
