### ISSUE TITLE
docker 环境无法通过环境变量选择数据库

### ISSUE THREAD

**Issue by itlad** [b3log/solo#12437]
/src/main/resources/docker/entrypoint.sh文件中：
1.DATEBASE_TYPE 拼写错误  应改为 
2.第9行   cat /otp/b3log/tmp/local.properties.mysql | sed \ 中 otp错误

**Comment by 88250** [comment]
@tomaer

**Comment by tomaer** [comment]
fixed in 2.9.0-dev
