### ISSUE TITLE
跨版本升级？

### ISSUE THREAD

**Issue by AllenCoder** [b3log/solo#12433]
[https://github.com/b3log/solo/issues/12431](https://github.com/b3log/solo/issues/12431)

如果不能跨版本升级？那请问我改怎么做？老版本运行的2.2.0的，难道我要一点点更新发布迭代到2.7.0？请问有什么好的办法？

**Comment by 88250** [comment]
只能逐个版本依次升级 😅

**Comment by ydcun** [comment]
也挺快的

于佃存
中国科学院计算技术研究所

在 2018年4月9日，21:29，Allen <notifications@github.com<mailto:notifications@github.com>> 写道：


#12431<https://github.com/b3log/solo/issues/12431>

如果不能跨版本升级？那请问我改怎么做？老版本运行的2.2.0的，难道我要一点点更新发布迭代到2.7.0？请问有什么好的办法？

**Comment by 88250** [comment]
具体可以参考一下 https://hacpai.com/article/1492881378588?r=88250 升级部分

**Comment by AllenCoder** [comment]
好的，明白了

**Comment by AllenCoder** [comment]
谢谢
