### ISSUE TITLE
主题 ease 动态页面显示问题

### ISSUE THREAD

**Issue by OneMuggle** [b3log/solo#12444]
主题ease动态页面的标签和分类显示高度设定808px，固定死了，显示不和谐
![image](https://user-images.githubusercontent.com/26530847/39851592-5a03cb30-544a-11e8-97dc-8dc12ca5f15c.png)

**Comment by Vanessa219** [comment]
https://github.com/b3log/solo-skins/commit/b0c5e50d9a7fa38519388d365d9b9d0d8974b1ff
