### ISSUE TITLE
浏览文章的页面能加个编辑按钮吗？

### ISSUE THREAD

**Issue by zwxbest** [b3log/solo#12442]
每次想更新内容，都需要先到后台找到文章，如果文章多了还需要一页一页翻。

**Comment by 88250** [comment]
修改文章使用频度不高，在前台搞的话需要加一些判断还有请求入口，会增加模版开发的复杂度，不利于其他人参与开发。

针对修改文章的场景，下个版本会在后台加入搜索功能，这样就方便定位文章了，谢谢反馈！

https://github.com/b3log/solo/issues/12412
