### ISSUE TITLE
请问保存草稿后，点击会显示找不到网页

### ISSUE THREAD

**Issue by QuinnTian** [b3log/solo#12456]
如图已经保存草稿，然后点击 会提示找不到网页
![xr 46 5lsyy 8 ru5i98k9](https://user-images.githubusercontent.com/29975541/40377477-9b2245aa-5e23-11e8-87e8-be0b79841b3c.png)

**Comment by 88250** [comment]
工具 -> 偏好设定 -> 参数设置 -> 允许通过链接访问草稿
