### ISSUE TITLE
iMobile皮肤问题

### ISSUE THREAD

**Issue by QuinnTian** [b3log/solo#12453]
换上这个皮肤后，无法使用评论功能具体报错如下，问了下原作者，原作者说是那个{miniPostfix}这个获取不到值的原因，因为要引用owo.min.js，自己试了试确实获取不到值，但是不知道是为什么。
![image](https://user-images.githubusercontent.com/29975541/40303008-b8a8d284-5d23-11e8-923d-9f550556b767.png)
![image](https://user-images.githubusercontent.com/29975541/40303033-cf4b7ae6-5d23-11e8-9d7d-7ff7445e42f3.png)

**Comment by 88250** [comment]
稍后我们看一下，谢谢反馈。

**Comment by Vanessa219** [comment]
这个开发环境是空，生产环境是 .min

**Comment by QuinnTian** [comment]
@Vanessa219  不太明白

**Comment by 88250** [comment]
你看下 latke.props，里面有个 `runtimeMode`，值配置成 `PRODUCTION` 后就会使用 .min 了。还有些其他具体的配置详见 [Latke 配置剖析](https://hacpai.com/article/1474087427032)。
