### ISSUE TITLE
solo导出sql报错

### ISSUE THREAD

**Issue by QuinnTian** [b3log/solo#12452]
![image](https://user-images.githubusercontent.com/29975541/40301679-645df4ec-5d1f-11e8-8f3d-c02eba796112.png)
![image](https://user-images.githubusercontent.com/29975541/40301704-7e4b16e6-5d1f-11e8-9b4c-e452701b3982.png)
这功能是没有吗？还是bug

**Comment by 88250** [comment]
mysqldump 没有在 $PATH 上。

**Comment by QuinnTian** [comment]
@88250 小白不太懂，是不是因为我的mysql装在另一个服务器的原因？

**Comment by 88250** [comment]
哦，这样的话肯定是不行的，这个是本地调用 `mysqldum` 这个命令。
