### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lesvere** [b3log/solo#12450]
一、Initailize Solo error: 

java.sql.SQLException: Incorrect string value: '\xE5\xBC\x80\xE6\xBA\x90...' for column 'optionValue' at row 1

二、
mvn clean install -DskipTests
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.b3log:solo:war:2.9.0
[WARNING] 'dependencies.dependency.systemPath' for org.patchca:patchca:jar should not point at files within the project directory, ${project.basedir}/src/main/resources/lib/net/pusuo/patchca-0.5.0.jar will be unresolvable by dependent projects @ line 238, column 25
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 

三、
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

**Comment by lesvere** [comment]
H2 库 ok。

**Comment by 88250** [comment]
文档上说明了，请仔细看，用 `utf8mb4` 字符集。

**Comment by lesvere** [comment]
感谢，那么晚了还在坚守。

CREATE DATABASE `blog` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

前面2.4的版本没有进行编码设置，没注意，感谢。已解决！
