### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by QuinnTian** [b3log/solo#12457]
**1.能否在后台管理中添加一个上传文件的功能？**
**2.能否增加在编辑器中增加添加图片的功能
（图片直接上传获得外链然后自动用markdown的语法插入文章中）**
3.还有个问题因为我七牛云还在实名认证所以上传的文件是存在服务器上的，如果连接到七牛云，在文章中上传的文件是否会随着文章的删除而删除到上传到七牛的文件呢？

**Comment by 88250** [comment]
1. 文件管理的功能和七牛云后台有重叠，所以 Solo 后台就不再重复造轮子了
2. 最新版的 Solo 是支持的，你升级试试
3. 删除文章不会删除文件

**Comment by QuinnTian** [comment]
最新版的不是2.9吗？不是只有插入文件吗
我看了看删除文章后本地文件会删除掉 我没链接到七牛云，如果存到本地服务器会删吧？

**Comment by 88250** [comment]
好像是用点小问题，下个版本修复。文件不会删的。

**Comment by QuinnTian** [comment]
那个现在插入图片是不是就是上传文件，然后把链接套上markdown格式来插入图片？为什么不单独添加一个上传图片的功能然后自动转成markdown的插入语法
我试了试如果是存在本地服务器 删除文章的同时会删除本地上传的文件

**Comment by 88250** [comment]
是用的文件上传，图片插入转 markdown 少了个 ! ，会修正的，感谢反馈。
