### ISSUE TITLE
不能发表文章

### ISSUE THREAD

**Issue by jack-smile** [b3log/solo#12455]
创建博客，只有第一篇系统默认创建的文章成功显示，其他自己发表全部失败。评论也不能正常显示！

主页标题可以正常显示。

![1](https://user-images.githubusercontent.com/17373065/40372410-354b5066-5e17-11e8-8774-74cccbff9875.png)
![2](https://user-images.githubusercontent.com/17373065/40372417-3834d7a2-5e17-11e8-9ac2-304b51c4cc3f.png)
![3](https://user-images.githubusercontent.com/17373065/40372422-3b876802-5e17-11e8-906c-3adc0541ebe1.png)
![4](https://user-images.githubusercontent.com/17373065/40372423-3c46d430-5e17-11e8-8c52-096ae6c59ecf.png)
![5](https://user-images.githubusercontent.com/17373065/40372430-3fc1ba76-5e17-11e8-96da-566b75aa05c0.png)

**Comment by 88250** [comment]
看下后台日志报错。

**Comment by jack-smile** [comment]
![6](https://user-images.githubusercontent.com/17373065/40373254-18127f36-5e19-11e8-957f-1bc7c55e8b69.png)

**Comment by jack-smile** [comment]
这个是查看评论时报的错误日志
![7](https://user-images.githubusercontent.com/17373065/40373671-fb2481c0-5e19-11e8-82e7-cc366949f9fc.png)

**Comment by jack-smile** [comment]
我刚才升级到最新版本2.9.0，就正常了。。之前版本是2.8.0.。。很奇怪。。。

**Comment by 88250** [comment]
从 Markdown 处理失败的报错日志来看，应该是因为端口服务问题：启用了**增强的** Markdown 处理但是该端口处理失败。

可以看下文档 [Solo 用户指南](https://hacpai.com/article/149288137858)中“如何获得更好的 Markdown 渲染效果？”部分。
