### ISSUE TITLE
请问这个是什么错

### ISSUE THREAD

**Issue by wzh154710510** [b3log/solo#12468]
[ERROR]-[2018-06-28 10:50:05]-[org.b3log.solo.service.UpgradeService:151]: Attempt to skip more than one version to upgrade. Expected: 2.9.0, Actually: 2.4.0

**Comment by 88250** [comment]
不能跨版本升级，只能一个一个升级。

**Comment by wzh154710510** [comment]
我是刚下的源码启动啊？用最新的源码启动的啊，  以前下过源码的会有这个影响？

**Comment by 88250** [comment]
那删一下数据库吧，数据库文件在 ~/solo_h2/db

**Comment by wzh154710510** [comment]
成功了谢谢
