### ISSUE TITLE
mysql 5.7.22 init error

### ISSUE THREAD

**Issue by lanux** [b3log/solo#12464]
Initailize Solo error: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'option(optionCategory,optionValue,oId) values ('statistic','0','statisticBlogArt' at line 1

**Comment by 88250** [comment]
你自己改过代码么？

**Comment by lanux** [comment]
没改过代码，是不是sql有关键字？
