### ISSUE TITLE
导航管理页面评论无法删除

### ISSUE THREAD

**Issue by iTanken** [b3log/solo#12460]
`后台管理` > `工具` > `导航管理`，允许评论的页面，不管是在`导航管理`还是`评论管理`，评论都无法删除，只有删除页面后评论才跟着一起删除了。

![admingif](https://img.hacpai.com/file/2018/05/fd21bb92600046ecb07cae6c5e16cb1a_admin.gif)

**Comment by iTanken** [comment]
https://hacpai.com/article/1526519602248#1527426372094

**Comment by 88250** [comment]
我这里没能重现。删除后你看下后台是否有报错日志？
