### ISSUE TITLE
编辑器如何切换呢？不想用markdown

### ISSUE THREAD

**Issue by pcwang0205** [b3log/solo#12462]
请问编辑器如何切换呢。不想用markdown
![image](https://user-images.githubusercontent.com/10112141/40698063-d427fb6a-63ff-11e8-9075-5774f22a2b4e.png)
偏好设置中，没找到相关的切换

**Comment by 88250** [comment]
现在只支持 Markdown 编辑器了。

**Comment by pcwang0205** [comment]
@88250

**Comment by pcwang0205** [comment]
@88250 
![image](https://user-images.githubusercontent.com/10112141/40698369-4d93a5de-6401-11e8-8670-d3194fc11da8.png)
看代码都有默认配置。。怎么会去掉了？？？
