### ISSUE TITLE
Solo与黑客派同步现在不能用了吗？

### ISSUE THREAD

**Issue by QuinnTian** [b3log/solo#12461]
为什么我在Solo发的博客不会同步到黑客派，黑客派上的B3都配置上了

**Comment by 88250** [comment]
你的用户名还有博客地址给我一下，我看看日志。

**Comment by 88250** [comment]
https://hacpai.com/article/1527493968520

**Comment by QuinnTian** [comment]
@88250 我试了试 按照那篇文章改了 好像还是同步不了 http://quinntian.xyz/ 用户名 QuinnTian

**Comment by QuinnTian** [comment]
@88250  可以了但是我发现 我的帖子全都同步到我之前那个号上了 用户名tk ，如果不同步我都不知道我曾经注册过这个号，能不能同步到我新号上？

**Comment by 88250** [comment]
你在社区私信我改邮箱吧。
