### ISSUE TITLE
Markdown的问题

### ISSUE THREAD

**Issue by longyg** [b3log/solo#12469]
我使用markdown写一些数学公式，只有部分能正常处理，有些不能正常显示，比如两点的距离公式！请问solo使用的什么markdown编辑器？

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/42198535-0d47d110-7ebb-11e8-9460-2259a134c169.png)

https://hacpai.com/article/1492881378588

**Comment by longyg** [comment]
后台编辑器有些markdown标签在预览时不能正常的显示。但发布后可以正常显示。
我想应该是编辑器与后台markdown引擎之间的差异导致的。

**Comment by 88250** [comment]
你贴一下原文本，我尝试修复下。

**Comment by longyg** [comment]
问题解决了吗？我看已经close了！

**Comment by 88250** [comment]
晚上看下，有进展我会回帖的 :)

**Comment by 88250** [comment]
代码已经合并到 master，如果急需的话就自己编译一下，否则就等 v2.9.2 发布吧。
