### ISSUE TITLE
数学公式渲染问题

### ISSUE THREAD

**Issue by 88250** [b3log/solo#12470]
> 比如下面两个公式，你可以拷贝到编辑器中然后预览，都不会正确显示。发布后，第一个可以正确显示，第二个不行。
> 
> $\sqrt{(x1-x2)^{2} + (y1-y2)}$
> 
> $\sqrt{(x1-x2)^{2} + (y1-y2)^{2}}$
> 
> PS：我用的yilia皮肤。

https://github.com/b3log/solo/issues/12469

Sym 的没问题，但是 Solo 的有。

**Comment by Vanessa219** [comment]
https://github.com/b3log/solo/commit/711bd078dc181efa250c08b4a5bbeb454ff64853

**Comment by longyg** [comment]
什么时候出2.9.2？

**Comment by 88250** [comment]
https://github.com/b3log/solo/milestone/33

**Comment by longyg** [comment]
替换了这4个js文件，还是不起作用，是还有其他的修改吗？

**Comment by 88250** [comment]
你看下提交记录。

**Comment by longyg** [comment]
#12469 提交记录就是4个js文件有修改。

**Comment by longyg** [comment]
大佬，给点提示吧。。。

**Comment by 88250** [comment]
@Vanessa219 帮忙看下，他改了文件没生效。

**Comment by Vanessa219** [comment]
你的问题是编辑器预览不能显示数学公式，皮肤是可以正常显示的么？

强制刷新一下看看

**Comment by longyg** [comment]
编辑器预览和文章都不能正常显示！强制刷新过，也试过其他浏览器，都不行

**Comment by 88250** [comment]
贴下你博客地址我们看下。

**Comment by longyg** [comment]
[www.yglong.com](www.yglong.com)
第一篇文章里有数学公式

**Comment by Vanessa219** [comment]
这个皮肤是第三方的，我已经联系作者进行修改了。

https://hacpai.com/article/1518334834570#comments

**Comment by longyg** [comment]
编辑器浏览时的问题怎么解决呢？

**Comment by longyg** [comment]
还有，我用其他官方的皮肤，也有同样的问题

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/42368172-e9381be2-8138-11e8-8645-b6bd3c0a32bc.png)

你启用 marked 增强就可以得到这个效果了。

**Comment by Vanessa219** [comment]
@longyg 还有哪一个皮肤？我记得我一个一个的查看过了。

**Comment by longyg** [comment]
yilia

**Comment by Vanessa219** [comment]
![image](https://user-images.githubusercontent.com/970828/42368920-e752e404-813a-11e8-929f-3c43119ecb5d.png)
你把你的皮肤换一下。我看看

**Comment by longyg** [comment]
之前测试就是你上面截图的效果。第二个显示不出来。
昨天重新编译master代码打包部署了一次，结果里面没有yilia，只有两个默认的皮肤。
现在我换成Medium了，也有同样的问题。你可以去看看。

**Comment by 88250** [comment]
用 marked 了么？

**Comment by longyg** [comment]
还没用

**Comment by longyg** [comment]
好吧，我晚上回去换。服务器还没装node

**Comment by Vanessa219** [comment]
你可以先试一下只输入 `$\sqrt{(x1-x2)^{2} + (y1-y2)}$` 这个看看能不能渲染

**Comment by longyg** [comment]
这个之前试过的，没问题
