### ISSUE TITLE
调整访客数刷新间隔为 10 分钟

### ISSUE THREAD

**Issue by OneMuggle** [b3log/solo#12477]
![](https://user-images.githubusercontent.com/26530847/43174055-bff03bd2-8fea-11e8-8cb2-7be8c07d474f.png)
不会减少，重启服务器才会恢复

**Comment by 88250** [comment]
刷新访客数默认是 60 分钟，在 cron.xml 中定义的。下个版本调整这个默认时间为 10 分钟。
