### ISSUE TITLE
看板娘插件

### ISSUE THREAD

**Issue by Vanessa219** [b3log/solo#12472]

**Comment by DrayChou** [comment]
你好

请问看板娘有单独开源吗？可以独立博客使用吗？

**Comment by 88250** [comment]
> 你好
> 
> 请问看板娘有单独开源吗？可以独立博客使用吗？
> 
> 谢谢

请参考这个仓库 https://github.com/b3log/kanbanniang

**Comment by DrayChou** [comment]
谢谢
