### ISSUE TITLE
升级遇到的问题

### ISSUE THREAD

**Issue by QuinnTian** [b3log/solo#12475]
本来想把项目重新导入，然后修改下配置重新打包部署的
改好mysql配置后报错
![snipaste_2018-07-11_00-12-34](https://user-images.githubusercontent.com/29975541/42523026-2e7b244c-849f-11e8-8443-b568c20f7a5c.png)

![snipaste_2018-07-11_00-13-36](https://user-images.githubusercontent.com/29975541/42523066-47cf6746-849f-11e8-88b8-21002139c079.png)

还有就是为什么我导入项目 pom文件报错

![snipaste_2018-07-11_00-21-05](https://user-images.githubusercontent.com/29975541/42523489-6dfae7be-84a0-11e8-86de-46615ad5fd29.png)
![snipaste_2018-07-11_00-20-31](https://user-images.githubusercontent.com/29975541/42523517-854677d0-84a0-11e8-90c1-bc4f81bed915.png)
![snipaste_2018-07-11_00-20-44](https://user-images.githubusercontent.com/29975541/42523530-8eefc390-84a0-11e8-91f9-3658cc16c766.png)

**Comment by 88250** [comment]
eclipse maven 插件的这个问题已经存在很多年了，你 google 一下就可以解决；建议换 IDE。

**Comment by QuinnTian** [comment]
运行时报的那个错是什么原因？已经改成MySQL练

**Comment by 88250** [comment]
切换数据库配置不对吧，日志报错是 H2。

**Comment by QuinnTian** [comment]
不可能啊 我把H2的那段注释了 改成了MySQL
