### ISSUE TITLE
登陆登出问题

### ISSUE THREAD

**Issue by huajinghua** [b3log/solo#12483]
在博客页面中的登陆登出按钮，默认链接到 /login?goto=
这个会出错的，
比如我用nginx，
域名：xxx.com，
solo:本机localhost:8080
博客地址xxx.com/blog/xxx，
然后通过ngxin重写规则映射到solo localhost:8080
所以我的博客所有地址都是/blog 路径下的url
而登录按钮那里不知道为什么直接到我根目录下 /login?这样，导致无法登录

**Comment by 88250** [comment]
不用配置 NGINX 重写的，只需要把 latke.props 里面的配置配成访问时候的地址就行了，具体请看 [Latke 配置剖析](https://hacpai.com/article/1474087427032)。
