### ISSUE TITLE
solo2.9.2关于更改用户权限问题

### ISSUE THREAD

**Issue by blueiou** [b3log/solo#12484]
目的：想设立多个管理员
操作：在表user中改了userRole的属性，变成adminRole，即普通用户变成管理员  
问题：发现该用户的权限还是没有变化

注：已确认在数据表中已经更改过来了

**Comment by 88250** [comment]
1. 设计上不支持多个管理员，见谅
2. 千万不要手改数据，不然会有各种不一致的问题出现

**Comment by blueiou** [comment]
好的 了解。原来不支持多管理员啊 0.0 T.T 那...额

**Comment by 88250** [comment]
支持的话更新角色那里会有的。

当初设计的时候我觉得不需要多个管理员，因为一个团队博客毕竟不会有多大的规模，所以一个管理员应该能够完成管理任务了。
