### ISSUE TITLE
初始化之后mysql数据库表注释乱码

### ISSUE THREAD

**Issue by erhu1999** [b3log/solo#12485]
如题：初始化之后数据库表注释乱码，如下图：
![snipaste_2018-08-21_18-41-57](https://user-images.githubusercontent.com/7963197/44397190-072c5200-a572-11e8-9e75-21530b7005ef.png)

补充：建库时是符合要求的，如下图：
![image](https://user-images.githubusercontent.com/7963197/44397221-23c88a00-a572-11e8-9f49-81d0b52b8726.png)

2018-08-21 19:39:30 补充：win10系统，在catalina.bat文件中声明了： JAVA_OPTS="-Dfile.encoding=UTF-8"
同时在tomcat9.0.10的web.xml文件中的DefaultServlet代码段中声明了：
        <init-param>
            <param-name>fileEncoding</param-name>
            <param-value>UTF-8</param-value>
        </init-param>
都不管用，数据库还是乱码。

**Comment by 88250** [comment]
我这里可以的：

![image](https://user-images.githubusercontent.com/873584/44399414-17e0c600-a57a-11e8-8dc0-91f2b626355c.png)

导出试试看是否正常。

**Comment by erhu1999** [comment]
要不你把mysql数据库初始化的Sql文件给我？
我看了一遍代码，应该是Charset.defaultCharset()方法在不同机器上得到的值是不一样的，在你那是好的，可能是因为你那刚好是UTF-8，我这可能刚好是GBK之类的。
![image](https://user-images.githubusercontent.com/7963197/44399524-86be1f00-a57a-11e8-8e90-a2bd39dd901f.png)

**Comment by 88250** [comment]
有可能是 Latke 框架生成 DDL SQL 的时候有问题，稍后我排查一下，感谢。初始化后的 SQL 如下，用户名 test@b3log.org，密码 1。

[solo.zip](https://github.com/b3log/solo/files/2306172/solo.zip)

**Comment by erhu1999** [comment]
谢谢。我又在Linux上测试了一遍，Linux上没有问题。之前在Windows10上不是这里乱码就是那里乱码。

**Comment by 88250** [comment]
已经找到问题了，加载 repository.json 的时候没设置编码。下个版本发布后这个问题应该就解决了，再次感谢 👍
