### ISSUE TITLE
tomcat-9.0.10 发布文章页面，光标乱码。修改/conf/web.xml的default servlet节点后没有效果

### ISSUE THREAD

**Issue by zhaiweihao** [b3log/solo#12480]
java新手，按照文档下载的百度网盘的war包，在tomcat的/conf/web.xml的default servlet节点添加了fileEncoding之后，启动还是光标后一个乱码
![image](https://user-images.githubusercontent.com/17781981/43821757-973d5070-9b1c-11e8-8c88-f5b8bb6292dd.png)
![image](https://user-images.githubusercontent.com/17781981/43821780-a6b1719e-9b1c-11e8-8857-33b7e20bc26a.png)

还有首页刷新时有一段乱码
![image](https://user-images.githubusercontent.com/17781981/43821713-839cf1a6-9b1c-11e8-9820-8e9fac683efc.png)
这个该如何解决？

**Comment by 88250** [comment]
操作系统是？

**Comment by zhaiweihao** [comment]
@88250 操作系统windows

**Comment by zhaiweihao** [comment]
@88250 操作系统win7，tomcat是当前最新版本

**Comment by 88250** [comment]
用容器模式启动看看？

**Comment by zhaiweihao** [comment]
@88250 我是将war包放到tomcat的webapps下，启动时会自动解压创建项目。目录如下
win7
![image](https://user-images.githubusercontent.com/17781981/43878867-f4f61726-9bd3-11e8-9dea-ad2b8e02a28d.png)
centos 7
![image](https://user-images.githubusercontent.com/17781981/43878907-12bef412-9bd4-11e8-86d8-f976171002a6.png)
win7的站点更改fileEncoding后个人主页样式还是有点问题，还有光标后一个乱码
![image](https://user-images.githubusercontent.com/17781981/43879010-78e997d8-9bd4-11e8-8fe9-83fc0714d91a.png)
![image](https://user-images.githubusercontent.com/17781981/43879011-793cf806-9bd4-11e8-9d7e-fc556b9acdd0.png)
centos7用的相同的war包，但是目前看是正常展示的
![image](https://user-images.githubusercontent.com/17781981/43879122-09ab537e-9bd5-11e8-8331-58863ef7a375.png)
![image](https://user-images.githubusercontent.com/17781981/43879087-e1c38d68-9bd4-11e8-879c-0b62ee8040c4.png)

**Comment by 88250** [comment]
我这里没有 Win7 ，不好调试，服务器上正常就先暂时忽略了，感谢反馈！
