### ISSUE TITLE
sitemap.xml访问不到

### ISSUE THREAD

**Issue by QuinnTian** [b3log/solo#12482]
![image](https://user-images.githubusercontent.com/29975541/44185911-de0e5a80-a148-11e8-86ea-afee5fca8f3a.png)
后台报表不存在，之前一直好好的
![image](https://user-images.githubusercontent.com/29975541/44185928-0007dd00-a149-11e8-8959-3274868d6abe.png)

**Comment by 88250** [comment]
`archivaDate` 和 `archiveDate_article` 这两个表名中的 D 要大写，改下表名应该就好了。
