### ISSUE TITLE
签名档处存在xss输入，前台页面执行

### ISSUE THREAD

**Issue by twoHub** [b3log/solo#12491]
后台设置签名档处存在xss，前台浏览网站时会触发xss，能有效返回cookie信息。
【工具】-【偏好设置】-【签名档】
/admin-index.do#tools/preference/signs
version:2.9.3
payload：<script>alert(document.cookie)</script>

过程：
![default](https://user-images.githubusercontent.com/33438164/44711443-fc793c00-aae0-11e8-9ebc-f5a55e55e3cb.png)
在签名档1输入payload
![default](https://user-images.githubusercontent.com/33438164/44711508-1b77ce00-aae1-11e8-9686-66e8b2865967.png)
在编写文章时选择签名档1保存。
![default](https://user-images.githubusercontent.com/33438164/44711554-35b1ac00-aae1-11e8-975e-00eac8760449.png)
在前台执行payload，显示当前cookie信息。
![default](https://user-images.githubusercontent.com/33438164/44711744-a658c880-aae1-11e8-9b30-1976c5dac8f8.png)

**Comment by 88250** [comment]
后台可以写脚本的，包括公告、文章里面都可以写，方便博主完成一些功能。
