### ISSUE TITLE
支持阿里云 OSS

### ISSUE THREAD

**Issue by linkerlin** [b3log/solo#12497]
七牛云测试域名只有三十天有效，可以支持阿里云oss么？

**Comment by 88250** [comment]
还是绑定域名使用吧，后面阿里云也有可能这样做。

阿里云 OSS 作为长期计划特性，以社区投票为准，如果超过 50 赞就开工。

**Comment by linkerlin** [comment]
我的域名没有备案

**Comment by iTanken** [comment]
阿里云 OSS 默认域名免费支持 HTTPS，七牛云只能自己配置 HTTPS，而且收费。

**Comment by SmileHui** [comment]
帮点，我放本地了。

**Comment by ChristChen128** [comment]
希望支持阿里云OSS

**Comment by superliuliuliu** [comment]
阿里云

**Comment by wxlost** [comment]
需要腾讯COS上传

**Comment by snowfigure** [comment]
希望支持阿里云OSS

**Comment by shangjing105** [comment]
支持阿里云OSS

**Comment by 88250** [comment]
感谢 @hzchendou 提交的 PR，如果不出意外，我们会在 v2.9.8 中合并他的提交。 https://github.com/b3log/solo/pull/12588

**Comment by 18156119872** [comment]
期待阿里云OSS
