### ISSUE TITLE
是否可以考虑开发印象笔记的API呢

### ISSUE THREAD

**Issue by fank243** [b3log/solo#12496]
**Is your feature request related to a problem? Please describe. 你在什么场景下需要该功能？**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] 请尽量清晰精准地描述你碰到的问题。
希望能够考虑接入印象笔记API,文章可以直接存入印象笔记中。

**Describe the solution you'd like 描述可能的解决方案**
A clear and concise description of what you want to happen. 请尽量清晰精准地描述你期待我们要做的，描述你想到的实现方案。

**Describe alternatives you've considered 描述你认为的候选方案**
A clear and concise description of any alternative solutions or features you've considered. 请尽量清晰精准地描述你能接受的候选解决方案。

**Additional context 其他信息**
Add any other context or screenshots about the feature request here. 请提供关于该功能建议的其他附加信息。

**Comment by 88250** [comment]
没有进一步讨论和反馈，暂时关闭。
