### ISSUE TITLE
初始化不了

### ISSUE THREAD

**Issue by Seymour1996** [b3log/solo#12502]
![wx20180910-175913](https://user-images.githubusercontent.com/32315036/45291308-6273b380-b524-11e8-8eec-ef4ef816c988.png)

Initailize Solo error: org.h2.jdbc.JdbcSQLException: NULL not allowed for column "OPTIONVALUE"; SQL statement: insert into b3_solo_option(optionCategory,oId) values (?,?) [23502-190]

初始化的时候显示这个错误

**Comment by 88250** [comment]
解决方案请贴一下，为其他人碰到这个问题的人提个醒 ❤️

**Comment by Seymour1996** [comment]
解决方案:
Solo 使用了 Git 子模块 来组织项目，所以在克隆时需要带上递归子模块参数 --recurse-submodules：
git clone --recurse-submodules https://github.com/b3log/solo.git
