### ISSUE TITLE
最新版本的solo，MySQL 8.0.12 遇到一条奇怪的日志!

### ISSUE THREAD

**Issue by linkerlin** [b3log/solo#12511]
[INFO ]-[2018-09-15 23:18:06]-[org.b3log.latke.repository.jdbc.util.JdbcUtil:150]: Executing SQL [ select  *  from b3_solo_archiveDate order by archiveTime desc limit 0,2147483647]
[INFO ]-[2018-09-15 23:18:06]-[org.b3log.latke.repository.jdbc.util.JdbcUtil:150]: Executing SQL [ select  *  from b3_solo_category order by categoryOrder asc limit 0,2147483647]
[WARN ]-[2018-09-15 23:18:06]-[org.b3log.solo.plugin.list.ListHandler:62]: ToC hit twice, please report this "ghosty" issue to developer team: https://github.com/b3log/solo/issues/new
[TRACE]-[2018-09-15 23:18:06]-[org.b3log.latke.repository.jdbc.util.Connections:183]: Connection pool [leasedConns=[]]
[INFO ]-[2018-09-15 23:18:06]-[org.b3log.latke.repository.jdbc.util.JdbcUtil:150]: Executing SQL [select count(oId) from b3_solo_article]

**Comment by linkerlin** [comment]
[WARN ]-[2018-09-15 23:18:06]-[org.b3log.solo.plugin.list.ListHandler:62]: ToC hit twice, please report this "ghosty" issue to developer team: https://github.com/b3log/solo/issues/new

**Comment by linkerlin** [comment]
本机运行的时候，遇到的。
操作是发布了一篇Blog。

**Comment by 88250** [comment]
暂时忽略， https://github.com/b3log/solo/issues/12436
