### ISSUE TITLE
md编辑的字体大小过小，怎么调整？

### ISSUE THREAD

**Issue by Arisono** [b3log/solo#12526]
详情请看地址：http://120.78.201.50/articles/2018/09/22/1537629812495.html

**问题现象**：默认编辑出来的字体大小过小。
求解决方法
![imagepng](https://img.hacpai.com/file/2018/09/36f3ac4620664ab6965eef8e4838ce54_image.png)

> 论坛的md编辑器挺好用的，默认字体大小合适，请问solo可以接入这款md编辑器吗？

![imagepng](https://img.hacpai.com/file/2018/09/a9774854c57545c7b2ec741fba5b5f22_image.png)

**Comment by Vanessa219** [comment]
![image](https://user-images.githubusercontent.com/970828/45996022-2d8f6100-c0cd-11e8-8581-49eb19dfb1c0.png)
被自定义样式覆盖，请自行修改。

**Comment by Arisono** [comment]
万分感谢，非常谢谢，我已经解决了问题。好人一生平安！！！
