### ISSUE TITLE
支持配置自定义模板变量

### ISSUE THREAD

**Issue by iTanken** [b3log/solo#12535]
![options](https://img.hacpai.com/file/2018/10/537be50151d84b9f87195079f71fc215_TIM20181008113305.png)

* 希望可以在此处添加一个自定义参数配置项，多个自定义参数以类似 ` key0=val0|key1=val1|key2=val2 ` 的方式保存到表中的一个字段里，用于处理皮肤或其他地方的个性化配置
* 在皮肤中可以使用类似 ` ${customVars.key0} ` 的方式获取自定义参数

**Comment by 88250** [comment]
这个机制确实有用，可以让扩展性变得很好，感谢提议。
