### ISSUE TITLE
可以从wordpress把之前的文章迁移过来吗?怎么操作

### ISSUE THREAD

**Issue by gm100861** [b3log/solo#12539]
### 已有博客的文章,怎么迁移过来
现有的博客是wordpress, 已经写了有5年了,一直想换一个java实现的博客
不知道作者是否有这方面的打算或者已经有了相关迁移方案.

**Comment by 88250** [comment]
找个 WordPress 导出 Markdown 的插件，然后通过[这个方式](https://hacpai.com/article/1498490209748)导入 MD 文件。
