### ISSUE TITLE
增加是否启用数学公式渲染配置开关

### ISSUE THREAD

**Issue by TsLenMo** [b3log/solo#12540]
### 在文章显示是否开启全局内联公式

markdown  的内联公式能够加个开关吗？

你看   下面字体是不是很怪异？
JAVA\_HOME=/dir(解压的目录)/(jdk目录)  
JRE\_HOME=$JAVA\_HOME/jre  
PATH=$PATH:$JAVA\_HOME/bin:$JRE\_HOME/bin  
CLASSPATH=:$JAVA\_HOME/lib/dt.jar:
$JAVA\_HOME/lib/tools.jar:$JRE\_HOME/lib  
export JAVA\_HOME JRE\_HOME PATH CLASSPATH

正常代码应该要显示成下面一样的...
```properties
#jdk settings 
JAVA_HOME=/dir(解压的目录)/(jdk目录)
JRE_HOME=$JAVA_HOME/jre 
PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin
CLASSPATH=:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JRE_HOME/lib 
export JAVA_HOME JRE_HOME PATH CLASSPATH
```

**Comment by 88250** [comment]
@Vanessa219 你觉得是否有必要呢？

**Comment by Vanessa219** [comment]
以上本属于代码片段。使用的时候放入代码块中即可
\`\`\`...\`\`\`
