### ISSUE TITLE
关于两个域名指向到solo博客 导致的资源跨域无法引用

### ISSUE THREAD

**Issue by pencilso** [b3log/solo#12541]
如题  我使用了www..xx.com 和 xx.com 解析到了同一个solo博客
但是solo里面只能配置一个域名 比如说我配置了xx.com
在访问xx.com的时候是正常的  但是访问www.xx.com的时候  就会有些图标无法展示
F12查看的时候  发现出现了跨域问题  因为它引用了xx.com的资源

**Comment by pencilso** [comment]
然后我发现  nijigen这个皮肤  在出现跨域后  反而更好看了 
出现跨域后  列表变大了  有一种填充整个界面的感觉  没有以前那么空荡荡

D大可以看看  感受感受

#会出现跨域
www.pencilso.cn
#正常展示
pencilso.cn

**Comment by 88250** [comment]
NGINX 上做重定向，两个域名不利于 SEO。
