### ISSUE TITLE
禁止直接获取 robots.txt

### ISSUE THREAD

**Issue by TsLenMo** [b3log/solo#12543]
robots.txt 文件能够正常访问到可能会泄露一些服务器配置信息

**Comment by 88250** [comment]
爬虫协议和服务器配置应该没有啥关系吧？请具体举个例子说明。

**Comment by TsLenMo** [comment]
我这个目的是禁止用户直接拉取rebots.txt这个文件
因为reboot.txt文件中可能存在了一些系统中的敏感信息
如后台地址或者不愿意对外公开的地址等，攻击者有可能利用这些信息实施进一步的攻击
虽然可能非正常获取 但是有一步比没有也要好是不是
http://fanxser.oicp.io/robots.txt
我的博客就做了处理
https://88250.b3log.org/robots.txt
你的就没做

**Comment by 88250** [comment]
你那个实现有问题，我做了些调整 https://github.com/b3log/solo/commit/debb65dff22974dc5c5e35e7341f4a9f25508942

**Comment by TsLenMo** [comment]
OK,没有仔细看看您的规范我就直接提交了
不好意思！

**Comment by TsLenMo** [comment]
> 你的实现有点问题，我做了些调整 [debb65d](https://github.com/b3log/solo/commit/debb65dff22974dc5c5e35e7341f4a9f25508942)

OK,没有仔细看看您的规范我就直接提交了
不好意思！

**Comment by 88250** [comment]
这个次要，主要是有 bug，requestURI 判断那里。你那边最好也改一下，不然搜索引擎获取不到。

感谢 PR 💓

**Comment by TsLenMo** [comment]
> 这个次要，主要是有 bug，requestURI 判断那里。你那边最好也改一下，不然搜索引擎获取不到。
> 
> 感谢 PR 💓

我用工具获取过   是可以获取到的.


![9vwi4 _6cmdg pq06 jtyy6](https://user-images.githubusercontent.com/23328499/46912809-66c33e80-cfb2-11e8-8afe-6e9f1831ea34.png)
