### ISSUE TITLE
社区推荐为什么要推荐两年前的帖子？

### ISSUE THREAD

**Issue by zwxbest** [b3log/solo#12557]
### 你在什么场景下需要该功能？
后台首页->社区推荐

看到两年前的无意义以及过时的帖子。

* 又双叒叕一款 Chrome 新标签页插件 -「Start here」  10/22/17 18:59:19
*  8-15 english code  8/15/17 19:59:51
*  上班一个月多了 公司要搬家了 这个不能怪我了吧  6/8/17 9:41:30
*  欢迎大家踊跃发言  12/1/15 21:30:5
*  wsgiref 源码阅读  10/20/18 17:20:44
*  linkedList 实现的 stack  10/20/18 16:9:23
*  排名前十的长租公寓爆仓了，房东租客损失惨重  10/20/18 14:9:17
### 描述可能的解决方案
希望推荐活跃以及近期的帖子。

**Comment by 88250** [comment]
这个推荐是根据最多使用标签进行匹配的。稍后我调整一下社区接口，混入一些较新文章，感谢反馈！
