### ISSUE TITLE
内置 HTTPS+CDN 文件存储

### ISSUE THREAD

**Issue by 88250** [b3log/solo#12556]
由 B3log 开源组织提供一个免费图床（HTTPS + CND），只要在社区中配置验证 B3 Key 后就可以在 Solo 中直接使用。

**Comment by iTanken** [comment]
我还是觉得支持阿里云更好一些

**Comment by linkerlin** [comment]
当务之急是做大b3log的流量，大部分solo站流量很小，不会对b3log带来什么流量压力。

**Comment by xinzhongtianxia** [comment]
支持支持，对初期用户来说，内置图床省去了很多繁琐的申请啊配置啊 等等，正式这些各种云（七牛啊，阿里啊，腾讯啊）把大多数有兴趣开始但是又嫌麻烦的同学们直接赶走了
建议先搞内置的

**Comment by iTanken** [comment]
> 计划 v3.0.0 正式内置云端文件存储，这样大家就不用自己折腾了。当然，要配置自己的七牛云或者阿里云 OSS 也是可以的。

如果后台有个单独的资源管理功能，支持管理本博客上传的所有文件，那是最好不过的

**Comment by 88250** [comment]
@iTanken 嗯，文件管理这个功能是有些必要的（包括文件导出），但是 v3.0.0 估计是做不完，放到后面的版本中实现。

**Comment by 88250** [comment]
* 统一使用社区的文件上传，移除本地、七牛云、阿里云 OSS 上传支持
* 社区会在后续上线文件管理，方便用户管理上传的文件

为实现 [B3log 构思](https://hacpai.com/article/1546941897596) 更进一步。
