### ISSUE TITLE
角色管理问题

### ISSUE THREAD

**Issue by calonmo** [b3log/solo#12562]
### 你在什么场景下需要该功能？

请尽量清晰精准地描述你碰到的问题。
在用户注册新账号进入后台管理时，竟然可以看到管理员(或者别人的文章)，但是又不能变更，文章列表一多的话就找不到哪些是自己的，不符合正常人的逻辑。

### 描述可能的解决方案

1、希望在后台只能看到自己的内容，并且可以编辑自己的内容。而不是全部都列出来。混淆视听。
2、后台的工具也同样，其实这个用户是什么定位？是管理员还是普通用户？普通用户就只应该设置个人的相关设置而不是全局的。

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by 88250** [comment]
Solo 的多人博客支持定位是团队博客，不是通常意义上的博客平台，一个团队共用一个后台，但是文章是分开编辑权限的。
