### ISSUE TITLE
在debian上部署到tomcat容器报错404

### ISSUE THREAD

**Issue by jwister** [b3log/solo#12567]
在debian上部署到tomcat容器整个站点报错404找不到

不知道有没有人在debian上测试过。我测试了几个环境 linux 和  windows 都是正常的

唯独部署到debian上面站点404  容器下面的其它站点都是好的。

**Comment by jwister** [comment]
已解决。
       解决办法  debiantomcat换成了9.0    
      但是之前windows  和linux 是用的tomcat8和7 ， 都没问题。

**Comment by 88250** [comment]
部署需要使用 Tomcat/Jetty 9+。
