### ISSUE TITLE
加载文章页时，日志记录500错误

### ISSUE THREAD

**Issue by snowfigure** [b3log/solo#12565]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[讨论区](https://hacpai.com/tag/solo)搜寻资料解决问题。

----

### 加载文章页时，日志记录500错误

版本号：Solo 2.9.5

![image](https://user-images.githubusercontent.com/4285621/47891941-49d2aa80-de90-11e8-8ae5-cb0ebba2a69a.png)

### 原因

> 新增文章时，`getPermalinkForAddArticle`中对于文章链接使用的是`articles`，所以数据库记录中文章名为`articles`

![image](https://user-images.githubusercontent.com/4285621/47891993-830b1a80-de90-11e8-94f9-cf6171d6c65a.png)

![image](https://user-images.githubusercontent.com/4285621/47892055-bc438a80-de90-11e8-866d-56c6a067ed55.png)

> 函数 `dispatchToArticleOrPageProcessor`处理时，判定文章使用的`article`路径，而不是`articles`路径。

![image](https://user-images.githubusercontent.com/4285621/47892103-f44acd80-de90-11e8-9d82-65fb93fe5746.png)

### 期待的结果

请验证是否有问题。

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
逻辑实现应该没问题。报错是由于框架升级过，你重新获取一下最新的 master 代码就好了。

**Comment by snowfigure** [comment]
> 应该没问题。报错是由于框架升级过，你重新获取一下最新的 ma

我走读代码发现确实没啥问题，确实是lakte框架升级导致。已测试OK。
