### ISSUE TITLE
cookie xss 

### ISSUE THREAD

**Issue by TsLenMo** [b3log/solo#12560]

**Comment by 88250** [comment]
请具体说一下问题，谢谢。

**Comment by TsLenMo** [comment]
> 请具体说一下问题，谢谢。

就是说   cookie  可以直接被客户端脚本获取   

就是   cookie的值可以由 客户端脚本中 document.cookie  获取。
因为 响应头 set-cookie 中连个简单的   httponly 参数都没有。
set-cookie  中增加 httponly 可以适当增加 cookie 的安全性。

**Comment by 88250** [comment]
嗯，这个我明白，感谢反馈。

**Comment by 88250** [comment]
已经转账。
