### ISSUE TITLE
服务器迁移导致登陆404

### ISSUE THREAD

**Issue by Dandjinh** [b3log/solo#12571]
----

### 描述问题

更换服务器，用的是h2数据库，把数据库和整个solo文件打包传到新服务器上面，把latke文件里的ip改成新服务器的ip，启动solo，历史文章能正常查看。
问题是，登陆的时候，会先发一个OPTION到旧的服务器ip，理所当然的返回404，然后就死在这里了。
这个ip难道不是在latke里面改吗？

### 其他信息

solo 2.9.5

**Comment by 88250** [comment]
OPTION 请求？你清空浏览器缓存看看。

**Comment by Dandjinh** [comment]
除了一张header图片外，所有资源都是从以前的服务器ip获取的，奇怪了

**Comment by Dandjinh** [comment]
解决了，因为我是用命令行启动solo的，所以latke文件里的serverHost不起作用！

**Comment by 88250** [comment]
命令行启动的话除非加了参数，否则默认也是用 latke.props 配置文件。
