### ISSUE TITLE
添加 email from 选项而不是直接使用 admin email

### ISSUE THREAD

**Issue by brentybh** [b3log/solo#12574]
### 你在什么场景下需要该功能？

admin email 通常是私人邮箱，如果使用 mailgun, sendgrid 等 email 服务，由于域名不匹配，通常会被直接扔进垃圾箱。

### 描述可能的解决方案

支持在 mail.props 中设定 mail from 选项，使用设定的地址发送邮件。

### 描述你认为的候选方案

无

### 其他信息

无

**Comment by 88250** [comment]
这样改进你看如何：在 mail.props 中增加 mail.from 设置项，用于设置发送邮箱。默认为空，使用管理员邮件地址。

其他地方不做任何调整，你看是否能够满足。
