### ISSUE TITLE
一段时间后自动关闭服务

### ISSUE THREAD

**Issue by JZLeung** [b3log/solo#12586]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[讨论区](https://hacpai.com/tag/solo)搜寻资料解决问题。

----

### 描述问题

>请尽量清晰精准地描述你碰到的问题。

服务器使用脚本启动，过了一段时间后（大概一周），就会自动关闭了。

### 重现步骤

请描述如何重现这个问题：

run script: 
```bash
nohup java -cp WEB-INF/lib/*:WEB-INF/classes org.b3log.solo.Starter >/home/website/soloblog/log.txt 2>/home/website/soloblog/error.log &
```

### 期待的结果

>请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

>如果可能，请尽量附加截图或录像来描述你遇到的问题。

log.txt 中只有启动的日志， error.txt 为空。不知道有没有自带的日志？

![image](https://user-images.githubusercontent.com/7995232/49638371-f03b3e00-fa42-11e8-9a0d-cf3acd89d03e.png)

### 桌面端环境

- OS: [e.g. windows, mac, linux] ubuntu server 16.04
- Browser [e.g. chrome, safari] none
- Version [e.g. 22] none

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
我这边没有发现这个问题，你可以配置一下 log4j 把日志写到文件里看看。另外，注意 JVM 奔溃日志，还有操作系统的系统日志，我估计有可能是内存不足引起的。

**Comment by JZLeung** [comment]
@88250 请问下哪里配置 日志文件输出？

**Comment by JZLeung** [comment]
@88250 
抱歉，没用过 java，不知道该 crash 的日志放在哪里？或者在哪里设置该日志的路径？
