### ISSUE TITLE
docker 部署solo 初始化异常

### ISSUE THREAD

**Issue by TobyLi0110** [b3log/solo#12589]
HTTP Status 404 – Not Found

HTTP Status 404 – Not Found
Type Status Report

Message Not found

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/9.0.13

 http://ip:8080/ 这个 url 404 了 是不是要改哪个配置 
serverHost这个已改成服务器对应 ip

**Comment by 88250** [comment]
文档里面有 docker 环境变量，你试着配置一下看看。 https://hacpai.com/article/1492881378588

**Comment by TobyLi0110** [comment]
> 文档里面有 docker 环境变量，你试着配置一下看看。 https://hacpai.com/article/1492881378588

用的是H2做存储，配了以后还是一样，并且看了默认值应该是符合的

**Comment by TobyLi0110** [comment]
> 文档里面有 docker 环境变量，你试着配置一下看看。 https://hacpai.com/article/1492881378588

![image](https://user-images.githubusercontent.com/24750823/49699638-83749f00-fc0e-11e8-8d82-ece913d1eadc.png)
直接弹出这个页面 f12看了是404

**Comment by 88250** [comment]
你先用原生方式部署，熟悉一下配置，然后再试试 docker 部署。

**Comment by TobyLi0110** [comment]
> 你先用原生方式部署，熟悉一下配置，然后再试试 docker 部署。

看介绍上是说会集成h2数据库，docker里还需要单独装h2吗

**Comment by TobyLi0110** [comment]
> 你先用原生方式部署，熟悉一下配置，然后再试试 docker 部署。

[org.b3log.latke.repository.jdbc.JdbcRepository:419]: Get failed
org.h2.jdbc.JdbcSQLException: Table "B3_SOLO_OPTION" not found; SQL statement:
SELECT * FROM b3_solo_option WHERE oId = ? [42102-197]

好像是有报异常 但是到h2的目录下看 这张表是已经生成了

**Comment by 88250** [comment]
你说一下完整的重现步骤吧。

**Comment by TobyLi0110** [comment]
> 你说一下完整的重现步骤吧。

最新的代码打成war包，然后根据Dockerfile放到Tomcat里面去执行，正常启动，首页注册新账户，注册成功点击“初始化的时候” 直接就404，然后看后台日志就报了这个异常

**Comment by TobyLi0110** [comment]
> > 你说一下完整的重现步骤吧。
> 
> 最新的代码打成war包，然后根据Dockerfile放到Tomcat里面去执行，正常启动，首页注册新账户，注册成功点击“初始化的时候” 直接就404，然后看后台日志就报了这个异常



> 你说一下完整的重现步骤吧。

可以加您微信请教吗

**Comment by 88250** [comment]
我不用微信的，有问题 issue 上交流吧。你先按我说的用原生方式部署。

**Comment by TobyLi0110** [comment]
> 我不用微信的，有问题 issue 上交流吧。你先按我说的用原生方式部署。

还发现个问题不知道是不是这个原因，看了h2目录下的文件 创建表的时候都带来前缀PUBLIC.B3_SOLO_OPTION，但是查询异常的时候 只有B3_SOLO_OPTION，是这个原因吗
