### ISSUE TITLE
运行环境

### ISSUE THREAD

**Issue by ldlqdsdcn** [b3log/solo#12592]
你好，请问咱们项目可以运行在tomcat容器里吗？

**Comment by 88250** [comment]
可以的。

**Comment by ldlqdsdcn** [comment]
war 包直接放到tomcat容易就行吗？
我在idea环境里 貌似启动不起来。
总卡在这一步
 Can't load the default skins, please make sure skin [Jane] is under skins directory and structure correctly

**Comment by 88250** [comment]
拉代码的时候注意要 clone 子模块，https://hacpai.com/article/1493822943172

**Comment by henrywendy** [comment]
![image](https://user-images.githubusercontent.com/5654178/61785609-a6229380-ae3e-11e9-9df0-36ce4e3add10.png)

![image](https://user-images.githubusercontent.com/5654178/61785634-b3d81900-ae3e-11e9-9e99-8f1ebfe30dc6.png)

solo docker  挂载本地的皮肤目录 报错，从日志来看 没有找到 皮肤目录，这个问题 是什么原因呢。

**Comment by 88250** [comment]
> ![image](https://user-images.githubusercontent.com/5654178/61785609-a6229380-ae3e-11e9-9df0-36ce4e3add10.png)
> 
> ![image](https://user-images.githubusercontent.com/5654178/61785634-b3d81900-ae3e-11e9-9e99-8f1ebfe30dc6.png)
> 
> solo docker 挂载本地的皮肤目录 报错，从日志来看 没有找到 皮肤目录，这个问题 是什么原因呢。

https://hacpai.com/article/1559107767487/comment/1563964047020?r=88250
