### ISSUE TITLE
能否加入到hub.docker.com

### ISSUE THREAD

**Issue by wjx0912** [b3log/solo#12603]
作者维护，而不是每个人在hub.docker维护一个，貌似现在的dockerfile自动编译error。谢谢

**Comment by wjx0912** [comment]
surefire test的问题：

https://github.com/b3log/solo/blob/master/pom.xml

把maven-surefire-plugin的skipTests改为true就好了，hub.docker和我本地都得这么改才能build成功。

**Comment by 88250** [comment]
@tomaer 更新一下 Dockerfile？跳过单元测试看看。

**Comment by 88250** [comment]
Docker Hub 镜像已经修复。
