### ISSUE TITLE
发布文章提示成功，点击文章404

### ISSUE THREAD

**Issue by tianyunperfect** [b3log/solo#12605]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[讨论区](https://hacpai.com/tag/solo)搜寻资料解决问题。

----

### 描述问题

我第一次布置系统，初始化正常，发布文章提示成功，主页也能看到发布的文章概要，但是点击刚发布的文章时，会报404，监视后台也没有报错。
jdk1.8，linux文件夹权限也是全部打开的。已经折腾了好几个小时了，请问我应该怎么办？

### 重现步骤

请描述如何重现这个问题：

2. Click on '...'
3. Scroll down to '...'

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

![image](https://user-images.githubusercontent.com/23491291/50417804-40980580-0863-11e9-9b45-4c2b096c79b0.png)

### 桌面端环境

- OS: [e.g. windows, mac, linux]

### 移动端环境

- Device: [e.g. iPhone8]
- OS: [e.g. iOS12]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
你用的是哪个版本？哪个皮肤？

**Comment by 88250** [comment]
我感觉可能是 NGINX 反代配置有问题。

**Comment by 88250** [comment]
请仔细看下这个帖子 https://hacpai.com/article/1474087427032 如果还有问题我们继续讨论。

**Comment by tianyunperfect** [comment]
> 请仔细看下这个帖子 https://hacpai.com/article/1474087427032 如果还有问题我们继续讨论。

您好，帖子我已经看了两遍了，我的操作没有找到问题，现在问题是：我的发布的文章在linux系统中找不到，文章地址是：solo/articles/2018/12/25/1545732144539.html，但是我在系统里面连刚才的目录都找不到……

**Comment by tianyunperfect** [comment]
谢谢你，确实是我的nginx反向代理的错，我把html文件给当做静态文件拦截了，没有经过tomcat。
