### ISSUE TITLE
nginx端口路由产生的bug？

### ISSUE THREAD

**Issue by wjx0912** [b3log/solo#12607]
**安装：**

> docker  run  -d  -p  58080:8080  --name  b3log  -v  /solo_datas:/opt/b3log/backup/  b3log:v2.9.7

**配置solo参数文件：latke.properties：**

> serverHost=www.weiqiba.com/blog
> serverPort=80

**nginx配置：**
```
server {
    listen       80;
    server_name  www.weiqiba.com;

    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location /blog/ {
        proxy_pass http://www.weiqiba.com:58080/;
    }
   ......
}
```

**问题：**
访问首页正常：http://www.weiqiba.com/blog/
但登录链接有问题：http://www.weiqiba.com/login?goto=..........
正常的链接应该是：http://www.weiqiba.com/blog/login吧？ 感觉是nginx配置了proxy_pass后，路径不正常。
请开发者确认下。谢谢

**Comment by 88250** [comment]
感谢反馈。

@Vanessa219 看上去可能是 Jane 这款皮肤的登录链接没有带上下文。

**Comment by 88250** [comment]
不好意思，不是我怀疑的问题。你需要在 latke.props 中加入 `contextPath=/blog` 就可以了，具体细节请参考 https://hacpai.com/article/1474087427032

**Comment by 88250** [comment]
`serverHost=www.weiqiba.com`
