### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by wgngoo** [b3log/solo#12612]
### 描述问题
服务启动时报错
02-Jan-2019 15:24:07.618 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained s logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improime.
[WARN ]-[2019-01-02 15:24:07]-[org.b3log.latke.Latkes:611]: !!!!Runtime mode is [DEVELOPMENT], please make sure configured it with [PROyed on production environment!!!!
[ERROR]-[2019-01-02 15:24:08]-[org.b3log.latke.Latkes:836]: Read skin [Jane]'s  configuration failed: null
[ERROR]-[2019-01-02 15:24:08]-[org.b3log.solo.SoloServletListener:302]: Can't load the default skins, please make sure skin [Jane] is urrectly

### 移动端环境

- tomcat: apache-tomcat-9.0.6
- jdk:1.8.0_144
- solo: latest

**Comment by 88250** [comment]
你好，clone 项目需要带子模块，具体请参考 https://hacpai.com/article/1493822943172
