### ISSUE TITLE
单Tomcat 部署多Solo问题

### ISSUE THREAD

**Issue by pencilso** [b3log/solo#12617]
目前我的solo部署了多个   但是 是部署在同一个tomcat下 如下
![qq 20190107112618](https://user-images.githubusercontent.com/16483654/50747512-361c3980-126f-11e9-980e-fa5d2a419dbb.jpg)

nginx配置如下:

       proxy_pass http://127.0.0.1:8080/pencilso;

       proxy_pass http://127.0.0.1:8080/xiaoxia; 

然后遇到的问题在于  访问资源的时候  自动在域名后面加了项目名  如下
       https://pencilso.cn/pencilso/skins/yilia/css/yilia.min.css?1546831379499

**Comment by pencilso** [comment]
看了一下代码  貌似是这里
'''

    String webappDirLocation = "src/main/webapp/"; // POM structure in dev env
        final File file = new File(webappDirLocation);
        if (!file.exists()) {
            webappDirLocation = "."; // production environment
        }

        final int port = Integer.valueOf(portArg);
        final Server server = new Server(port);
        final WebAppContext root = new WebAppContext();
        root.setParentLoaderPriority(true); // Use parent class loader
        root.setContextPath("/");
        root.setDescriptor(webappDirLocation + "/WEB-INF/web.xml");
        root.setResourceBase(webappDirLocation);
        server.setHandler(root);

'''

**Comment by pencilso** [comment]
emm....   尝试在本地下载下代码进行调试这个事情   但是没找到相关的代码

**Comment by 88250** [comment]
Jetty 的话可以通过配置虚拟目录解决，Tomcat 也类似，你网络上搜索一下“Tomcat 虚拟目录”
