### ISSUE TITLE
社区同步幂等处理

### ISSUE THREAD

**Issue by lizhongyue248** [b3log/solo#12629]
### 你在什么场景下需要该功能？

已经发布了的文章，忘记勾选同步到社区或者希望以后同步到社区（比如待文章所有功能完善后再一起发布到社区，而未完善的时候只能在博客上面看）。

### 描述可能的解决方案

未同步到社区且已在博客中发布的文章，可以在更新时添加一个同步到社区选项，而已同步到社区的文章则不存在此选项。

**Comment by 88250** [comment]
感谢提议！

其实这个选项应该一直存在（即使是已经同步过，更新文章时只要勾选就表示需要同步更新社区这边的帖子），这样的话即使第一次发布漏选同步，后面也可以再更新时进行同步补偿，保持同步操作的幂等。

涉及的细节比较多，我们会尽量实现**更新时可开启同步**这个选项。

**Comment by 88250** [comment]
在文章列表上增加了一个推送到社区的按钮，随时可点。

![image](https://user-images.githubusercontent.com/873584/52531242-294aa400-2d4d-11e9-8fda-221f8664e141.png)
