### ISSUE TITLE
文章 PDF 导出

### ISSUE THREAD

**Issue by skyking116** [b3log/solo#12636]
### 你在什么场景下需要该功能？

发布完成的博文，当需要将博文内容以文档的形式进行传播时

### 描述可能的解决方案

后台管理>文章管理>更新>多一个导出为PDF的按钮
![image](https://user-images.githubusercontent.com/26771976/52172101-a2715680-27a3-11e9-90f1-31c26cbd2ecb.png)

### 描述你认为的候选方案

尽可能的一个按钮解决，当然也可以通过预览的形式，让有需要的博主自行另存为-惊醒保存。
目前做法：
1、复制到 sublime，通过插件预览另存为 PDF
2、http://www.mdtr2pdf.com/index.html  通过该站进行转换

### 其他信息

暂无

**Comment by 88250** [comment]
我觉得放在前台可能更好一些，这样其他浏览者也可以下载到文章的 PDF 文档。

### 方案

* 加入文章链接查询字符串接口 {permalink}?export=pdf，可未登录访问，访问即下载该文章的 PDF
* PDF 主要包含：博客名称、博客地址、作者，文章标题、文章地址、摘要、目录、正文
* 使用方式由博主来告诉浏览者：签名档或者公告栏

这样设计功能入口是“隐藏的“，需要在文档中介绍。

### 实现

* 签名档中填充 ${articlePermalink} 变量
* 渲染文章时读取 export 参数
* 引入 PDF 处理库
* 处理下载流

---

欢迎随时讨论 😅

**Comment by 88250** [comment]
研究了下导出 PDF 主要难点是中文字体，这需要服务器上有字体，把字体打在 Solo 包中的话又太大了。

暂时先放弃这个特性了，以后如果有更好的解决方案再继续。
