### ISSUE TITLE
后台管理添加邮箱管理功能

### ISSUE THREAD

**Issue by lizhongyue248** [b3log/solo#12635]
### 你在什么场景下需要该功能？

尝试配置邮箱的时候遇到以下问题：

1. 每次都要修改配置文件然后重启十分麻烦
2. 邮箱配置好后重启后，必须要自己手动留言测试，并且留言测试后，在博客中删除测试的评论，社区未同步删除评论
3. 邮箱测试多次都不行，只有弄下来 dev 分支进行测试，还要理半天代码=-=
4. 由于邮箱功能的缺失，回复评论别人收不到通知，很少回访博客。

### 描述可能的解决方案

添加后台的邮箱管理功能

1. 可以考虑使用内存配置覆盖文件配置的方式，在后台进行修改配置信息，然后同步在内存中，覆盖掉启动时读取到的文件配置，待测试成功后，再去修改配置文件重启应用。
2. 邮箱管理功能提供一键发送测试邮件功能
3. 提供几大邮箱（163，QQ等）样板化配置（好像有点强人所难。。。逃。。。）
4. 无奈=-=

### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

样板化配置最容易实现

### 其他信息

至今邮箱还没用起来，，泪奔。

**Comment by 88250** [comment]
邮箱配置没有做成 UI 动态化是考虑到这个配置基本是不变的，一旦配置好后很少会再更新。关于配置邮箱，可以打开 mail.props 中的 `mail.debug=true`，这样可以很方便的看到连接邮件服务出问题的报错信息。

非常感谢你的建议，但我们不打算去修改了，见谅。
