### ISSUE TITLE
重构数据统计计数

### ISSUE THREAD

**Issue by flashdoggy** [b3log/solo#12633]
辛苦各位大大一直在更新了，
今天碰到了关于 statistic 参数的一些结构问题。

我们的文章数/评论数等真的要做成 statistic 来另存吗？
我这只是疑问，因为不太懂这么做的必要性。
今天因为数据迁移导致一直没关注到这个地方。
查了很长时间才发现这原来是从数据库取出来的。
否则凡是用到的都会以数据库的个数为准查出来。

**Comment by 88250** [comment]
谢谢关注，这样设计师为了减少一次 count 查询，后续可能会移除，因为这个优化对于博客的数据量来说完全没啥必要，还增加了复杂度。

更多关于 Solo 设计的细节和考量请参考[《Solo 从设计到实现》](https://hacpai.com/article/1537690756242) ❤️

**Comment by flashdoggy** [comment]
谢谢D佬的回复和关注
辛苦大家了
相信数据结构重组又是个不小的工作量
我会一直支持的！

**Comment by 88250** [comment]
有时候以前的特性会随着时间的流逝变为缺陷，特别是性能相关的优化。

> 过早的优化是万恶之源 —— Donald Knuth
