### ISSUE TITLE
仅支持 GitHub 登录

### ISSUE THREAD

**Issue by 88250** [b3log/solo#12630]
从 v2.9.9 起仅支持通过 GitHub 登录进行初始化和注册、登录，主要是为了解决和社区账号关联一致性的问题。

在升级 v2.9.9 之前，在用 v2.9.8 的用户需要进行如下操作：

1. 在 Solo 后台用户管理中，将用户名、邮箱改成和你 GitHub 账号一致
2. 升级 v2.9.9，然后通过 GitHub 登录即可

**Comment by iTanken** [comment]
是不是比邮箱登录更方便、安全了

**Comment by acuilab** [comment]
我有一台电脑用github账号退出后，就再也没有登上去过

**Comment by acuilab** [comment]
版本3.2.0

**Comment by 88250** [comment]
@acuilab 你好，用户名不一致么？如果不一致的话可以手动修改数据库 user 表。
