### ISSUE TITLE
升级Solo后Github登录报错

### ISSUE THREAD

**Issue by linkerlin** [b3log/solo#12646]
![image](https://user-images.githubusercontent.com/37062/52544369-872dc900-2deb-11e9-8a4b-0cdd82fd203b.png)
似乎是表丢失了字段，自动升级没有扩表？
solo master代码，H2数据库。

**Comment by 88250** [comment]
先升级到 tag v2.9.9，master 上面是 dev v3.0.0 ，升级程序还没有完成。
