### ISSUE TITLE
v3.0.0版本打开/admin-index.do#tools/user-list页面报错

### ISSUE THREAD

**Issue by jerryhwq** [b3log/solo#12649]
### 描述问题

solo v3.0.0版本用户管理界面无法打开

### 重现步骤

登录solo后打开solo后台管理的/admin-index.do#tools/user-list界面即可看到

### 期待的结果

左上角始终显示载入中且控制台会有报错

### 其他信息

#12645 中将变量commentEmail1Label删除，而[src/main/webapp/admin/admin-user-list.ftl](https://github.com/b3log/solo/blob/master/src/main/webapp/admin/admin-user-list.ftl)中仍旧依赖这个变量引起

**Comment by 88250** [comment]
已经在主干上进行修复，war 包稍后更新，感谢反馈！

**Comment by 88250** [comment]
你好，已经重新打包上传，如果需要请重新下载发布包，谢谢。
