### ISSUE TITLE
solo3.0 后台管理中发布文章无法出现编辑框

### ISSUE THREAD

**Issue by CodingOX** [b3log/solo#12656]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[讨论区](https://hacpai.com/tag/solo)搜寻资料解决问题。

----

### 描述问题

请尽量清晰精准地描述你碰到的问题。
RT,图如下所示，无法出现编辑框
![image](https://user-images.githubusercontent.com/9800933/53020624-43ddf500-3492-11e9-829a-077b50e8bc46.png)

### 重现步骤

请描述如何重现这个问题：

1. 通过http://hicode.club/admin-index.do 登录后台管理
2. 点击发布文章后出现上述图片

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 桌面端环境

- OS: [mac]
- Browser chrome
- Version 72.0.3626.109

### 其他信息
1、已尝试在Safari 和重新安装，均不可以
2、昨晚首次进入进入没有问题，今天单纯在服务器安装了node 后出现该问题。

**Comment by 88250** [comment]
不好意思，这两天编辑器这部分有比较大的调整。如果你是自己打包的，请重新从 master 上拉取最新代码进行编译部署。v3.0.0 的发布包稍后上传。

**Comment by 88250** [comment]
发布包已经上传，如有需要请重新下载，造成不便请见谅。
