### ISSUE TITLE
手机版文章内容很长不换行，没法看

### ISSUE THREAD

**Issue by liuwenchang** [b3log/solo#12665]
用手机打开界面布局是正常的，就是点开博客，博客内容很长不换行，要滑动文本框滚动条才能看全

**Comment by 88250** [comment]
麻烦给个链接，方便我们排查问题，谢谢。

**Comment by liuwenchang** [comment]
这么晚还没睡，我开头打两个空格是正常的，打四个空格就不行。。。可能是markdown格式问题。应该不算问题。

**Comment by 88250** [comment]
四个空格的话会被识别为代码块，如果要按照传统中文习惯排版（开头空两格）的话，可以用全角空格。

晚安 😅
