### ISSUE TITLE
添加文章时间设置功能

### ISSUE THREAD

**Issue by EricTao2** [b3log/solo#12660]
### 你在什么场景下需要该功能？

从其他博客系统改用Solo，文章时间全都是今天发布的。

### 描述可能的解决方案

在发布文章时增加发布时间的功能。

**Comment by 88250** [comment]
你好，博客迁移的话可以使用 Markdown 导入功能，这样时间、存档都能复原。

**Comment by EricTao2** [comment]
谢谢，能不能给一个文档链接，还不知道有这样的功能

**Comment by 88250** [comment]
文档链接 https://hacpai.com/article/1498490209748

我关闭这个 issue 了，如果还有问题跟帖即可，感谢使用！
