### ISSUE TITLE
如何添加高亮代码

### ISSUE THREAD

**Issue by MachiBarton** [b3log/solo#12661]
### 你在什么场景下需要该功能？

请尽量清晰精准地描述你碰到的问题。

### 描述可能的解决方案

请尽量清晰精准地描述你期待我们要做的，描述你想到的实现方案。

### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by MachiBarton** [comment]
想放代码片段不过没有看到放代码的功能，请问怎么使用

**Comment by 88250** [comment]
你好，使用 Markdown 语法即可。代码块语法：

<pre>
```java
public class HelloWorld {

    public static void main(String[] args) {
        System.out.println("Hello World!");
    }

}
```
</pre>

更多 Markdown 语法细节请参考[这里](https://hacpai.com/guide/markdown)。
