### ISSUE TITLE
皮肤 favourite 的问题

### ISSUE THREAD

**Issue by MikeoPerfect** [b3log/solo#12677]
![2019-02-27_153234](https://user-images.githubusercontent.com/37768864/53473334-19e58d80-3aa5-11e9-92d2-51286aa8bb01.jpg)

副标题被遮盖，且整个皮肤似乎有些错位和粗糙，和原来的2.99版本比较，3.00显得不是那么的精细

**Comment by Vanessa219** [comment]
@MikeoPerfect  非常抱歉，由于 https://github.com/b3log/solo/issues/12658 产生了新问题，现已基本修复，如果还有细节问题可以随时 reopen
