### ISSUE TITLE
博文定时同步 GitHub 仓库

### ISSUE THREAD

**Issue by 88250** [b3log/solo#12676]
### 特性介绍

将博文定时同步到自己的 GitHub 仓库中，每隔 24 小时做一次全量同步。

应用场景与动机：

* 通过 GitHub 让更多人看到自己的博客
* 自动在 GitHub 仓库上备份文章 

### 实现流程

1. 博客端定时触发同步请求，将所有公开（非加密）文章导出 md 打 zip 包
2. 将包发送至社区服务器，由社区服务器完成仓库创建/更新、文件提交

由社区服务器进行 GitHub 操作主要考虑到两点：

* 安全性，避免运维过程中潜在的凭证泄露（下面会进行详细描述）
* 可用性，由社区服务器国外节点进行操作，减少国内网络问题带来的影响

### 安全考量

主要涉及 GitHub 访问凭证（Access Token）的授权和使用。

#### 凭证授权

目前博客端在进行 GitHub 登录时申请的权限包括：

* public_repo：公开仓库相关的读写操作，比如创建仓库、Issues、提交代码等
* read:user：读取用户信息
* user:follow：关注/取消关注用户

具体细节可以通过[该文档](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/)了解。我们仅在用户同意授权使用该功能的情况下做操作（博客端会在设置中增加`是否需要同步仓库`的选项，**默认不同步**），大家进行公开监督，避免产生不必要的误会。

#### 凭证使用

凭证统一在社区存储，由社区统一进行运维操作，尽量避免潜在的安全泄露。所以博客端不进行凭证相关的任何存储和操作以降低风险。如果发现安全问题，我们会在 GitHub 上注销所有凭证，将安全问题产生的影响降到最低程度。

**Comment by lai-bluejay** [comment]
社区的github设置后没反应。repos不更新

**Comment by 88250** [comment]
@lai-bluejay 收到，这个问题是程序 bug，稍后修复 😅

**Comment by TerickJojo** [comment]
大佬，希望这个功能设置成可选，毕竟有些文章不希望同步到github里（和代码无关的文章）。。。

**Comment by 88250** [comment]
@TerickJojo 同步的效果不是在 GitHub 中展开每篇文章，而是上传文章 md 文件的 zip 包，仓库 READMD 里面会自动生成最新、热门、热议文章的索引，链接到博客的文章。主要目的是为博客文章数据做备份以及索引导流到博客，效果可参考[这里](https://github.com/88250/solo-blog)。

配置项也是有的，不过是全局的，可配置是否开启同步仓库。你感觉这样可以接受吗，或者有其他任何建议都欢迎讨论，目前还在开发中 😅

**Comment by TerickJojo** [comment]
> 这里

还是希望有一个配置是否开启同步仓库的功能

**Comment by 88250** [comment]
@TerickJojo 是有的，并且默认不开启同步。

**Comment by TerickJojo** [comment]
> @TerickJojo 是有的，并且默认不开启同步。

多谢啦

**Comment by 88250** [comment]
已经上线，最终效果请看[这里](https://github.com/88250/solo-blog)。

**Comment by lizhongyue248** [comment]
请问可以询问下流程嘛？我开启以后，他首先 fork [这里](https://github.com/88250/solo-blog)，但是等待了一会儿后就没有了动静？同步过程是怎样的呢？

**Comment by 88250** [comment]
@lizhongyue248 Solo 后台开启开关即可，启动 Solo 服务后 10 分钟会跑第一次定时任务，后续每 24 小时跑一次。

**Comment by lizhongyue248** [comment]
> @lizhongyue248 Solo 后台开启开关即可，启动 Solo 服务后 10 分钟会跑第一次定时任务，后续每 24 小时跑一次。

https://github.com/lizhongyue248/solo-blog 十分钟后，并没有更新，是要等待 24 小时吗？

**Comment by 88250** [comment]
@lizhongyue248 呃，不用 fork 我的啊。仓库创建和更新程序会自动做的。你先确保 Solo 后台这个功能的开关是打开的，然后：

1. 手动删除刚刚 fork 的仓库
2. 重启 Solo 等待 10 分钟

**Comment by lizhongyue248** [comment]
@88250 不是我 fork 的啊。。。他是自动 fork 的，，我开启后，他就自动 fork 了。。。那我删除重启 solo 试试看。

**Comment by 88250** [comment]
@lizhongyue248 不会 fork 的，你可能是之前手动点过吧 😂

**Comment by lizhongyue248** [comment]
@88250 这个真木有，我看日期是今天才 fork 的。。。重启了快二十分钟，仓库没有变化。。我重新开启选项试试

**Comment by 88250** [comment]
@lizhongyue248 那就奇怪了，我没写过这样的代码。

**Comment by 88250** [comment]
@lizhongyue248 同步时 Solo 会打日志，你看下是不是报什么错了。

**Comment by liu215677** [comment]
从git master下载的代码 通过idea打包的 部署后，勾选git但是没有同步，后台有看到一些错误o.IOException: Broken pipe
，Invalid character found in method name. HTTP method names must be tokens

**Comment by 88250** [comment]
@liu215677 你好，可以在本地开发环境打断点调试看看。这个功能的实现方法是 `ExportService#exportGitHubRepo`，功能是通过定时任务触发的，入口在 `CronMgmtService#start`。启动后等 10s 后就会进入断点。

**Comment by liu215677** [comment]
> @liu215677 你好，可以在本地开发环境打断点调试看看。这个功能的实现方法是 `ExportService#exportGitHubRepo`，功能是通过定时任务触发的，入口在 `CronMgmtService#start`。启动后等 10s 后就会进入断点。

**Comment by liu215677** [comment]
> @liu215677 你好，可以在本地开发环境打断点调试看看。这个功能的实现方法是 `ExportService#exportGitHubRepo`，功能是通过定时任务触发的，入口在 `CronMgmtService#start`。启动后等 10s 后就会进入断点。

ExportService在这个类中
            if (Latkes.getServePath().contains("localhost") || Strings.isIPv4(Latkes.getServerHost())) {
                return;
            }
这段代码检测了ipv4为true 然后返回了

**Comment by 88250** [comment]
@liu215677 本地调试的话先注释掉；线上的话需要配置域名参数。

**Comment by liu215677** [comment]
> @liu215677 本地调试的话先注释掉；线上的话需要配置域名参数。

域名参数是配置 latke.properties 这个文件里面的serverHost 吗

**Comment by 88250** [comment]
@liu215677 是的。

**Comment by iTanken** [comment]
![image](https://user-images.githubusercontent.com/23544702/59829691-9c55ce00-9370-11e9-9c9a-2f04940571ba.png)

@88250 我这个配置是打开的，但是从来都没有同步过来，这是什么情况？

**Comment by 88250** [comment]
@iTanken 你看下日志里面有没有这句 `Github repo sync completed`

**Comment by iTanken** [comment]
> @iTanken 你看下日志里面有没有这句 `Github repo sync completed`

没有打开文件日志，我先打开文件日志观察一下。话说没有窗口的话怎么看 `INFO` 和 `stdout` 的日志？

**Comment by 88250** [comment]
@iTanken 没有窗口？

**Comment by iTanken** [comment]
> @iTanken 没有窗口？

就是通过定时任务在后台启动的，没有命令行窗口

**Comment by iTanken** [comment]
> @iTanken 你看下日志里面有没有这句 `Github repo sync completed`

重启了几次，没有 10 分钟后看日志都没有相关日志

**Comment by 88250** [comment]
@iTanken 看下是不是命中这个条件了？

```java
if (Latkes.getServePath().contains("localhost") || Strings.isIPv4(Latkes.getServerHost())) {
     return;
}
```

**Comment by iTanken** [comment]
> @iTanken 看下是不是命中这个条件了？
> 
> ```java
> if (Latkes.getServePath().contains("localhost") || Strings.isIPv4(Latkes.getServerHost())) {
>      return;
> }
> ```

哦哦，是因为我没有配置 serverHost 啊

**Comment by 88250** [comment]
@iTanken 不应该没有配置吧，这个配置项是域名的配置项啊。

**Comment by iTanken** [comment]
只配置了一个 https，主机和端口都没配置

**Comment by 88250** [comment]
@iTanken 好吧....配置上应该就 OK 了，我看你那边现在已经好了 https://github.com/iTanken/solo-blog

**Comment by xiewensheng** [comment]
我已经勾选了偏好设置中的同步到github  但是我在我的github并没有找到solo-blog仓库，这是怎么回事？

**Comment by 88250** [comment]
> 我已经勾选了偏好设置中的同步到github 但是我在我的github并没有找到solo-blog仓库，这是怎么回事？

博客已经用域名上线了吗？

**Comment by xiewensheng** [comment]
> > 我已经勾选了偏好设置中的同步到github 但是我在我的github并没有找到solo-blog仓库，这是怎么回事？
> 
> 博客已经用域名上线了吗？

![image](https://user-images.githubusercontent.com/10386461/65400067-c5b04b00-ddf2-11e9-83ce-06aeff2f5bb7.png)
一直都 Github repo syncing

**Comment by 88250** [comment]
@xiewensheng 麻烦更新最新版，最新版加入了更详细的日志。
