### ISSUE TITLE
文章结构加入首图字段

### ISSUE THREAD

**Issue by 88250** [b3log/solo#12670]
文章结构加入首图字段 `articleImg1URL`，用于存储从正文中自动提取的首图地址。

* 如果文章有图片，则自动提取第一幅图片地址作为首图地址
* 如果文章没有图片，则自动用社区的[首图服务](https://github.com/b3log/bing)提供的图片地址进行填充

**Comment by iTanken** [comment]
只提取正文的首图？摘要里的处理不？

**Comment by 88250** [comment]
@iTanken 优先提取摘要里的。
