### ISSUE TITLE
latke.props 调整

### ISSUE THREAD

**Issue by 88250** [b3log/solo#12683]
https://github.com/b3log/latke/issues/141

默认配置文件中删除 `serverHost` 和 `serverPort`，仅保留一项 `serverScheme`。

**Comment by mainlove** [comment]
几十年的问题了

**Comment by 88250** [comment]
害得很多人浪费了宝贵的时间，这些时间加起来我估计可以绕地球三圈了。

> 浪费别人的时间等于谋财害命
