### ISSUE TITLE
皮肤 Pinghsu 的两个问题

### ISSUE THREAD

**Issue by iTanken** [b3log/solo#12685]
### 1. article-list.ftl 问题
第 27 行 `${article.articleAbstractText}` 需改为 `${article.articleAbstractText!""}`，因为对应第字段有 `null` 的情况。
### 2. 首页标题显示问题
标题超过一行后，与`有更新` / `置顶` 重叠：
![image.png](https://img.hacpai.com/file/2019/03/image-3faa87e4.png)

.

**Comment by 88250** [comment]
感谢反馈。请问 1 是已经发生 null 还是从数据库字段上看的？问题 2 已经在 https://github.com/b3log/solo/issues/12679 修复。

**Comment by iTanken** [comment]
报错之后查的数据量看的

**Comment by 88250** [comment]
收到，可能是升级程序的问题，我尽量改改看，先关闭 issue 了。
