### ISSUE TITLE
移除邮件相关功能

### ISSUE THREAD

**Issue by 88250** [b3log/solo#12690]
Solo 自 v3 以后用户认证基于 GitHub OAuth，在 GitHub 授权后回调社区授权服务时会将用户的邮箱信息擦除，所以在博客端其实是获取不到邮箱信息的。由此，之前的邮件通知功能其实也就没有可能被用到。

改造点：

* 申请权限时减少 GitHub Scope `user:email`
* 删除 user 结构 email 字段
* 删除邮件相关配置和功能：mail.props 配置、SMTP 发送、通知模板

**Comment by lizhongyue248** [comment]
移除以后，评论或者回复评论，是不是就没有邮件提示了？

**Comment by 88250** [comment]
@lizhongyue248 是的。博主自己查看评论倒不是多大问题，但如果回复评论者的话就没法实现了，还在想解决方案，欢迎提建议。
