### ISSUE TITLE
3.2.0版本开发环境启动失败

### ISSUE THREAD

**Issue by Usernameisalreadytakenbitme** [b3log/solo#12697]
### 重现步骤

请描述如何重现这个问题：
1.下载文件,
2.放置skins
3.修改local.properties为mysql
4.部署到本地tomcat7.0.90
5.启动3.2.0包失败

### 期待的结果
3.2.0的似乎无法启动

### 截屏或录像

请提供其他附加信息帮助我们诊断问题。
![image](https://user-images.githubusercontent.com/27808855/53778934-72031080-3f39-11e9-80cf-a871ee37f7e3.png)
![image](https://user-images.githubusercontent.com/27808855/53779276-8abff600-3f3a-11e9-8737-4a12f53cf3f2.png)

**Comment by 88250** [comment]
你好，这是因为 v3 之前不支持跨版本升级。需要一个一个版本升级到 v3.0.0 才能支持跨版本升级。

**Comment by Usernameisalreadytakenbitme** [comment]
直接启动3.2.0也是不行的么

**Comment by 88250** [comment]
把之前的数据库删了吧，在 home 下面。

**Comment by ClonkMr** [comment]
大佬,再请教一下几个问题,看了一下你的代码,
1.脱离了常用的开源架构,请问是为什么?为了安全么?
2.本地账号的功能似乎被删除了,这样的话和B3log绑定的太紧了?似乎有违开源的初衷
3.如果开源的话能否有一份二次开发指引之类的文档什么的
4.可能testNG我不太常用,好像testCase无法以Debug模式启动?或者是什么地方跳过了,增加了代码单元测试却起不来,原谅我太菜了

**Comment by 88250** [comment]
1. 不是为了安全，主要是为了实现一些想法，具体细节请浏览[这里](https://hacpai.com/article/1403847528022)
2. 这是 B3log 的初心，能开源的部分我们已经尽量开源了
3. [Solo 从设计到实现](https://hacpai.com/article/1537690756242)
4. 可以 debug 的，如果用 IDEA 的话直接在具体的测试方法上 Run 就行

感谢关注！
