### ISSUE TITLE
What's the difference between pipe and solo

### ISSUE THREAD

**Issue by yb123speed** [b3log/solo#12707]
rt

**Comment by 88250** [comment]
* Solo 是一款博客系统，仅支持团队协作，用户共用同一个后台和前台
* Pipe 是一款博客平台，支持多用户，每个用户有自己的后台和前台
* Solo 功能稍微多一些，比如支持草稿、友情链接
* Solo 是 Java 实现的，Pipe 是 Go 实现的

感谢关注 😄
