### ISSUE TITLE
无法初始化

### ISSUE THREAD

**Issue by qichuangguo** [b3log/solo#12704]
500 Internal Server Error!

**Comment by 88250** [comment]
你好，方便贴一下日志么？

**Comment by qichuangguo** [comment]
[ERROR]-[2019-03-11 12:52:28]-[org.b3log.latke.servlet.renderer.AbstractFreeMarkerRenderer:131]: Renders template [index.ftl] failed [Request [
    method=GET,
    URL=http://localhost:8080/,
    contentType=null,
    characterEncoding=UTF-8,
    local=[
        addr=127.0.0.1,
        port=8080,
        name=localhost],
    remote=[
        addr=127.0.0.1,
        port=34724,
        host=127.0.0.1],
    headers=[
        host=localhost:8080
        connection=close

**Comment by qichuangguo** [comment]
FreeMarker template error:
The following has evaluated to null or missing:
==> loginLabel  [in template "skins/amaze/header.ftl" at line 76, column 19]

**Comment by 88250** [comment]
请问你那边是 clone 代码部署的还是使用我们打的包？

**Comment by 88250** [comment]
这个问题是因为 amaz 这款第三方皮肤没有跟随 Solo 主版本更新，如果方便的话可以到源库上提交一个 issue 催更 😄 

https://github.com/zjhch123/solo-skin-amaze
