### ISSUE TITLE
可配置 favicon 图标路径

### ISSUE THREAD

**Issue by 88250** [b3log/solo#12706]
尽量减少对资源的改动，这样升级起来会更方便一些。

需求灵感来源： [Solo-auto (Solo 独立部署方式自动检测更新)](https://github.com/lizhongyue248/solo-auto)

- [x] favicon 配置
- [x] 移除页面中 logo.png

**Comment by iTanken** [comment]
还有 `logo.png` `logo.jpg` `logo/logo@**.png` 😁

**Comment by 88250** [comment]
@iTanken 收到，我们干脆把这些都尽量移除了吧，主要是 40x 页面、开始页。

**Comment by Vanessa219** [comment]
@88250 logo/logo@**.png 不太好弄，是和 PWA 相关的。
