### ISSUE TITLE
移除Latke配置文件导致的异常

### ISSUE THREAD

**Issue by MikeoPerfect** [b3log/solo#12701]
### 描述问题
3.1版本之前未出现Nginx中upstream引发的URL链接无效
3.2版本移除latke配置文件中的serverPort等等导致原Nginx配置失效
![image](https://user-images.githubusercontent.com/37768864/54068598-c4219a00-4289-11e9-816f-1b05a8294f4d.png)

**Comment by 88250** [comment]
latke.props 里面配置一下 `serverHost`。

**Comment by MikeoPerfect** [comment]
> latke.props 里面配置一下 `serverHost`。
看来还是要带上Port了
![image](https://user-images.githubusercontent.com/37768864/54068739-c3d5ce80-428a-11e9-8e8a-807cf379f28f.png)

**Comment by 88250** [comment]
可以参考一下 [Solo 用户指南](https://hacpai.com/article/1492881378588)，里面有个 NGINX 的配置示例。
