### ISSUE TITLE
更新博客域名提示

### ISSUE THREAD

**Issue by 88250** [b3log/solo#12716]
工具 - 信息配置中该配置项是优先读取 latke.pros 中 `serverHost` 配置项，如果该配置项不存在则按当前请求赋值，**建议修改配置文件或命令行传参**。

#### 配置文件

更新 latkr.props 中的 `serverHost`，修改为对外访问的域名，例如

```properties
serverHost=88250.b3log.org
```

不需要加端口或者协议，协议由 `serverScheme` 确定，端口由 `serverPort` 确定，端口默认留空即可。

#### 命令行参数 

通过命令行参数传入 `--server_host=88250.b3log.org`。

### 重启

配置完成后需要重启服务。

**Comment by aliang228** [comment]
如果是docker中启动的如何更改域名呢？ 发现修改container中的`latke.properties`重启后并不生效。

**Comment by 88250** [comment]
@aliang228 通过命令行参数代入即可，不用改配置文件。

**Comment by aliang228** [comment]
> @aliang228 通过命令行参数代入即可，不用改配置文件。

好的，多谢。 我之前是因为考虑到修改了container信息导入了历史的markdowns。从源码来看数据是入库了的，重启应该不影响。
