### ISSUE TITLE
管理员修改用户名后无法登陆

### ISSUE THREAD

**Issue by the-wang** [b3log/solo#12728]
v3.3.0
以管理员身份登陆，到“用户管理”修改自己的用户名，退出后无法登录

**Comment by 88250** [comment]
请手动修改 user 表中的记录。另外，目前 solo 以及社区会将用户名中的 `-` 剔除，可能是因为这个问题造成你登录不了的，这个问题我们正在努力修复，让 Solo 和社区允许使用包含 `-` 的用户名。
