### ISSUE TITLE
新皮肤 Casper

### ISSUE THREAD

**Issue by Vanessa219** [b3log/solo#12737]
参考：https://github.com/TryGhost/Casper

https://github.com/b3log/solo/issues/12449

**Comment by pencilso** [comment]
这皮肤好丑

**Comment by Vanessa219** [comment]
欢迎推荐 https://github.com/b3log/solo/issues/12449

**Comment by Complexity-Naughty** [comment]
新皮肤不能用，报500错误

**Comment by 88250** [comment]
@Complexity-Naughty 你好，Solo 版本是最新版么？
