### ISSUE TITLE
点击任意分类标签后，下一页跳转异常

### ISSUE THREAD

**Issue by Hanseltu** [b3log/solo#12735]
### 描述问题

个人使用solo v3.3.0版搭建的博客系统，站点https://www.tuhaoxin.cn

进入主页后点击分类中的任一个，下拉到第二页，跳转发生如下异常

<img width="898" alt="404" src="https://user-images.githubusercontent.com/19731522/54867408-d4259780-4dba-11e9-957f-b0cc6f0d4d65.png">

### 重现步骤

1. 访问https://www.tuhaoxin.cn
2. 找到分类->LeetCode每日一刷
3. 下拉翻页，点击第2页
4. 出现404错误

### 期待的结果

正常显示该标签下第二页的内容

**Comment by 88250** [comment]
麻烦在分类管理中将分类的 URI 设置为英文，然后帮忙看下是否还 404，谢谢。

**Comment by Hanseltu** [comment]
ok了。谢谢~
