### ISSUE TITLE
为什么删除了上传到服务器功能呢？

### ISSUE THREAD

**Issue by the-wang** [b3log/solo#12732]
如 https://hacpai.com/article/1442418791213 中所述，本来都支持的功能为什么要删除呢？

感觉支持上传服务器挺好啊，很多人也有这个需求，现在都上传到公共图床是挺简单，但是自己就无法完全掌握自己的数据了呀，万一这个图床不稳定了，岂不是自己的所有图片都丢了？难道还需要自己单独维护一份图片吗？

求解。

**Comment by 88250** [comment]
https://hacpai.com/article/1553236036778/comment/1553240453247?r=88250
