### ISSUE TITLE
Casper 细节修改

### ISSUE THREAD

**Issue by lizhongyue248** [b3log/solo#12748]
### 描述问题

1. 浏览文章时，**点击目录跳转到对应标题位置**，然后点击代码块右上角复制，代码已成功复制，但是文章会跳回到文章顶部。
2.  Caspe 手机端没有目录，长文章阅读不便
3. 当设置站外阅读数量为 0 时，文章底部出现黑色的占位块
4. 另外建议 Caspe 手机端文章浏览时，只有一张图片就够了。。。

### 重现步骤

1. 进入文章
2. 点击目录跳转
3. 找到代码块复制
4. 文章会跳回顶部

### 期待的结果

1. 正常复制且文章不回顶部
2. 手机端加上目录
3. 当设置站外阅读数量为 0 时，文章底部没有黑色占位块
4. 另外建议 Caspe 手机端文章浏览时，只有一张图片就够了。。。

### 桌面端环境

- OS: linux
- Browser firefox

**Comment by Vanessa219** [comment]
- [ ] 复制代码块文章回到顶部 bug
- [ ] 手机端加上目录
- [ ] 当设置站外阅读数量为 0 时，文章底部没有黑色占位块
- [ ] Casper 移动端移除背景图
- [ ] 点击文章标题回到顶部

**Comment by 88250** [comment]
页脚会空白：

![image](https://user-images.githubusercontent.com/873584/55404433-751a0c80-558a-11e9-95e1-9d53319c6221.png)
