### ISSUE TITLE
签名档内置模板变量

### ISSUE THREAD

**Issue by iTanken** [b3log/solo#12758]
在 `后台管理`> `工具`> `偏好设置`> `签名档` 中编辑签名档时，能支持 Markdow 语法实为刚需，若签名为版权声明之类的内容，则需要引用原文链接等信息，故需要支持公共模板变量。

![image.png](https://img.hacpai.com/file/2019/04/image-ce7dbf3b.png)

**Comment by 88250** [comment]
签名档还是得用 HTML，因为有脚本需求。公共变量这个是需要，下个版本优化，感谢建议！

**Comment by iTanken** [comment]
> 签名档还是得用 HTML，因为有脚本需求。公共变量这个是有必要的，感谢建议！

👌

**Comment by 88250** [comment]
内置变量：

* `{title}`：文章标题
* `{author}`：作者用户名
* `{url}`：文章地址
