### ISSUE TITLE
我的开源页面排版推荐

### ISSUE THREAD

**Issue by iTanken** [b3log/solo#12759]
代码
-------

```markdown
[GitHub Repositories](https://github.com/${adminUser.name}?tab=repositories&type=source)
------------------------

### 📂 1. [仓库名称一](https://github.com/${adminUser.name}/仓库名称) <kbd title="主要编程语言">CSS</kbd> 
>
> 仓库描述信息 Description
> [🤩 `999`](https://github.com/${adminUser.name}/仓库名称/watchers "关注数") [⭐️ `666`](https://github.com/${adminUser.name}/仓库名称/stargazers "收藏数") [🖖 `0`](https://github.com/${adminUser.name}/仓库名称/network/members "分支数")
>  [🏠 仓库主页地址 Website](https://itanken.github.io/***/ "项目主页")

------

### 📂 2. [仓库名称二](https://github.com/${adminUser.name}/仓库名称) <kbd title="主要编程语言">CSS</kbd> 
>
> 仓库描述信息 Description
> [🤩 `999`](https://github.com/${adminUser.name}/仓库名称/watchers "关注数") [⭐️ `666`](https://github.com/${adminUser.name}/仓库名称/stargazers "收藏数") [🖖 `0`](https://github.com/${adminUser.name}/仓库名称/network/members "分支数")
>  [🏠 仓库主页地址 Website](https://itanken.github.io/***/ "项目主页")

------

```

效果
------

[GitHub Repositories](https://github.com/${adminUser.name}?tab=repositories&type=source)
------------------------

### 📂 1. [仓库名称一](https://github.com/${adminUser.name}/仓库名称) <kbd title="主要编程语言">CSS</kbd> 
>
> 仓库描述信息 Description
> [🤩 `999`](https://github.com/${adminUser.name}/仓库名称/watchers "关注数") [⭐️ `666`](https://github.com/${adminUser.name}/仓库名称/stargazers "收藏数") [🖖 `0`](https://github.com/${adminUser.name}/仓库名称/network/members "分支数")
>  [🏠 仓库主页地址 Website](https://itanken.github.io/***/ "项目主页")

------

### 📂 2. [仓库名称二](https://github.com/${adminUser.name}/仓库名称) <kbd title="主要编程语言">Java</kbd> 
>
> 仓库描述信息 Description
> [🤩 `999`](https://github.com/${adminUser.name}/仓库名称/watchers "关注数") [⭐️ `666`](https://github.com/${adminUser.name}/仓库名称/stargazers "收藏数") [🖖 `0`](https://github.com/${adminUser.name}/仓库名称/network/members "分支数")
>  [🏠 仓库主页地址 Website](https://itanken.github.io/***/ "项目主页")

------

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/56080441-c8fede00-5e33-11e9-96a1-9e5112398b68.png)
