### ISSUE TITLE
发表文章图片上传、加载问题

### ISSUE THREAD

**Issue by iTanken** [b3log/solo#12757]
### 描述问题
* Solo 版本：3.5
* 皮肤：Casper

1. 上传问题：
若博客已有内容，向内容插入图片，上传中提示的 Markdown 一直不变，上传成功后的 Markdown 内容会添加到文章末尾，而不是插入的位置：
![image.png](https://img.hacpai.com/file/2019/04/image-615ad606.png)
![image.png](https://img.hacpai.com/file/2019/04/image-54ed1453.png)

2. 加载问题：
发表前预览正常，发表后浏览时图片链接后会自动添加参数 `?imageView2/2/w/768/format/jpg/interlace/1`，但会重复添加两次，导致参数错误，无法正常显示图片：
```
https://img.hacpai.com/file/2019/04/caddyrproxyhttps-cb279b5e.png?imageView2/2/w/768/format/jpg/interlace/1?imageView2/2/w/768/format/jpg/interlace/1
```
![image.png](https://img.hacpai.com/file/2019/04/image-9a31ec13.png)

### 桌面端环境
- OS: Windows 10
- Browser: Chrome

**Comment by iTanken** [comment]
还有一个问题就是发贴的时候选中 `同步到社区` 不起作用，发表后在列表中手动点 `推送到社区` 后才同步到社区。

**Comment by iTanken** [comment]
另外 Casper 皮肤的首页顶部背景图和文章内容的顶部大图，建议添加一个 `filter: blur(5px)` 之类的模糊效果 😊

**Comment by Vanessa219** [comment]
@iTanken 

* 同步需要  30 秒，你有空再试一下。
* 加载问题可以给以下具体的重新啊步骤么？

**Comment by iTanken** [comment]
> @iTanken
> 
> * 同步需要  30 秒，你有空再试一下。 （Pipe 是定时 30 秒触发，Solo 不是定时的）
> * 加载问题可以给以下具体的重新啊步骤么？

* 操作过程：
![solo.gif](https://img.hacpai.com/file/2019/04/solo-da5de337.gif)

* 测试文章链接：
[https://zixizixi.cn/ImageUploadTest](https://zixizixi.cn/ImageUploadTest)

**Comment by 88250** [comment]
图片加载重复添加处理样式这个我这边没能重现哦。

**Comment by 88250** [comment]
发布时勾选同步社区不生效是个 bug，稍后修复。

**Comment by 88250** [comment]
上传问题也修复了，目前只剩下图片会重复添加样式的问题了，但这个问题我这边没能重现，暂时先关闭 issue 了。如果你有空请帮忙给一下重现步骤 🙏

**Comment by iTanken** [comment]
> 图片加载重复添加处理样式这个我这边没能重现哦。

那就应该是我的环境有问题，等升级 3.6 再试试
