### ISSUE TITLE
后台添加皮肤模板编辑功能

### ISSUE THREAD

**Issue by wj985712588** [b3log/solo#12753]
### 你在什么场景下需要该功能？

官方的主题不能完全满足自己的需求，希望可以自己自定义部分模板（列如添加备案信息等）

### 描述可能的解决方案

在后台列出主题文件，可以修改html文件来添加自己的想法

### 描述你认为的候选方案

类似于wordpress功能

### 其他信息

无

**Comment by 88250** [comment]
如果有自定制皮肤的需求，请通过开发阶段实现。运行时提供该功能的话会版本更新的问题：一旦皮肤被修改过，就不能用更新的版本来覆盖了，这样带来的问题可能更多。如果是通过 Docker 运行，用户有可能没有把 skins 目录挂卷，修改后持久化不了。感谢反馈，但还是暂时不考虑实现了。

对了，备案号可以通过配置页脚功能实现。
