### ISSUE TITLE
Github登录错误

### ISSUE THREAD

**Issue by just-for-krystal** [b3log/solo#12756]
### 描述问题

无法使用GitHub登录，会显示404，保存过GitHub密码的浏览器会直接404，没有保存的，会让你填写账号密码，然后出现404

### 截屏或录像
![ ](http://cdn.nextto.top/404.png)
log
![ ](http://cdn.nextto.top/log%E2%80%94%E2%80%94solo.png)
request
![ ](http://cdn.nextto.top/request.png)
nginx
![ ](http://cdn.nextto.top/nginx.png)
docker 
`docker run --detach --name solo --network=host     --env RUNTIME_DB="MYSQL"     --env JDBC_USERNAME="solouser"     --env JDBC_PASSWORD='xxx' --env JDBC_DRIVER="com.mysql.cj.jdbc.Driver"     --env JDBC_URL="jdbc:mysql://139.196.121.107:3306/solo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC"     b3log/solo --listen_port=8080 --server_scheme=https --server_host=www.nextto.top --server_port=443`

### 桌面端环境
- OS: Windows 10 1809
- Browser: Firefox 66.0.3
- Version: solo 3.5.0

**Comment by 88250** [comment]
你好，请手动修改一下数据库 user 表中的用户名为 `just-for-krystal`，然后重启 Solo 应该就能解决。带来不便请多包涵 😅
