### ISSUE TITLE
AsciiDoc 支持

### ISSUE THREAD

**Issue by lizhongyue248** [b3log/solo#12750]
### 你在什么场景下需要该功能？

现在大多项目的文档开始由 markdown 转向 [Asciidoc](http://asciidoc.org/)，相比markdown具有跟多的标记且能够更好的显示效果，是否考虑引入 AsciiDoc 的支持呢？这是目前其他博客所没有的功能。

### 描述可能的解决方案

引入 AsciiDoc 的支持

**Comment by 88250** [comment]
感谢推荐，但对于大部分用户来说 MD 还算好用，再学习一套新的标记语法可能有点不太现实。如果将来 AsciiDoc 普及了我们再跟进 🙏
