### ISSUE TITLE
There is stored xss vulnerability

### ISSUE THREAD

**Issue by czming123** [b3log/solo#12751]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[讨论区](https://hacpai.com/tag/solo)搜寻资料解决问题。

----

### 描述问题

I found a stored xss vulnerability in publishing a new article.

### 重现步骤

请描述如何重现这个问题：
I login the solo with my github account.

1. edit a new article
use payload: ```<iframe src="javascript:alert(document.cookie)"  >```
![image](https://user-images.githubusercontent.com/49016976/55538710-a95c0d00-56f1-11e9-828c-3479a85bda79.png)
2. Click on publish button.

3. go to the page of the article. We can see that alert a window with cookie.
![image](https://user-images.githubusercontent.com/49016976/55538954-25565500-56f2-11e9-8ad1-45203749c657.png)

4. obviously, this place has not the xss protection.

### 期待的结果

Fix the vulnerability

### 桌面端环境

- OS: [e.g. windows, mac, linux]

### 移动端环境

- Device: [e.g. iPhone8]
- OS: [e.g. iOS12]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
你好，博客后台可以使用脚本，包括文章内容、公告、签名档等处。感谢反馈！
