### ISSUE TITLE
docker部署,能不能提供一个简单一点的增加皮肤的方式?

### ISSUE THREAD

**Issue by MuMuloveU** [b3log/solo#12765]
### 你在什么场景下需要该功能？

后台更换皮肤的时候.

### 描述可能的解决方案

可以在后台面板通过主题的社区链接增加新的主题.

### 描述你认为的候选方案

我可以把主题文件放到指定的目录,然后可以加载出来.

### 其他信息

感谢作者开源Thanks♪(･ω･)ﾉ

**Comment by 88250** [comment]
docker 启动时挂载就行了  `--volume host_skins:/opt/solo/skins`。
