### ISSUE TITLE
升级 3.6.0 后遇到的几个问题

### ISSUE THREAD

**Issue by iTanken** [b3log/solo#12766]
#### “我的开源”导航链接问题
前缀是 `https:///`,需要手动添加域名
![image](https://user-images.githubusercontent.com/23544702/56457585-8bf49780-63af-11e9-9d87-e512f029250a.png)

#### Casper 皮肤问题
1. 首页可以正常加载导航的 Github 图标，文章页面 404，在导航管理中的图标路径前加 / 可解决：
![image](https://user-images.githubusercontent.com/23544702/56457535-ad08b880-63ae-11e9-9caa-f814cd034c9f.png)

2. 之前在 `solo-skins` 里提过的目标标题被顶部工具条覆盖的问题： https://github.com/b3log/solo-skins/issues/29

更新后发现并没有解决：
![image](https://user-images.githubusercontent.com/23544702/56457797-69b04900-63b2-11e9-8ddc-7baa32ffa6fd.png)

而且我点的是 `1. 图标类(Icon/Font/SVG…)：`，右侧目录高亮的却是 `2-2. UI 设计类`，每一个目录项目点击后高亮的位置都不对。

3. 分页按钮，当前页按钮的背景色很难区别出来，看着都是纯黑色 😂 
![image](https://user-images.githubusercontent.com/23544702/56458154-b9dcda80-63b5-11e9-9189-09ebeedf9236.png)

**Comment by iTanken** [comment]
还有一个我之前在 `solo-skins` 里提过的目标标题被顶部工具条覆盖的问题： https://github.com/b3log/solo-skins/issues/29

更新后发现并没有解决：
![image](https://user-images.githubusercontent.com/23544702/56457797-69b04900-63b2-11e9-8ddc-7baa32ffa6fd.png)

而且我点的是 `1. 图标类(Icon/Font/SVG…)：`，右侧目录高亮的确是 `2-2. UI 设计类`，每一个目录项点击后高亮的位置都不对。

**Comment by iTanken** [comment]
![image](https://user-images.githubusercontent.com/23544702/56458154-b9dcda80-63b5-11e9-9189-09ebeedf9236.png)

还有就是 Casper 皮肤这个分页按钮，当前页背景色很难区别出来，看着都是纯黑色 😂

**Comment by 88250** [comment]
现在自定义导航里面只能填完整路径了，没有带协议部分的话会自动填上 http://。图标路径也用完整路径。
其他问题 @Vanessa219 看下。

**Comment by Vanessa219** [comment]
@88250 没有压缩代码。
@iTanken 可以到 https://github.com/b3log/solo-skins 上获取最新代码

**Comment by iTanken** [comment]
好的👌

**Comment by iTanken** [comment]
![image](https://user-images.githubusercontent.com/23544702/56472006-e3683580-648b-11e9-9473-e0c2dcf8cec8.png)

@88250  还是有问题，我每次都把 `http:///my-github-repos` 手动改成 `https://zixizixi.cn/my-github-repos`，但每次重启之后都会再冒出来一个 `http:///my-github-repos`

**Comment by 88250** [comment]
收到，我们将在[这个 issue ](https://github.com/b3log/solo/issues/12768)中进行修复。

**Comment by 88250** [comment]
现在这个情况可以先停服，然后在数据库里面把 page 表里的 permalink 字段改成 `/my-github-repos` 再启动 Solo 应该可以解决。

**Comment by iTanken** [comment]
> 现在这个情况可以先停服，然后在数据库里面把 page 表里的 permalink 字段改成 `/my-github-repos` 再启动 Solo 应该可以解决。

👌
