### ISSUE TITLE
导出完整文档和文档中的图片，支持导入恢复

### ISSUE THREAD

**Issue by fish2018** [b3log/solo#12767]
### 你在什么场景下需要该功能？

备份完整文件和数据，能够导出完整的文档和文档中的图片。
将来在恢复时也可以直接导入备份。

### 描述可能的解决方案
支持导出文档和图片，也可以支持导出word
图片上传至本地一份，可以用于备份

**Comment by 88250** [comment]
目前已经支持数据导出，功能入口在后台管理 -> 工具 -> 其他 -> 数据导出，可以导出三种格式，SQL、JSON、Markdown。

文件图片的话没有必要导出吧，因为使用的是公共外链地址。社区图床会最大限度保证服务持续可用的，如果不放心可以使用其他图床，也可以使用自己维护的图床。

关于导出备份还有一个功能，入口在工具 -> 偏好设定 -> 参数设置 -> 允许同步 GitHub 仓库，勾选后将自动备份公开文章到你自己的 GitHub 仓库上，具体效果可参考[这里](https://github.com/88250/solo-blog)，实现细节可参考[这里](https://github.com/b3log/solo/issues/12676)。

另外，之前考虑过 [PDF 导出](https://github.com/b3log/solo/issues/12636)，但实现上有技术难点不好解决（Word 导出估计也有类似问题），所以暂时放弃了。

感谢反馈，如果有建议意见欢迎进一步讨论，我先关闭该  issue 了。
