### ISSUE TITLE
评论中的 Emoji 使用原始字符

### ISSUE THREAD

**Issue by zjhch123** [b3log/solo#12778]
### 描述问题

在文章评论中的部分emoji表情在移动端会出现乱码。如❤️(目前只发现这个爱心表情的问题)

### 重现步骤

在任意一篇文章中回复❤️表情，在移动端可见乱码。

不管是使用vditor添加的表情，还是系统输入法输入的表情，都会出现乱码。

### 截屏或录像

next皮肤:
<img src="https://image.hduzplus.xyz/image/1557494708514.jpg" width="400">

Pinghsu皮肤:
<img src="https://image.hduzplus.xyz/image/1557494801260.jpg" width="400">

### 服务器环境

 - Device: macOS 10.14
 - MySQL: 5.7.22 

建库语句: 
```mysql
create database solo default charset=utf8mb4;
```

MySQL字符编码:
```shell
mysql> show variables like '%char%';
+--------------------------+-----------------------------------------------------------+
| Variable_name            | Value                                                     |
+--------------------------+-----------------------------------------------------------+
| character_set_client     | utf8mb4                                                      |
| character_set_connection | utf8mb4                                                      |
| character_set_database   | utf8mb4                                                    |
| character_set_filesystem | binary                                                    |
| character_set_results    | utf8mb4                                                      |
| character_set_server     | utf8mb4                                                    |
| character_set_system     | utf8                                                      |
| character_sets_dir       | /usr/local/mysql-5.7.22-macos10.13-x86_64/share/charsets/ |
+--------------------------+-----------------------------------------------------------+
8 rows in set (0.00 sec)
```

### 移动端环境

- Device: iPhone7
- OS: iOS 12.2
- Browser: Wechat / Safari
- Version: solo 3.6.0

### 其他信息

本地刚刚跑起来的solo，使用的官方皮肤，没有添加任何奇怪的代码，没有进行任何魔改

**Comment by zjhch123** [comment]
应该是这里的问题

<img src="https://image.hduzplus.xyz/image/1557495348154.png" width="600">

**Comment by zjhch123** [comment]
好像那个冒号也不是中文的冒号，复制出来看像是一个非常奇怪的字符😅

**Comment by 88250** [comment]
编辑预览的时候能看出乱码么？

**Comment by Vanessa219** [comment]
PC 端有这个情况么？ 其他 emoji 有这个问题么？

**Comment by zjhch123** [comment]
编辑预览看不出，pc端没有这个情况。其他emoji我没有试过…迟点试一试…

**Comment by zjhch123** [comment]
这里是vditor支持的emoji表情(从这里找到的[src/ts/emoji/allEmoji.ts](https://github.com/b3log/vditor/blob/master/src/ts/emoji/allEmoji.ts))

<img width="400" alt="4" src="https://user-images.githubusercontent.com/12215513/57570640-d3ae9200-7436-11e9-9b01-e8fd23388056.png">
<img width="400" alt="1" src="https://user-images.githubusercontent.com/12215513/57570636-d0b3a180-7436-11e9-8df2-e27cc9e921d9.png">
<img width="400" alt="2" src="https://user-images.githubusercontent.com/12215513/57570638-d315fb80-7436-11e9-8b04-a629963738ec.png">
<img width="400" alt="3" src="https://user-images.githubusercontent.com/12215513/57570639-d3ae9200-7436-11e9-8ae9-79d8b84dd902.png">

好像就爱心有问题 @Vanessa219

**Comment by zjhch123** [comment]
<img width="500" alt="111" src="https://user-images.githubusercontent.com/12215513/57570816-eaee7f00-7438-11e9-82b9-15fb8c34e0a1.png">

这是在评论一个爱心的时候抓的包，如果把爱心后面的框框删掉再提交的话移动端显示正常

**Comment by Vanessa219** [comment]
请问一下在 https://hacpai.com/article/1511015097370/comment/1557633972320?r=Vanessa 或该评论中是否显示正常

❤️ ♥️

**Comment by zjhch123** [comment]
@Vanessa219 没有问题诶

**Comment by 88250** [comment]
那应该可以确定就是输入时带入的了？

@zjhch123 请帮忙在社区上输入测试一下，用这篇帖子 https://hacpai.com/article/1534385295613

**Comment by Vanessa219** [comment]
@zjhch123 呃，hacpia 和 solo 用的是同一个编辑器，用 iPhone 输入及查看都没有的问题莫非是 @88250 在后端悄悄的处理了什么？

**Comment by zjhch123** [comment]
社区里输入的、复制的爱心都没问题，输入预览里的也都没有问题诶

还有一点我发现在solo里，如果是通过选择vditor里的表情输入的，就会有乱码；如果是按照`:heart:`输入的就不会有乱码

很神奇…

**Comment by 88250** [comment]
> @zjhch123 呃，hacpia 和 solo 用的是同一个编辑器，用 iPhone 输入及查看都没有的问题莫非是 @88250 在后端悄悄的处理了什么？

没处理。从 @zjhch123 的重现步骤上看应该是前端带入的。

**Comment by Vanessa219** [comment]
@zjhch123 是通过点击这里进行输入的么？ 

![image](https://user-images.githubusercontent.com/970828/57756477-ec17f880-7725-11e9-96f7-1926eca7b646.png)

**Comment by zjhch123** [comment]
> @zjhch123 是通过点击这里进行输入的 Solo 就有问题，社区没有问题？
> 
> ![image](https://user-images.githubusercontent.com/970828/57756477-ec17f880-7725-11e9-96f7-1926eca7b646.png)

是的。而且，用系统(iOS)自带的输入法输入这个爱心符号提交到 Solo 也会有问题。

**Comment by 88250** [comment]
麻烦把这个字符拷贝一个给我。（可以用 txt 保存打包一下上传）

**Comment by zjhch123** [comment]
[heart.zip](https://github.com/b3log/solo/files/3183217/heart.zip)

@88250 喏~

**Comment by 88250** [comment]
谢谢，问题定位到是由于依赖的 [Java Emoji 库](https://github.com/vdurmont/emoji-java)在转换表情 Unicode 到 ASCII（:heart:）时有 bug。社区那边没有转换，直接保存的是原始字符所以没有问题。

Solo 这边文章正文也是保存原始字符，但评论做了一个转换，至于为啥要做这个转换我也不记得了 :joy: 目前情况来看可以移掉转换，直接存原始表情字符，这样就不存在该问题了。

这个版本先这样修复，如果以后遇到问题再说。
