### ISSUE TITLE
函数式调用的时候，映射方法异常，无法找到impl  

### ISSUE THREAD

**Issue by xfkkx** [b3log/solo#12772]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[讨论区](https://hacpai.com/tag/solo)搜寻资料解决问题。

----

### 描述问题

请尽量清晰精准地描述你碰到的问题。

### 重现步骤

请描述如何重现这个问题：

2. Click on '...'
3. Scroll down to '...'

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 桌面端环境

- OS: [e.g. windows, mac, linux]

### 移动端环境

- Device: [e.g. iPhone8]
- OS: [e.g. iOS12]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
麻烦提供一下 JDK 版本、Servlet 容器版本等相关细节信息。

**Comment by xfkkx** [comment]
java version "1.8.0_152"

servlet 工程中自带的start






chi.he@howbuy.com
 
发件人： D
发送时间： 2019-04-30 14:31
收件人： b3log/solo
抄送： xfkkx; Author
主题： Re: [b3log/solo] 函数式调用的时候，映射方法异常，无法找到impl (#12772)
麻烦提供一下 JDK 版本、Servlet 容器版本等相关细节信息。

**Comment by xfkkx** [comment]
chi.he@howbuy.com
 
发件人： D
发送时间： 2019-04-30 14:31
收件人： b3log/solo
抄送： xfkkx; Author
主题： Re: [b3log/solo] 函数式调用的时候，映射方法异常，无法找到impl (#12772)
麻烦提供一下 JDK 版本、Servlet 容器版本等相关细节信息。

**Comment by 88250** [comment]
有可能是 IDE 配置导致 JDK 不是所需的版本，可以用 `mvn jetty:run` 启动看看。

**Comment by xfkkx** [comment]
chi.he@howbuy.com
 
发件人： D
发送时间： 2019-04-30 15:49
收件人： b3log/solo
抄送： xfkkx; Author
主题： Re: [b3log/solo] 函数式调用的时候，映射方法异常，无法找到impl (#12772)
有可能是 IDE 配置导致 JDK 不是所需的版本，可以用 mvn jetty:run 启动看看。
