### ISSUE TITLE
关于solo 中标签与分类的关系的问题.

### ISSUE THREAD

**Issue by Michael-Scofield** [b3log/solo#12775]
维护者好. 我在看 solo 的设计时, 感觉通过归类标签来自动完成对文章的分类是个很棒的想法. 不过些地方不是很明白:

1. 存在关联表 tag_article. 但是在 article 中还是发现了 tags(英文分隔的多个标签 id)这个字段. 这样二者不就重复了么? 关联表也就没啥意思意义了吧.
2. 标签和分类是一对一还是多对一呢? 我的理解是, 给出了关联表, 那么说明应该是多对一的. 对吧?

**Comment by 88250** [comment]
你好，感谢对 Solo 的支持和关注。

1. tag_article 关联表是为了渲染标签-文章列表准备的，这样才能展示标签相关的文章。article 中单独存了 tag titles 是为了性能考虑，在渲染文章时不用多查（或者 join）一次关联表
2. 标签和分类是多对多，一个标签可以属于多个分类，一个分类可以包含多个标签

还有问题随时讨论，我先关闭 issue 了。
