### ISSUE TITLE
docker部署访问出现latke配置错误，这个改怎么解决？

### ISSUE THREAD

**Issue by ALonelyWanderingMind** [b3log/solo#12789]

**Comment by 88250** [comment]
请带参配置域名，具体请看页面提示那篇文档，谢谢。

**Comment by ALonelyWanderingMind** [comment]
配置了域名是因为域名还在审核阶段的原因吗？非常感谢大佬这么快解答我的问题。

**Comment by 88250** [comment]
打开浏览器 F12 看下网络请求就知道原因了。

**Comment by GitHubtianjingle** [comment]
请问，必须要配置成域名吗？浏览器报域名无法解析net::ERR_NAME_NOT_RESOLVED

**Comment by 88250** [comment]
> 请问，必须要配置成域名吗？浏览器报域名无法解析net::ERR_NAME_NOT_RESOLVED

IP 也可以。
