### ISSUE TITLE
通过域名访问主页后点击链接跳转到IP

### ISSUE THREAD

**Issue by jiangqiang96** [b3log/solo#12780]
首页某些链接点击之后会通过IP进行访问，使用的是Tomcat容器+Nginx进行部署，部署成功后发现首页标题栏上的任何链接点击之后，域名都会被跳转为IP，手动修改了数据库中用户的URL才解决问题。数据库中URL不知道为什么是存的IP地址。

**Comment by 88250** [comment]
用户 URL 是根据访问时候的配置持久化入库的，可能是因为之前 latke.props 的配置不是域名导致。

**Comment by jiangqiang96** [comment]
请问如何解决啊。我把能设置域名的地方都改了。但是我看见前端静态页面里面都是写的IP。

**Comment by 88250** [comment]
* 用 docker 部署的话带启动参数设置域名
* 用 war 部署的话直接改 latke.props
