### ISSUE TITLE
tomcat

### ISSUE THREAD

**Issue by hsBoysLove** [b3log/solo#12791]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

请尽量清晰精准地描述你碰到的问题。

### 重现步骤

请描述如何重现这个问题：

2. Click on '...'
3. Scroll down to '...'

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 桌面端环境

- OS: [e.g. windows, mac, linux]

### 移动端环境

- Device: [e.g. iPhone8]
- OS: [e.g. iOS12]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
你好，有问题的话请写清楚问题描述，谢谢。

**Comment by hsBoysLove** [comment]
![image](https://user-images.githubusercontent.com/41679338/58849429-e0807780-86bc-11e9-9ecd-eaf0f038ee59.png)

**Comment by hsBoysLove** [comment]
![image](https://user-images.githubusercontent.com/41679338/58849462-01e16380-86bd-11e9-8184-96908e0663cd.png)

**Comment by hsBoysLove** [comment]
需要我自己建数据库建表吗大佬

**Comment by hsBoysLove** [comment]
![image](https://user-images.githubusercontent.com/41679338/58849693-ee82c800-86bd-11e9-8bb5-53686a678e02.png)
![image](https://user-images.githubusercontent.com/41679338/58849705-fb9fb700-86bd-11e9-8e9b-01008eddd145.png)
我是小白,请大佬指点一下,怎么在浏览器初始化

**Comment by 88250** [comment]
打开浏览器访问 8080 端口。

**Comment by hsBoysLove** [comment]
![image](https://user-images.githubusercontent.com/41679338/58849834-9d270880-86be-11e9-8949-6e17cf2378fd.png)好了大佬,但是我想问下,我能不能把这套系统迁移到我自己的服务器上,不想与github牵连可以吗

**Comment by 88250** [comment]
可以的，请自行修改源码，开发方面可参考 [Solo 开发指南](https://hacpai.com/article/1493822943172)。

**Comment by hsBoysLove** [comment]
好的,谢谢大佬,,我是做Android的,挑战下自己哈哈,谢谢啦

**Comment by TealerProg** [comment]
话说我也是做安卓的

**Comment by 88250** [comment]
对了，另外可以考虑使用这款产品 https://github.com/halo-dev/halo 它没有和 GitHub 耦合。

**Comment by hsBoysLove** [comment]
哈哈握爪,我是做了接近4年的Android,一直想搭建个自己的博客,前一阵子自己买了服务器,本来自己写的一些简单接口,但是无奈不熟悉前端页面写法,感觉很丑,所以先看看成熟的系统怎么做的

**Comment by hsBoysLove** [comment]
> 话说我也是做安卓的

哈哈握爪,我是做了接近4年的Android,一直想搭建个自己的博客,前一阵子自己买了服务器,本来自己写的一些简单接口,但是无奈不熟悉前端页面写法,感觉很丑,所以先看看成熟的系统怎么做的

**Comment by hsBoysLove** [comment]
> 话说我也是做安卓的

哈哈握爪,我是做了接近4年的Android,一直想搭建个自己的博客,前一阵子自己买了服务器,本来自己写的一些简单接口,但是无奈不熟悉前端页面写法,感觉很丑,所以先看看成熟的系统怎么做的

**Comment by TealerProg** [comment]
> > 话说我也是做安卓的
> 
> 哈哈握爪,我是做了接近4年的Android,一直想搭建个自己的博客,前一阵子自己买了服务器,本来自己写的一些简单接口,但是无奈不熟悉前端页面写法,感觉很丑,所以先看看成熟的系统怎么做的

共勉，共勉，一起学习，多交流

**Comment by hsBoysLove** [comment]
> 对了，另外可以考虑使用这款产品 https://github.com/halo-dev/halo 它没有和 GitHub 耦合。

了解,先研究下,一直做Android,对后端不熟悉,研究下,谢谢大佬
