### ISSUE TITLE
要是分类可以分层级就完美了

### ISSUE THREAD

**Issue by denghui1010** [b3log/solo#12793]
### 你在什么场景下需要该功能？
写系列文章的时候, 可能需要带层级的分类

请尽量清晰精准地描述你碰到的问题。

### 描述可能的解决方案

请尽量清晰精准地描述你期待我们要做的，描述你想到的实现方案。

### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

### 其他信息
参考像jpress类似的分类

请提供关于该功能建议的其他附加信息。

**Comment by 88250** [comment]
你好，信息架构方面我们考虑的是标签扁平化并通过分类进行聚合，相关的细节介绍和设计考量请看这里：[Solo 标签聚合分类](https://hacpai.com/article/1558320086126)。
