### ISSUE TITLE
【提案】优先使用社区提供的 Markdown 接口

### ISSUE THREAD

**Issue by 88250** [b3log/solo#12792]
为了保证最好的渲染效果，优先使用社区提供的 Markdown 渲染接口，如果调用失败再使用内建或者本地的 md 渲染服务。

目前本 issue 还在意见征求阶段，欢迎大家参与讨论。

**Comment by AdlerED** [comment]
只要稳定，能调用最新的Markdown接口当然赞同，社区宕了也可以本地，没毛病。

**Comment by JinJianh** [comment]
这样弄的话，博客的文章同步到社区就会出现格式问题，我之前就遇到了

**Comment by 88250** [comment]
> 这样弄的话，博客的文章同步到社区就会出现格式问题，我之前就遇到了

所以本提案就是为了解决这个问题诞生的，统一使用社区接口进行渲染避免格式一致性问题。

**Comment by 88250** [comment]
看来大家不是太需要，先关闭了。
