### ISSUE TITLE
使用 MySQL 时不启用 SQL 导出功能

### ISSUE THREAD

**Issue by gitldy1013** [b3log/solo#12806]
### 描述问题
Docker方式启动时musqldump报错，因为solo应用和数据库服务不在一个容器 导致报错

### 重现步骤

点击后台管理 工具->其他->数据导出->导出sql文件报错

### 期待的结果

提供一个官方的solo应用镜像 并内置mysql服务完美解决

**Comment by 88250** [comment]
感谢反馈，如果用 `docker exec mysql mysqldump`  作为导出命令你认为可行么？

**Comment by gitldy1013** [comment]
个人认为不可行 这种方式我尝试过 因为按钮触发后的操作实在docker容器内执行的 docker容器内无法执行容器外命令和其他容器命令 环境变量不同 个人想过合并容器或者镜像 不过结果其实都是在一个容器内封装了数据库服务 我想到最好的解决办法可能是在solo应用容器内安装mysqlclient执行mysqldump并指定host（容器）我本地尝试了一下但是改的东西太多 每次solo升级做的工作太多了 所以提了这个建议

**Comment by 88250** [comment]
嗯，我忽略这本身就是 docker 进程这一点了 😂 
我想了下，在后台手工执行导出 SQL 其实设计上也不大合理，导出其他格式可以有，但是导出数据库 SQL 还是通过 Solo 本身以外的运维手段解决吧。干脆把这个功能砍了？

**Comment by gitldy1013** [comment]
嗯 我感觉也可以 mysql的方式可以砍掉这个功能 H2因为不涉及单独的数据库服务个人感觉还是可以保留 我现在用的就是H2 感觉挺实用的 mysql一般我都用sqlyog等工具直接导出即可 这个操作也不是很频繁

**Comment by 88250** [comment]
👌 下个版本（v3.6.3）如果使用 MySQL 的话将从 UI 上隐藏这个功能，如果使用 H2 的话保持不变。
