### ISSUE TITLE
标签中含有#号时无法保存

### ISSUE THREAD

**Issue by hysong00** [b3log/solo#12802]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

在发布文章时，如果标签选择C# 或者F#等带#号的字符时，标签展示为待分类。

### 重现步骤

请描述如何重现这个问题：

1. 进入发布文章页面
2. 编辑文章后，标签选择 **C#**
3. 点击发布按钮
4. 发布后的文章标签为 **待分类**

### 期待的结果

C# 标签正常展示

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 桌面端环境

- OS: Windows
- Browser Chrome FireFox Edge
- Version Solo 3.6.2

### 移动端环境

- Device: [e.g. iPhone8]
- OS: [e.g. iOS12]

### 其他信息

正则表达式匹配的问题，TAG_TITLE_PATTERN_STR 无法匹配带#号的字符

**Comment by 88250** [comment]
感谢反馈，已经修复。Docker 镜像正在构建中，请再过 30 分钟左右尝试 pull。
