### ISSUE TITLE
新皮肤 Bubble

### ISSUE THREAD

**Issue by Vanessa219** [b3log/solo#12805]
参考：https://www.cnblogs.com/jajian

https://github.com/b3log/solo/issues/12449

**Comment by lizhongyue248** [comment]
新皮肤太好看啦～！已经用上了，V 姐记得给移动端加一下 目录嚄～

还有就是 markdown 文章中使用 `[TOC]` 目录的时候，点击她，url 会有锚点但是滚动不下去，锚点为标题名称，这个问题能解决嘛？看了下右侧的锚点都是类似于 `b3_solo_h3_5` 这种的，好像不太好跳转。

**Comment by Vanessa219** [comment]
收到，发站点我看看，我本地可以点的。

**Comment by Vanessa219** [comment]
@lizhongyue248 移至 https://github.com/b3log/solo/issues/12814
