### ISSUE TITLE
docker 启动没有响应

### ISSUE THREAD

**Issue by adongs** [b3log/solo#12801]
![image](https://user-images.githubusercontent.com/17808661/59742115-757b9700-929f-11e9-9550-805c36636198.png)
发现只启动监听端口,访问端口没有启动

**Comment by adongs** [comment]
访问
![image](https://user-images.githubusercontent.com/17808661/59742199-a52a9f00-929f-11e9-9411-108961ce87e6.png)

**Comment by 88250** [comment]
Docker 端口已经映射到外网可访问的端口了吗？或者防火墙阻止访问等原因？

**Comment by 88250** [comment]
已经解决的话我关闭了，如果还有问题就请跟帖，谢谢。
