### ISSUE TITLE
关闭内置 MD 引擎的 [TOC] 扩展

### ISSUE THREAD

**Issue by Vanessa219** [b3log/solo#12814]
新皮肤太好看啦～！已经用上了，V 姐记得给移动端加一下 目录嚄～

还有就是 markdown 文章中使用 `[TOC]` 目录的时候，点击她，url 会有锚点但是滚动不下去，锚点为标题名称，这个问题能解决嘛？看了下右侧的锚点都是类似于 `b3_solo_h3_5` 这种的，好像不太好跳转。

_Originally posted by @lizhongyue248 in https://github.com/b3log/solo/issues/12805#issuecomment-511176527_

**Comment by lizhongyue248** [comment]
不好意思才看到，文章见 https://echocow.cn/articles/2019/07/14/1563096109754.html

我在 markdown 中 添加了 `[TOC]` 生成了目录链接，点击的锚点是中文名称。

**Comment by Vanessa219** [comment]
你这个 TOC 目录是怎么生成的？

Solo 会自己生成目录

**Comment by lizhongyue248** [comment]
我记得使用默认的。。。。

因为希望用户一进来就可以看到目录，就直观明了。所以在 Markdown 使用 `[TOC]` 进行生成，且现在手机端没有目录所以加上了。

**Comment by Vanessa219** [comment]
md 使用 `[TOC]` 生成是个什么操作？

移动端现在已经有了，可以到 https://github.com/b3log/solo-skins 进行更新

**Comment by lizhongyue248** [comment]
这样的

![pic](https://resources.echocow.cn/file/2019/07/18/%E6%B7%B1%E5%BA%A6%E6%88%AA%E5%9B%BE_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20190718172641.png)

**Comment by 88250** [comment]
@lizhongyue248 你使用的是 Solo 内置的渲染引擎还是 [markdown-http](https://github.com/b3log/markdown-http)？

**Comment by Vanessa219** [comment]
哦，我明白了。 @88250 要么你把这个功能关了，要么和你生成的 toc 统一一下

**Comment by 88250** [comment]
那就关掉内置 flexmark 的 `[TOC]` 扩展的渲染吧，和目录插件的功能有重叠。

**Comment by 88250** [comment]
另外，之前是启用了 flexmark 的全部扩展，其实没这必要。稍后会调整扩展设置，只要实现 GFM 就可以了。
