### ISSUE TITLE
 Check tables failed

### ISSUE THREAD

**Issue by V3kb** [b3log/solo#12819]
[ERROR]-[2019-07-21 21:17:21]-[org.b3log.solo.service.InitService:186]: Check tables failed, please make sure database existed and database configuration [jdbc.*] in local.props is correct [msg=Communications link failure

**Comment by 88250** [comment]
你好，日志显示数据库连接失败，请检查相关配置。

**Comment by V3kb** [comment]
我用本地数据库软件可以连接，已经创建了数据库，但是用docker部署启动就报错。

**Comment by 88250** [comment]
可以启动一个 alpine 镜像系列的容器，然后在容器内看下能否连通寄主机的 MySQL，网络模式记得用 host。

另外还有一个主意是通过 Docker Compose 拉起相关容器进程，具体请参考 https://github.com/liumapp/solo-in-docker

**Comment by V3kb** [comment]
Latke Configuraton Error? 环境配置好了，打开浏览器报这个错误。

**Comment by 88250** [comment]
请参考[这里](https://hacpai.com/article/1474087427032)。
