### ISSUE TITLE
迁移博客到solo之后想设置博客浏览量

### ISSUE THREAD

**Issue by panjf2000** [b3log/solo#12820]
### 你在什么场景下需要该功能？

我以前用的是其他的博客系统搭建的个人博客，后来那个作者不更新了，就想迁移原来的博客，后来发现了solo，觉得它很强大，就迁移过来了，文章、标签什么的我都自己写脚本迁移到solo博客了，但现在有一个问题，就是新的博客的总浏览量（因为是刚搭建的），所以我想把以前我的旧的博客的浏览量加到solo这里。

### 描述可能的解决方案

看了下DB以及粗略搜了下源码，没找到博客总浏览量存储在哪里，所以我猜是嵌入的第三方脚本统计的？想问下有没有办法可以改这个值？我觉得这个迁移博客总浏览量的需求还是有点用的，毕竟迁移的新的博客就丢了以前的浏览量对博主来说感觉挺心疼的，这可能也是阻止新用户把博客迁移到solo的一个不大不小的潜在blocker吧。

### 其他信息
最后，谢谢作者提供了一个这么强大的博客系统！

请提供关于该功能建议的其他附加信息。

**Comment by 88250** [comment]
你好，文章浏览量在 article 表中；博客总浏览量在 option 表中。具体表结构可以参考[这里](https://hacpai.com/article/1537694566175)。

另外，迁移数据如果原博客系统支持导出 Markdown 文件的话，可以将导出的 Markdown 文件导入 Solo，这样标签、日期存档等都会自动处理，在最大程度上进行还原。在不是非常熟悉数据结构和处理逻辑的前提下不建议直接对数据库进行操作，这样可能会留下潜在的一致性问题。

感谢使用。
