### ISSUE TITLE
增加是否从 GitHub 拉取信息生成导航的开关

### ISSUE THREAD

**Issue by JinJianh** [b3log/solo#12825]
### 在设置里面新增一个是否从 GitHub 拉取信息生成导航的开关

1. 并不是所有人都想展示自己的开源项目（想展示就打开，不想展示就关闭）
2. 像我这种没啥开源项目的，这一页就显得比较尴尬

**Comment by AlgerFan** [comment]
提的倒是挺快的 @JinJianh

**Comment by 88250** [comment]
感谢建议，我们会在下个版本中加入这个开关，默认开启。

**Comment by JinJianh** [comment]
> 提的倒是挺快的@JinJianh

正好闲着

**Comment by TravelEngineers** [comment]
期待该功能，不想每次pull最新版的加入github介绍。

**Comment by 88250** [comment]
另外，[导出文章到 GitHub 仓库](https://github.com/b3log/solo/issues/12676)会改为默认开启，这个功能默认开启的话可以帮助用户备份数据。
