### ISSUE TITLE
订阅输出改进

### ISSUE THREAD

**Issue by JinJianh** [b3log/solo#12826]
![image](https://user-images.githubusercontent.com/23192332/61775393-76b65b80-ae2b-11e9-8d32-81160366b111.png) 
这是社区订阅的样子

![image](https://user-images.githubusercontent.com/23192332/61775544-b54c1600-ae2b-11e9-9ed6-0637047cac63.png)
这是D的博客订阅的样子（当然我的也是一样)

**Comment by 88250** [comment]
Solo 用了实体转义，稍后进行一下改进，社区那种比较好一些。

**Comment by iTanken** [comment]
![image](https://user-images.githubusercontent.com/23544702/62007229-801e2b80-b17d-11e9-9553-3a194454f38c.png)
为什么我的没有转义？（3.6.1）

**Comment by 88250** [comment]
description 没有用 `<![CDATA[....]]>` 处理会有安全问题，估计是浏览器发现后自动转成 HTML 实体来避免安全问题了。

v3.6.4 会修复这个问题，谢谢反馈。
