### ISSUE TITLE
JDK11 插件加载报错

### ISSUE THREAD

**Issue by Miracle-Liu** [b3log/solo#12824]
### 截屏或录像

![image](https://user-images.githubusercontent.com/28992105/61694797-cf6ef100-ad64-11e9-9605-0866d66db664.png)

### 其他信息

Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 23:22:22+0800)
Maven home: D:\Program Files\apache-maven-3.1.1\bin\..
Java version: 11.0.4, vendor: AdoptOpenJDK
Java home: C:\Program Files\AdoptOpenJDK\jdk-11.0.4.11-hotspot
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"

**Comment by 88250** [comment]
你好，我这边目前暂时没有这个 JDK 环境去验证问题，稍后我安装好环境以后再进行重现测试。
感谢反馈。

**Comment by Miracle-Liu** [comment]
好的，感谢




------------------ Original message ------------------
From: "D"; 
Sendtime: Tuesday, Jul 23, 2019 4:55 PM
To: "b3log/solo"; 
Cc: "残星、点点"<1107650503@qq.com>; "Author"; 
Subject: Re: [b3log/solo] 项目启动报错 (#12824)




你好，我这边目前暂时没有这个 JDK 环境去验证问题，稍后我安装好环境以后再进行重现测试。
 感谢反馈。

**Comment by 88250** [comment]
确认是 Latke 框架插件加载的 bug，已经进行修复。Solo v3.6.4 会更新到最新版框架进而修复这个问题。

**Comment by Miracle-Liu** [comment]
收到。




------------------ Original message ------------------
From: "D"; 
Sendtime: Monday, Jul 29, 2019 10:27 AM
To: "b3log/solo"; 
Cc: "残星、点点"<1107650503@qq.com>; "Author"; 
Subject: Re: [b3log/solo] JDK11 插件加载报错 (#12824)




确认是 Latke 框架插件加载的 bug，已经进行修复。Solo v3.6.4 会更新到最新版框架进而修复这个问题。
