### ISSUE TITLE
分类无法添加超过 4 个标签

### ISSUE THREAD

**Issue by panjf2000** [b3log/solo#12821]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

你好，我在管理后台设置博客分类的时候，往分类里加标签的时候，发现往一个分类里加了很多标签之后最后提交，然后发现每次一个分类里只会剩下最多四个，超过四个后面的标签就没有了，我去查了下数据库，的确是只有四个标签。

在黑客派论坛没搜到相关的帖子，一开始我以为是逻辑限制，然后看了下新增category的源码，貌似没有看到这个逻辑，然后我又看到别人用solo搭的博客的分类里有超过四个的，所以我想请问下这可能是什么原因导致的？

### 重现步骤

请描述如何重现这个问题：

1. 进入solo后台管理，点击`分类管理`tab；
2. 新增分类，选择添加标签，添加超过四个；
3. 点击`保存`；
4. 在上方选择刚刚新建的分类，看到只有最多四个标签。

### 期待的结果
我看到别人的solo博客里有超过四个标签的，有十几个、几十个，所以我想应该是我的数据哪里有问题吧，想问下怎么fix它，然后可以在分类里添加超过四个标签，谢谢。

### 截屏或录像
![2019-07-22 101441](https://user-images.githubusercontent.com/7496278/61601777-8a19c900-ac69-11e9-8a62-ca4b2aef1c83.gif)

### 桌面端环境

- OS: [MacOS]
- Browser [Chrome]
- Version [75.0.3770.100]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
源码已经在 master 上进行修复；目前正在做 Solo 的 Docker 镜像更新，过 30 分钟左右 docker pull 应该就可以了。

感谢反馈 ❤️
