### ISSUE TITLE
增加设置首页文章排序方式的选项

### ISSUE THREAD

**Issue by AlgerFan** [b3log/solo#12837]
排序方式可以用两种：
1.按发布时间排序
2.按更新时间排序
毕竟有时候想让别人看到的是新文章

**Comment by 88250** [comment]
你好，请看下后台`偏好设定 -> 参数设置 -> 启用文章更新提示`是否已经勾选，理论上如果勾选的话首页文章列表排序就是按更新时间排序了。

**Comment by AlgerFan** [comment]
好的，了解了

**Comment by TerickJojo** [comment]
勾选`启用文章更新提示`后，文章标题旁边会出现`有更新`字样，点击文章进去之后这几个字仍然不会消失，看着很难受。。。
希望能改进，比如点击文章阅读后，主页的文章标题旁`有更新`几个字会消失。
另外还希望有个小功能，最新更新日期的字样可以显示在主页文章标题下方（不是发布日期）。
十分感谢！

**Comment by 88250** [comment]
@TerickJojo 收到，稍后我们调整一下。

@Vanessa219

**Comment by Vanessa219** [comment]
@TerickJojo 可以理解为这样么 https://github.com/b3log/solo/issues/12842 ？

**Comment by TerickJojo** [comment]
应该是这样的

- 列表页面新增更新时间字样并且自动排序上移至顶端（主页）
- 启用更新提示后，列表页面显示“有更新”字样，点击浏览之后“有更新”字样消失（主页）
- 启用更新提示后，文章页面不显示“有更新”字样

@Vanessa219 麻烦啦

**Comment by Vanessa219** [comment]
@TerickJojo 列表上一般只放一个时间，新增更新时间可能太挤了，但可以统一为更新时间。排序的话现在有更新的会排在顶端的，是排序出现 bug 了么？

**Comment by TerickJojo** [comment]
启用更新提示后，排序是正常的，最新更新的文章会自动上移，这没问题。

关于更新时间的问题，因为我用的皮肤是Bubble的，文章列表（主页）是不显示任何时间的
![image](https://user-images.githubusercontent.com/24235319/61992327-9c9d5500-b011-11e9-81b7-1711565f889d.png)
所以我才说要增加更新时间，可能这是皮肤的问题吧。
@Vanessa219

**Comment by Vanessa219** [comment]
收到
