### ISSUE TITLE
皮肤yilia优化建议

### ISSUE THREAD

**Issue by TravelEngineers** [b3log/solo#12843]
### 描述问题

皮肤yilia中自定义的导航菜单能否改成三个一行的，现在一行一个，自定义菜单就只能放2个。同时，如果公告不填写内容的话，博客的副标题也不会显示出来。建议优化下哈。

### 重现步骤

请描述如何重现这个问题：

1. 多设置几个自定义导航栏会在768分辨率的时会排版错乱。

### 期待的结果

自定义导航栏改成平铺的，每行至少可以放2个，节省一下空间。

### 截屏或录像

可以实际试一下。

### 桌面端环境

win7 64位 360极速浏览器极速模式
### 移动端环境

无

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by Vanessa219** [comment]
收到

**Comment by Vanessa219** [comment]
考虑到自定义导航可能过长，现在如果超出的话，会使用滚动来进行操作
