### ISSUE TITLE
是否增加更多markdown语言高亮支持

### ISSUE THREAD

**Issue by AlgerFan** [b3log/solo#12845]
markdown不支持shell高亮，我还去翻阅了vditor支持的语言，发现并不多，之后会加上更多语言的代码高亮吗？

**Comment by 88250** [comment]
bash 是支持的：

````
```bash
#!/bin/bash

echo "Let's play a solo"
```
````

内置的主流语言应该都支持，如果还需要支持更多可以到 Vditor 项目上提，感谢反馈。
