### ISSUE TITLE
存档页增加 articles 变量

### ISSUE THREAD

**Issue by InkDP** [b3log/solo#12840]
昨天在开发皮肤时在`archives`页面使用`articles`变量时报错500；
经过测试发现`articles`只能在首页，分类，标签页使用，而`archives`只能使用一个时间列表，这大大限制了开发的自由度，希望能将一些变量变为全局的

**Comment by JinJianh** [comment]
这个呢

**Comment by 88250** [comment]
稍等会处理的，需要点时间....

**Comment by 88250** [comment]
v3.6.4 先发布了，这个需求在 v3.6.5 中实现。

**Comment by 88250** [comment]
考虑了下，因为存档不太适合放所有文章，可能会有性能问题，并且存档页也不支持分页，所以还是暂时不实现了。

也许以后会在某个适合的时机再回过头来考虑这个问题，现在先关闭了，谢谢建议。
