### ISSUE TITLE
rss订阅功能无法正常使用

### ISSUE THREAD

**Issue by washmore** [b3log/solo#12847]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

使用foxmail功能无法正常添加博客的rss连接,显示
`无法识别该地址,请检查输入的Rss地址是否正确.`

### 重现步骤

请描述如何重现这个问题：
solo3.6.1
foxmail7.2 build11.303
添加rss地址:[https://blog.washmoretech.com/rss.xml](https://blog.washmoretech.com/rss.xml)失败.

### 期待的结果

正常添加rss源并阅读

### 截屏或录像

![image](https://user-images.githubusercontent.com/13030698/62445095-0647fc80-b792-11e9-9d2d-fd222fc25df6.png)

### 桌面端环境

- OS: win10
- Browser chrome69
- Version 3.6.1

**Comment by 88250** [comment]
感谢反馈，这个问题和 https://github.com/b3log/solo/issues/12826 中的问题可能是一个，会在 v3.6.4 中进行修复。

目前 master 和 docker 镜像已经发布，可以一试，谢谢！

**Comment by 88250** [comment]
对了，可以用你截图的工具试下 https://88250.b3log.org/rss.xml 如果可以的话说明应该已经修复了。

**Comment by washmore** [comment]
这个链接可以正常解析;
我这就去升级
