### ISSUE TITLE
文章聚合分类分页问题

### ISSUE THREAD

**Issue by InkDP** [b3log/solo#12859]
制作皮肤是为了测试分页，我设置了每页显示两篇文章
1. 我的分类《杂谈与随笔》下有两篇文章“未来的路”与“《追风筝的人》阅读笔记”
2. “关于我”页面存储与草稿夹里面，但是也属于《杂谈与随笔下》
3.  分类-杂谈与随笔应该显示的是:关于我”与“《追风筝的人》阅读笔记”这两篇文章，现在第一页直接什么都没有了，第二页显示了“未来的路”

**Comment by 88250** [comment]
“未来的路”是另一篇属于这个分类的文章吗？

**Comment by JinJianh** [comment]
> “未来的路”是另一篇属于这个分类的文章吗？

《杂谈与随笔》下共三篇文章“《追风筝的人》阅读笔记”“未来的路”“关于我（草稿夹）”

**Comment by 88250** [comment]
好的，这个问题我大概知道原因了，后面会尝试进行修复。
感谢反馈！

**Comment by JinJianh** [comment]
> 好的，这个问题我大概知道原因了，后面会尝试进行修复。
> 感谢反馈！

又发现一个，在前端分类下，总共就一篇文章，也出现了两页，两页一模一样

**Comment by 88250** [comment]
嗯，导致问题的原因应该是同一个。

**Comment by Vanessa219** [comment]
@88250 还需要该分类下的文章数

**Comment by 88250** [comment]
> @88250 还需要该分类下的文章数

`${pagination.paginationRecordCount}`

**Comment by 88250** [comment]
@InkDP 
代码已经合并至 master，Docker 镜像估计需要 1 小时左右才能构建好。届时请拉取最新镜像，然后帮忙验证一下是否修复，感谢感谢 🙏
