### ISSUE TITLE
solo 博客跳转导航页面 404

### ISSUE THREAD

**Issue by panjf2000** [b3log/solo#12867]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题
在 solo 博客的作者文章页：https://domain/authors/1xxxxx, 点击在后台通过『导航管理』创建的页面会导致 404，期待的正确跳转url应该类似：https://domain/about, 结果是：https://domain/authors/about

### 重现步骤

请描述如何重现这个问题：

1. 点击文章列表页任意一个文章上的所属作者，跳转到类似：https://domain/authors/1xxxxx 这样的url；
2. 然后点击博客导航栏中的任意一个导航页面，比如『关于我』；
3. 页面 404。

### 期待的结果

在作者文章页点击其他导航页面能正确跳转。

### 截屏或录像

<img width="1230" alt="Screen Shot 2019-08-27 at 13 37 50" src="https://user-images.githubusercontent.com/7496278/63743806-02f6eb00-c8d0-11e9-847f-079b22871909.png">

### 桌面端环境

- OS: mac
- Browser：chrome
- Version: 76.0.3809.100, 64-bit

**Comment by Vanessa219** [comment]
配置时请如下使用完整的域名或者绝对路径
![image](https://user-images.githubusercontent.com/970828/63749063-33915180-c8dd-11e9-9a9c-040185fd52a7.png)
