### ISSUE TITLE
同步拉取 GitHub 失效

### ISSUE THREAD

**Issue by panjf2000** [b3log/solo#12864]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

在 solo 后台勾选了同步拉取 github 仓库，只更新了几次，后续就再没有更新了：
![image](https://user-images.githubusercontent.com/7496278/63653103-03419a00-c79b-11e9-8172-877eea2b22e6.png)

### 重现步骤

请描述如何重现这个问题：
1. 在 solo 后台的偏好设置里勾选自动拉取 github 仓库选项；
2. 没有每天更新。

### 期待的结果
能准时更新。

### 截屏或录像

![image](https://user-images.githubusercontent.com/7496278/63653120-4996f900-c79b-11e9-8021-69c8ed24881f.png)

### 桌面端环境

- OS: mac
- Browser chrome

### 移动端环境

- Device: [e.g. iPhone8]
- OS: [e.g. iOS12]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
能帮忙确认一下是拉取报错还是拉取后数据没变吗？拉取报错的话应该会有相关报错日志，如果没有错误日志的话估计是拉取了，但是数据没有变。

数据没有变的话可能是因为社区没有刷新数据，刷新数据的时机是每次通过 GitHub 登录社区或者手动[授权获取公开仓库数据](https://hacpai.com/settings/github)。

**Comment by panjf2000** [comment]
明天我进 docker 看下 log 确认下。

**Comment by panjf2000** [comment]
授权问题。

**Comment by panjf2000** [comment]
solo 博客的每日同步更新个人 github 仓库到博客的功能好像有点奇怪，不是每天更新，好像是很久更新一次，而且更新后的数据还不是最新的数据，https://taohuawu.club/my-github-repos

**Comment by panjf2000** [comment]
docker 的 logs 也没查到什么错误，还是我查的方法不对？关键字是什么？

**Comment by 88250** [comment]
这个功能依赖社区拉取仓库的数据，社区拉取仓库是在登录时刷新的。也就是说如果需要最新数据的话需要登录一次社区。

**Comment by panjf2000** [comment]
这有个问题，如果我登陆过社区了，这个 session 一直都在，那我要更新只能退出社区账号重新登陆一下？

**Comment by 88250** [comment]
老铁我之前说过了啊：

> 数据没有变的话可能是因为社区没有刷新数据，刷新数据的时机是每次通过 GitHub 登录社区或者手动[授权获取公开仓库数据](https://hacpai.com/settings/github)。

**Comment by panjf2000** [comment]
我知道，我是说这样的操作要一直重复？

**Comment by 88250** [comment]
目前如果需要更新仓库数据的话只能手动触发，稍后我再考虑一下怎么做定时刷新，主要难点是几万用户定时跑的话耗时太长 😂

**Comment by 88250** [comment]
方案我再想想，只考虑博客端用户的定时刷新应该还是能做的，感谢反馈了哈。

**Comment by panjf2000** [comment]
对，社区端如果没有合适的方案可以暂时保持这样，但是博客端我觉得可以做定时刷新。

**Comment by 88250** [comment]
现在社区已经改成博客端发起拉取请求后触发数据刷新操作。
