### ISSUE TITLE
皮肤 yilia 优化

### ISSUE THREAD

**Issue by panjf2000** [b3log/solo#12863]
### 你在什么场景下需要该功能？

solo 的皮肤 yilia 有一些体验不太好的地方：
1. 文章列表页没有显示浏览数和评论数；
![image](https://user-images.githubusercontent.com/7496278/63652883-23bc2500-c798-11e9-9c94-29e3cbd0e6c2.png)
2. 点击文章列表页显示的摘要图片是跳转到图片地址而非文章详细页，体验不太好；
3. 文章详情页左侧的文章目录 tab 样式有点问题，关闭按钮和目录第一个在同一行，如果目录文字比较长会和关闭按钮相互遮挡：
![image](https://user-images.githubusercontent.com/7496278/63652920-c379b300-c798-11e9-88b6-d91c871fa366.png)

### 描述可能的解决方案
我在 pipe 里看到的和这个皮肤相同样式的皮肤 Koma，并没有我上面描述的那几个问题，希望 solo 能在这个皮肤上和 pipe 保持一致：
1. 在文章列表页加上浏览数和评论数；
![image](https://user-images.githubusercontent.com/7496278/63652970-6d593f80-c799-11e9-9bcc-ff76cd69af55.png)

2. 文章列表页的摘要图片直接跳转文章详情页；
3. 让文章目录 tab 的关闭按钮独占一行；
![image](https://user-images.githubusercontent.com/7496278/63652978-7a762e80-c799-11e9-83f5-14c16d8a2026.png)

### 其他信息

pipe示例网站：http://pipe.b3log.org/blogs/TommyMerlin

**Comment by 88250** [comment]
感谢反馈，稍后处理。

**Comment by panjf2000** [comment]
另外一个问题，不仅限于这个皮肤，就是文章列表页上显示的 "文章发表日期" 都是更新日期，这个我觉得不太妥当，很容易造成混乱，我认为应该显示文章创建时间。

**Comment by 88250** [comment]
> 另外一个问题，不仅限于这个皮肤，就是文章列表页上显示的 "文章发表日期" 都是更新日期，这个我觉得不太妥当，很容易造成混乱，我认为应该显示文章创建时间。

工具 -> 偏好设定 -> 参数设置 中不要勾选 `启用文章更新提示` 应该就是创建时间了。

**Comment by panjf2000** [comment]
@88250 我没有勾选，但是依然显示的是更新时间。

**Comment by 88250** [comment]
@panjf2000 可能是我记错了了 😂  稍后一并排查。

**Comment by panjf2000** [comment]
@88250 嗯，谢谢~~

**Comment by 88250** [comment]
> 另外一个问题，不仅限于这个皮肤，就是文章列表页上显示的 "文章发表日期" 都是更新日期，这个我觉得不太妥当，很容易造成混乱，我认为应该显示文章创建时间，然后如果可能的话在文章底部加上更新时间。

刚才翻了下历史，都显示“更新时间”是一个才做不久的[变更](https://github.com/b3log/solo/issues/12842) 😂 

现在显示“文章发布日期”文案确实容易引起歧义，应该改为“最后更新日期” @Vanessa219

**Comment by Vanessa219** [comment]
@panjf2000 说的应该是文案和时间不符合。现在统一显示的是文章更新时间。

**Comment by Vanessa219** [comment]
时间文案参见 https://github.com/b3log/solo/issues/12868， 其余问题已修改
