### ISSUE TITLE
没有域名，Latke 配置错误问题

### ISSUE THREAD

**Issue by cr7mufc520** [b3log/solo#12877]
这是docker命令
`docker run --detach --name solo --network=host \
    --env RUNTIME_DB="MYSQL" \
    --env JDBC_USERNAME="root" \
    --env JDBC_PASSWORD="123456" \
    --env JDBC_DRIVER="com.mysql.cj.jdbc.Driver" \
    --env JDBC_URL="jdbc:mysql://127.0.0.1:3306/solo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC" \
    b3log/solo --listen_port=8080 --server_scheme=http --server_host=公网ip --server_port=`

遇到Latke 配置错误，该怎么修改？还有问一下，通过docker exec -it 容器id bash 怎么进入不了容器内部？谢谢
![ScreenClip](https://user-images.githubusercontent.com/50861832/64062447-ef71ba00-cc18-11e9-8540-b3faaa28d07a.png)
![ScreenClip2](https://user-images.githubusercontent.com/50861832/64062448-ef71ba00-cc18-11e9-9f2c-4077898beadc.png)

**Comment by 88250** [comment]
可以开 F12 看下网络请求。

**Comment by 88250** [comment]
我先关闭 issue 了，如果还有问题请随时跟帖，谢谢。
