### ISSUE TITLE
希望能支持插入目录[toc]

### ISSUE THREAD

**Issue by Leif160519** [b3log/solo#12872]
### 你在什么场景下需要该功能？

当文章比较长的时候，想增加文章内目录

**Comment by 88250** [comment]
目前 Markdown 渲染是使用 GFM 不支持其他扩展，目的是在最大程度上保持通用。所以暂时不会加入这个特性，谢谢理解和支持！

**Comment by Leif160519** [comment]
好的，了解。另外还有几个小问题也想顺便提一下，不知道可不可以改进：
1.粘贴已经处理好缩进的代码的时候，编辑页面会自动将代码顶格
2.粘贴代码或者表格的时候，文本内容中间都会新增一行空行

**Comment by Leif160519** [comment]
好的，了解。另外还有几个小问题也想顺便提一下：
1.粘贴已经处理好缩进的代码的时候，编辑页面会自动将代码顶格
2.粘贴代码或者表格的时候，文本内容中间都会新增一行空行

**Comment by 88250** [comment]
> 好的，了解。另外还有几个小问题也想顺便提一下：
> 1.粘贴已经处理好缩进的代码的时候，编辑页面会自动将代码顶格
> 2.粘贴代码或者表格的时候，文本内容中间都会新增一行空行

@Vanessa219

**Comment by Vanessa219** [comment]
@Leif160519 更新后看一下

**Comment by Leif160519** [comment]
好的，非常感谢，下个版本看看


| |
骆飞
|
|
yzluofei@126.com
|
签名由网易邮箱大师定制
在2019年8月30日 18:17，Vanesssa<notifications@github.com> 写道：

@Leif160519 更新后看一下
