### ISSUE TITLE
Markdown HTTP 渲染引擎切换为 Lute

### ISSUE THREAD

**Issue by 88250** [b3log/solo#12871]
之前使用的是 [markdown-http](https://github.com/b3log/markdown-http)，切换为 [Lute](https://github.com/b3log/lute)。

**Comment by vcjmhg** [comment]
后台界面不显示markdown的编辑框，请问该怎么办
![Snipaste_2019-09-11_22-21-20](https://user-images.githubusercontent.com/55177318/64705428-832d6b00-d4e2-11e9-9ddb-32f5fb753e2a.png)

**Comment by Vanessa219** [comment]
https://github.com/b3log/solo/issues/12904
