### ISSUE TITLE
能否做个手动保存ctrl-s

### ISSUE THREAD

**Issue by BaLaLaLs** [b3log/solo#12883]
### 你在什么场景下需要该功能？

今天写东西写了一大堆发布错点成了取消发布，点更新进去页面之前的内容全都不在了。作为程序员感觉还是ctrl-s 可靠些。

**Comment by 88250** [comment]
存稿的话可以鼠标点击。我明白程序员对快捷键的需求，但是考虑到整体设计一致，暂时还是不加了快捷键功能了，以后如果有机会再考虑，感谢反馈！
