### ISSUE TITLE
加密文章摘要泄露

### ISSUE THREAD

**Issue by Guangdinghou** [b3log/solo#12887]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

需要密码才能查看的博文在首页就可以预览部分内容。

### 重现步骤

请描述如何重现这个问题：

1.创建一篇文章，设置浏览密码，发布。
2.在首页可以预览文章部分内容，即便是设置了浏览密码。 

### 期待的结果

希望需要密码才能浏览的文章在首页不给返回具体内容。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。
![image](https://user-images.githubusercontent.com/10398241/64411940-e8d3be80-d0c0-11e9-8530-0370e05fa5f8.png)
![image](https://user-images.githubusercontent.com/10398241/64411967-fa1ccb00-d0c0-11e9-9b41-fffdeec91c96.png)
![image](https://user-images.githubusercontent.com/10398241/64411977-01dc6f80-d0c1-11e9-911d-fbe63c2a70b2.png)

### 桌面端环境

- OS: All
- Browser chrome  76.0.3809.132（

### 移动端环境

- Device: All
- OS: [e.g. iOS12]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
感谢反馈，master 上已经修复，最新 Docker 镜像稍后发布。
