### ISSUE TITLE
seo问题，用了半年几乎没有收录

### ISSUE THREAD

**Issue by fish2018** [b3log/solo#12889]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

我大概是4月开始用的，半年了百度几乎没有收录，查看站点统计几乎都是从google来的，是不是这个程序对seo不友好

### 期待的结果

正常收录

**Comment by 88250** [comment]
程序对 SEO 非常友好，请放心。
