### ISSUE TITLE
RSS订阅直接显示更新内容而不是只显示标题

### ISSUE THREAD

**Issue by Leif160519** [b3log/solo#12899]
### 你在什么场景下需要该功能？

RSS订阅更新

### 描述可能的解决方案

在xml里面显示文章内容，而不用每次都点击一下标题然后再显示文件内容
![image](https://user-images.githubusercontent.com/19452903/64949668-47145480-d8ac-11e9-8c4a-076625a664f4.png)

![image](https://user-images.githubusercontent.com/19452903/64949688-52678000-d8ac-11e9-865e-f855dfc2cbf8.png)

**Comment by 88250** [comment]
偏好设定里可以配置为全文输出。

**Comment by Leif160519** [comment]
> 偏好设定里可以配置为全文输出。

找到了谢谢
