### ISSUE TITLE
文章管理增加按回车键搜索

### ISSUE THREAD

**Issue by AlgerFan** [b3log/solo#12894]
文章管理的搜索框较宽，搜索不方便，希望加入按回车键搜索

![image](https://user-images.githubusercontent.com/873584/64836231-ae67a580-d61b-11e9-91e9-0da31234edc8.png)

**Comment by Leif160519** [comment]
强烈期望添加此功能

**Comment by 88250** [comment]
> 强烈期望添加此功能

镜像正在构建，请稍后 pull 拉取即可。
