### ISSUE TITLE
Can't load the default skins, please make sure skin [Pinghsu] is under skins directory and structure correctly

### ISSUE THREAD

**Issue by kanadeblisst** [b3log/solo#12896]
作者你好，我想在我的N1上运行这个solo，系统是Armbian Debian，但是拉取镜像并运行出错了，查看docker日志显示Can't load the default skins, please make sure skin [Pinghsu] is under skins directory and structure correctly
。请问一下，我应该如何操作才能解决这个问题。如果我使用war包来启动博客，应该如何修改数据库的密码，因为我直接启动报mysql拒绝访问。

另外，感谢你的无私奉献，你的solo博客项目非常优秀。

**Comment by Leif160519** [comment]
先用docker拉取一下mysql的镜像，设置好密码之后启动mysql容器，再拉取solo镜像，之后修改solo的运行命令里面的部分参数，具体参看readme，之后运行solo容器即可即可

**Comment by 88250** [comment]
请给出 docker 启动命令。

**Comment by kanadeblisst** [comment]
> 请给出 docker 启动命令。

`docker run --detach --name solo --network=host \
    --env RUNTIME_DB="MYSQL" \
    --env JDBC_USERNAME="root" \
    --env JDBC_PASSWORD="123456" \
    --env JDBC_DRIVER="com.mysql.cj.jdbc.Driver" \
    --env JDBC_URL="jdbc:mysql://127.0.0.1:3306/solo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC" \
    clinan/solo --listen_port=8080 --server_scheme=http --server_host=localhost --server_port=`

**Comment by kanadeblisst** [comment]
> 先用docker拉取一下mysql的镜像，设置好密码之后启动mysql容器，再拉取solo镜像，之后修改solo的运行命令里面的部分参数，具体参看readme，之后运行solo容器即可即可

mysql可以不使用容器吧，直接使用本地的，我只是在启动solo容器时报那个错误。我说的设置mysql密码是使用已经编译的solo-v3.6.4.war包来启动，如何修改war默认MySQL的密码

**Comment by 88250** [comment]
`clinan/solo` 这个库可能你要找原作者反馈了，这个镜像不是我们维护的哦。

**Comment by 88250** [comment]
从报错日志上看应该是默认皮肤镜像里面没打，你尝试手动挂载试试。

**Comment by 88250** [comment]
我先关闭了，有问题就继续跟帖。

**Comment by Leif160519** [comment]
> > 先用docker拉取一下mysql的镜像，设置好密码之后启动mysql容器，再拉取solo镜像，之后修改solo的运行命令里面的部分参数，具体参看readme，之后运行solo容器即可即可
> 
> mysql可以不使用容器吧，直接使用本地的，我只是在启动solo容器时报那个错误。我说的设置mysql密码是使用已经编译的solo-v3.6.4.war包来启动，如何修改war默认MySQL的密码

用下面两个命令是可以跑起来的
**solo_installer.sh**
```
docker run --detach --name solo --network=host \
    --env RUNTIME_DB="MYSQL" \
    --env JDBC_USERNAME="root" \
    --env JDBC_PASSWORD="123456" \
    --env JDBC_DRIVER="com.mysql.cj.jdbc.Driver" \
    --env JDBC_URL="jdbc:mysql://127.0.0.1:3306/solo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC" \
    --restart=always \
    b3log/solo --listen_port=8080 --server_scheme=https --server_host=your-domain --server_port=
```

**mysql_installer.sh**
```
config_dir=`pwd`
PASSWORD=123456
docker run -d --net host --name solo_mysql\
     -p 3306:3306 \
     -e MYSQL_ROOT_PASSWORD=$PASSWORD \
     -e TZ=Asia/Shanghai \
     --restart=always \
     mysql:5.7
```

mysql使用docker镜像是因为安装方便
