### ISSUE TITLE
开启https访问solo，后台管理系统不能正常使用

### ISSUE THREAD

**Issue by gjTool** [b3log/solo#12898]
### 描述问题

我使用的是solo-v3.6.4。用的tomcat9部署的solo。数据库用自带的h2。部署好后可以正常使用。最近我用nginx代理实现了https访问solo。但是，https访问solo后，我在后台管理系统里，更新任何东西都会报错403。当我关掉nginx，改回http访问。后台管理系统又正常了。

### 重现步骤

使用nginx代理开启https。修改tomcat项目目录里solo的latke.properties，将serverScheme=http改为serverScheme=https。然后去访问就发现可以正常访问，但是我需要修改文章或者更新其他任何东西的时候，都会报接口403。

### 期待的结果

希望不要报错403。后台管理系统可以正常使用

### 截屏或录像

![image](https://user-images.githubusercontent.com/36074298/64942448-a61d9d80-d89b-11e9-9eb1-76355a1c642e.png)

### 桌面端环境

所有

### 移动端环境

所有

### 其他信息

无

**Comment by 88250** [comment]
这个 403 不是 Solo 返的，我估计是 NGINX 返的吧，请检查一下 NGINX 相关配置。
