### ISSUE TITLE
PWA mainifest.json 模版化

### ISSUE THREAD

**Issue by forecasted** [b3log/solo#12901]
### 你在什么场景下需要该功能？

发现了喜欢的b3log博客时，会点击Chrome浏览器中的“安装应用 Solo - 博客"，添加到Chrome应用列表中。

当添加了多个博客的话，Chrome应用的名称都为 "Solo - 博客"，无法区分是哪个博客。。

### 描述可能的解决方案

建议使用博客的title，或者别的方式，来做为Chrome应用的名称，以提高区分度。

### 描述你认为的候选方案

无

### 其他信息

无，希望b3log越做越好。

**Comment by 88250** [comment]
感谢反馈。后续会将 PWA manifest.json 配置文件进行模版化，动态渲染应用名称。
