### ISSUE TITLE
3.6.5 H2数据库 查询分类出错

### ISSUE THREAD

**Issue by csfwff** [b3log/solo#12905]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

solo 3.6.5 使用H2数据库的时候点击分类无响应，控制台查看相应的链接为404。
查看日志发现为SQL执行异常
`Column "B3_SOLO_TAG_ARTICLE.OID" must be in the GROUP BY list`
请尽量清晰精准地描述你碰到的问题。

### 重现步骤

使用H2，点击分类

### 期待的结果

正确取得结果

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 桌面端环境

- OS: windows server

**Comment by 88250** [comment]
感谢反馈，已经修复。v3.6.5 war 和 Docker 镜像都更新了，请重新部署，辛苦了 🙏
