### ISSUE TITLE
后台导航管理添加链接失败

### ISSUE THREAD

**Issue by Leif160519** [b3log/solo#12908]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

后台导航管理项，添加导航失败

### 重现步骤

请描述如何重现这个问题：

1. 发布一篇文章为test，链接改为/test
2. 打开这个新文章发现可以访问
3. 导航管理页面，添加这个/test链接
4. 点击保存后提示失败，solo报错“链接重复”
5. 接着，若将/test改为/test1，再次点击保存，添加成功
6. 然后修改该导航为/test，保存后成功，导航可以正常访问该链接

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

![image](https://user-images.githubusercontent.com/19452903/65226579-b3d05e80-daf9-11e9-96fe-51d4d0efea60.png)

![image](https://user-images.githubusercontent.com/19452903/65226621-c64a9800-daf9-11e9-8c64-41f156ec27fc.png)

![image](https://user-images.githubusercontent.com/19452903/65226701-e712ed80-daf9-11e9-8e8f-2364dac97dbd.png)

### 桌面端环境

- OS: macos
- Browser chromium
- Version 76

**Comment by 88250** [comment]
感谢反馈，请看 #12912
