### ISSUE TITLE
 [markdown-http] is not available

### ISSUE THREAD

**Issue by iceuncle** [b3log/solo#12903]
一直部署不成功，log 显示
[markdown-http] is not available, uses built-in [flexmark] for Markdown processing. Please read FAQ section in user guide (https://hacpai.com/article/1492881378588) for more details.

[INFO ]-[2019-09-18 00:14:54]-[org.b3log.solo.SoloServletListener:99]: Solo is booting [ver=3.6.4, servletContainer=jetty/9.4.12.v20180830, os=Linux, isDocker=true, markdownHttpAvailable=false, pid=1, runtimeDatabase=MYSQL, runtimeMode=PRODUCTION, jdbc.username=root, jdbc.URL=jdbc:mysql://127.0.0.1:3306/solo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC]

[INFO ]-[2019-09-18 00:14:54]-[com.zaxxer.hikari.HikariDataSource:110]: HikariPool-1 - Starting...

[INFO ]-[2019-09-18 00:14:55]-[com.zaxxer.hikari.HikariDataSource:123]: HikariPool-1 - Start completed.

[WARN ]-[2019-09-18 00:14:55]-[org.b3log.solo.service.InitService:161]: Solo has not been initialized, please open your browser to init Solo

根据博客https://hacpai.com/article/1565021959471进行部署
是少了哪步吗

**Comment by 88250** [comment]
https://hacpai.com/article/1568737497333
