### ISSUE TITLE
后台删除了一篇博客，但是被删除的还可以访问

### ISSUE THREAD

**Issue by Leif160519** [b3log/solo#12907]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

后台删除了一篇博客，但是被删除的还可以访问

### 重现步骤

打开一篇博客，然后在后台删除之，重新刷新博客页面，仍然可以访问

### 期待的结果

跟3.6.4版本一样，删除一篇博客后，再次刷新打开的窗口，显示404或者提示博客已被删除

### 截屏或录像

![image](https://user-images.githubusercontent.com/19452903/65224288-779aff00-daf5-11e9-94d4-321de86d9b95.png)
后台删除了**Git中.gitignore的配置语法**，但是浏览器还可以访问 https://leif.fun/articles/2019/08/29/1567057481005.html

### 桌面端环境

- OS:macos
- Browser chromium
- Version

**Comment by Leif160519** [comment]
之前是发现有两篇博客内容一致，标题相差一个**的**，删除了带**的**的，结果还可以访问

**Comment by Leif160519** [comment]
如果被删除的文章的连接是自己指定的，那么写新文章时，之前指定的这个链接就不能在用了，会提示链接重复

**Comment by 88250** [comment]
感谢反馈，请看 #12912
