### ISSUE TITLE
自定义导航栏路径导致PJAX失效

### ISSUE THREAD

**Issue by InkDP** [b3log/solo#12906]
1. 两个自定义导航栏的一个写了完整路径，而另外一个省略了域名
![image.png](https://img.hacpai.com/file/2019/09/image-8400ae35.png)
2. 访问写全了路径的自定义导航栏就不会破坏pjax,而访问关于我就会
前往[墨殇的技术博客-Pingsu](https://www.jinjianh.com/?skin=Pinghsu)查看,下面公告栏的歌单就是最好的证明,直接拖一段切换就可以看到PJAX失效的问题

**Comment by 88250** [comment]
镜像正在构建，估计需要 30 分钟。
