### ISSUE TITLE
文章链接手动修改过后，原来的连接还可以访问

### ISSUE THREAD

**Issue by Leif160519** [b3log/solo#12909]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

文章链接手动修改过后，原来的连接还可以访问

### 重现步骤

请描述如何重现这个问题：

1. 打开一篇文章
2. 进入后台，修改该文章，将文章链接修改为其他
3. 保存发布文章
4. 改文章的旧连接依旧可以访问

### 期待的结果

一篇文章的连接修改过后，之前的连接需失效无法访问

### 桌面端环境

- OS: macos
- Browser chromium
- Version 76

**Comment by 88250** [comment]
感谢反馈，请看 #12912
