### ISSUE TITLE
博客的分类页面 404

### ISSUE THREAD

**Issue by panjf2000** [b3log/solo#12902]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

博客的分类页里的所有子分类页面突然全部打不开了。

### 重现步骤

请描述如何重现这个问题：
进入 https://taohuawu.club/tags.html 然后随便点一个子分类，跳转 404。

### 期待的结果

正确显示分类下的文章列表。

### 桌面端环境

- OS: mac
- Browser: chrome
- Version:  76.0.3809.132 (Official Build) (64-bit)

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
请看下日志，如果有报错的话请打个 zip 包上传。

**Comment by panjf2000** [comment]
晚上回家查一下

**Comment by Leif160519** [comment]
> 晚上回家查一下

可能为浏览器缓存，清理一下看看，如果之前有博客被删除，再次访问这个博客的连接会显示404.然后再点击其他存在的博客，有时候也会显示404，我用的chromium出现过这个问题，chrome估计也差不多

**Comment by 88250** [comment]
@panjf2000 今天发布了 v3.6.5 麻烦先更新到最新版再看是否能重现问题，谢谢。

**Comment by panjf2000** [comment]
好，我先试试

**Comment by panjf2000** [comment]
@88250 
问题消失了，所以你们是修复这个问题了对吧？

**Comment by 88250** [comment]
> @88250
> 问题消失了，所以你们是修复这个问题了对吧？

标签部分的确有个细节处理过，可能是修复了吧 😂 

我关闭 issue 了，如果还有问题请跟帖，谢谢！
