### ISSUE TITLE
火狐浏览器后台无法跳转

### ISSUE THREAD

**Issue by lizhongyue248** [b3log/solo#12916]
----

### 描述问题

manjaro 火狐浏览器无法进行菜单跳转

### 重现步骤

1. 点击管理
2. 点击左边菜单栏无任何变化
3. 点击发布文章提示载入中但还是无变化
4. 需要F5进行刷新后才会变化

查看控制台和网络，均无任何输出

谷歌浏览器正常

### 期待的结果

火狐浏览器能正常切换

### 截图

![Peek 2019-10-01 16-27](https://user-images.githubusercontent.com/29678316/65946772-7230a380-e469-11e9-8aee-a7d12132d9e3.gif)

### 桌面端环境

- OS: manjaro 18
- Browser ![深度截图plasmashell20191001163315.png](https://img.hacpai.com/file/2019/10/深度截图plasmashell20191001163315-00d6e5bd.png)

### 其他信息

- 尝试重装浏览器，无效
- 重启Solo，无效
- 重装系统，无效

**Comment by 88250** [comment]
我这边用 Windows 和 Mac 的 FF 重现不了问题哦。
