### ISSUE TITLE
后台管理体验优化建议

### ISSUE THREAD

**Issue by AlgerFan** [b3log/solo#12915]
经过大约半年的使用，有一些使用体验优化建议，如有不合理的地方，望指出：

1. 发布文章、更新文章过程略显繁琐：目前的iframe布局下写文章，因markdown布局较小，一般会在全屏下写文章，所以写文章的流程为：点击发布文章——>全屏——>写完文章后——>取消全屏——>点击发布

   两种解决方案（参考其他平台）：

   1）将导航栏放置在头部，这样markdown就可以足够的大，写作也较为舒适。

   2）跳转至新的页面（类似于csdn），头部有标题、发布按钮，下方为铺满markdown编辑器。

   这样做的好处是写作文章的过程简化，而且markdown体验较佳，流程为：点击发布文章——>写完文章后——>点击发布

2. 后台样式过于单一，毕竟作者经常停留在后台写作，希望能加入后台主题模块或者不同的主题色、布局。

3. 在参数设置页面：各个参数设置其实可以一行两个参数，这些参数用不了占据整行，导致页面较长。

**Comment by Vanessa219** [comment]
1. 在编辑器中可以使用 `ctrl+'` 快捷键进行全屏设置
2. 考虑到用户使用习惯，尽量保持简单一致
3. 稍后修改
