### ISSUE TITLE
希望可以优化docker-restart.sh脚本

### ISSUE THREAD

**Issue by vcjmhg** [b3log/solo#12920]
## 说明
每次都进行版本更新比较繁琐，因此希望能够自动化更新。虽然官方给了一个`docker-restart.sh`脚本，但该脚本在充当升级脚本时有些许不足，无论`solo`是否更新都会将原来的容器删除再重建，有些不合理。因此我通过分析`docker`在`pull` 镜像时，分析有更新和没更新情况下的区别下，编写了`docker-update.sh`这个脚本。
## 思路
由于`docker`中没有命令直接可以用于检测一个镜像是否最新，因此我们可以考虑从`docker pull`执行过程入手进行分析。    
当`solo`是最新版是会出现如下界面：  
![](https://raw.githubusercontent.com/goWithHappy/pictureRepo/master/img/20191013143852.png)

当`solo`需要更新时会出现如下界面：  
![](https://raw.githubusercontent.com/goWithHappy/pictureRepo/master/img/20191013144801.png)

因此我们通过`管道命令`和`grep`结合如果有更新，执行上边删除旧容器，创建新容器的命令。否则只是输出提示语。  

## 运行过程
需要更新时，调试过程结果（`solo`的部署脚本和`docker-update`是一个文件）    
![](https://raw.githubusercontent.com/goWithHappy/pictureRepo/master/img/20191013153027.png)

需要更新时，执行结果    
![](https://raw.githubusercontent.com/goWithHappy/pictureRepo/master/img/20191013153102.png)

无需更新时调试过程结果：  
![](https://raw.githubusercontent.com/goWithHappy/pictureRepo/master/img/20191013153245.png)

无需更新时运行结果：  
![](https://raw.githubusercontent.com/goWithHappy/pictureRepo/master/img/20191013153318.png)

## 脚本内容
```shell
#!/bin/bash
#
# Solo docker 更新脚本
#
# 1. 请注意修改参数
# 2. 可将该脚本加入 crontab，每日凌晨运行来实现自动更新
#

isUpdate=$(docker pull b3log/solo|grep "Downloaded")
echo $isUpdate

#如果有新版本或者没有安装才会进行更新
if [[ -z  $isUpdate ]] 
then 
	echo This is the latest version
else
	docker stop solo
	docker rm solo
	docker run --detach --name solo --network=host \
	--env RUNTIME_DB="MYSQL" \
       	--env JDBC_USERNAME="root" \
	--env JDBC_PASSWORD="123456" \
	--env JDBC_DRIVER="com.mysql.cj.jdbc.Driver" \
	--env JDBC_URL="jdbc:mysql://127.0.0.1:3306/solo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC" \
       	b3log/solo --listen_port=8080 --server_scheme=http --server_host=localhost
fi

```
[文件链接](https://github.com/vcjmhg/solo/blob/master/scripts/docker-update.sh)

**Comment by 88250** [comment]
感谢建议，请发起 PR。

**Comment by 88250** [comment]
https://github.com/b3log/solo/pull/12923
