### ISSUE TITLE
希望新增文章隐藏的功能

### ISSUE THREAD

**Issue by oyzh1994** [b3log/solo#12925]
### 你在什么场景下需要该功能？
部分文章内容已经过时，删除太可惜，又不希望展示
请尽量清晰精准地描述你碰到的问题。
希望对于文章，有一个隐藏或者不显示的按钮，避免直接删除
### 描述可能的解决方案，
对文章新增一个显示字段，对于设置为不显示的文章，不显示在前端
请尽量清晰精准地描述你期待我们要做的，描述你想到的实现方案。

### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by 88250** [comment]
更新文章时取消发布即可，这样文章会变成草稿。如果希望草稿能够被访问到可以在参数设置中勾选`允许通过链接访问草稿`。
