### ISSUE TITLE
文章内容或标题变更后，首页出现“有更新！” 字样，点击访问后未消失

### ISSUE THREAD

**Issue by njqaaa** [b3log/solo#12927]
### 描述问题
文章内容或标题变更后，首页出现“有更新！” 字样，点击访问后无变化，“有更新！”字样依然存在

### 重现步骤
有点记不清了，好像就变更过配置文件的域名，会导致这问题吗？ 
好像也没做其他操作。
数据库用的h2。
博客地址：http://www-njq.51vip.biz/
可重现。

### 期待的结果
如果文章内容或标题变更后，首页出现“有更新！” 字样。
但当点击访问文章后，隐藏“有更新！”字样。
备注：能否实现根据UUID等来判断是否需展示“有更新！”字样（场景：曾经访问过该文章的人，都应该可以清楚的了解该文章曾经做过变更，不能因任意一人查看过，而给别人误导）
简单点的话，按照用户登录的github账号来判断，游客则忽略……

### 截屏或录像

![image](https://user-images.githubusercontent.com/5145656/67300676-f0401180-f520-11e9-94b1-23729fabb72c.png)

### 桌面端环境

- OS: [e.g. windows, mac, linux]
- Browser chrome

**Comment by njqaaa** [comment]
运行环境 Raspbian GNU/Linux 10 (buster)
使用docker + tomcat管理 （arm32v7/tomcat:8-jre8-alpine）
solo版本  (https://github.com/b3log/solo/releases/tag/v3.6.5)

**Comment by 88250** [comment]
感谢建议，不过暂时不做变更了。更新提示没有针对单个用户，如果不需要的话可以在设置中关闭。
