### ISSUE TITLE
怎么关闭首页上的开始使用呢

### ISSUE THREAD

**Issue by liqitian3344** [b3log/solo#12939]
请问怎么关闭首页上的开始使用呢？急急急

**Comment by 88250** [comment]
目前关闭不了，请问是什么情况让你需要关闭它？

**Comment by lizhongyue248** [comment]
只有手动修改皮肤。。。

**Comment by liqitian3344** [comment]
@88250 主要是别人可以直接使用我的站点发布些不雅的东西。。。

**Comment by liqitian3344** [comment]
@lizhongyue248 😭

**Comment by 88250** [comment]
哦，明白了。如果是违法违规的内容欢迎举报发布者的账号，我们统一进行封禁，谢谢。

**Comment by liqitian3344** [comment]
@88250 希望后期可以在后台添加是否 开启首页入口。。。。😭

**Comment by 88250** [comment]
收到，2020 Q1 我们会对 Solo 进行一次大的升级，评论系统会使用社区提供的服务，具体计划可参考[Solo v4 计划](https://hacpai.com/article/1571544590916)。登录相关机制届时也会进行调整，敬请期待！
