### ISSUE TITLE
ubuntu 18.04 安装solo后没有报错，但是使用docker ps并没有solo在

### ISSUE THREAD

**Issue by WeiYongqiang55** [b3log/solo#12934]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

请尽量清晰精准地描述你碰到的问题。

### 重现步骤

请描述如何重现这个问题：

2. Click on '...'
3. Scroll down to '...'

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 桌面端环境

- OS: [e.g. windows, mac, linux]

### 移动端环境

- Device: [e.g. iPhone8]
- OS: [e.g. iOS12]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
可能是进程报错退出了，请用 docker logs 查看报错日志。

**Comment by pengdongliang** [comment]
巧了正好我刚遇到这个问题^_^
原因: docker容器之间相互访问问题
我是这样解决的: 在mysql容器创建的时候加上 `--network=host`
