### ISSUE TITLE
更新皮肤开发工具链

### ISSUE THREAD

**Issue by zjhch123** [b3log/solo#12933]
## 1. CSS

针对css，希望可以自动添加浏览器前缀，比如
```
transition: xxx,
-webkit-transition: xxx
```

可以通过postcss搭配autoprefixer实现

## 2. JS

支持ES6。目前的`gulp-uglify`不知道是版本过低还是怎么，无法压缩ES6代码。

![image](https://user-images.githubusercontent.com/12215513/68069510-c813a680-fd9b-11e9-83c0-a34fb75c1b55.png)

---
多谢！

**Comment by AlgerFan** [comment]
@zjhch123 这是准备开发新皮肤吗？😉😉
