### ISSUE TITLE
Solo的Markdown中无法渲染数学公式

### ISSUE THREAD

**Issue by Evilrabbit520** [b3log/solo#12936]
Solo的Markdown中无法渲染数学公式，版本为3.6.6，我的测试为行内公式

官方给出Markdown教程

`公式 $a^2 + b^2 = \color{red}c^2$ 是行内`

无法应用在后台编辑器中

**Comment by littlecurl** [comment]
还有一点，Solo编辑器行首使用Tab之后，会变成引用，手动敲四个空格后也会变成引用。
尽管有格式化功能，但格式化之后依然不能实现小时候写作文要求的段首空两个字的格式 : )

**Comment by 88250** [comment]
@littlecurl 4 个空格或者 1 一个 tab 不是引用，而是代码块，这是标准的 Markdown 语法实现。如果需要段落开头空两格可以用全角空格。

**Comment by 88250** [comment]
@Evilrabbit520 数学公式的渲染需要启用 Lute，具体请看这里 https://hacpai.com/article/1569240189601
