### ISSUE TITLE
更新到 v3.6.7 之后博客所有样式都乱了

### ISSUE THREAD

**Issue by panjf2000** [b3log/solo#12942]
### 描述问题

通过 docker 升级到最新的 v3.6.7，结果整个前端样式全乱了，https://taohuawu.club/, 回退到前几个版本也没恢复。

### 重现步骤

请描述如何重现这个问题：

用 docker 升级 solo 到 v3.6.7，博客前端样式就全都乱了

### 期待的结果

恢复前端样式

### 截屏或录像

https://taohuawu.club/

### 桌面端环境

- OS: mac
- Browser: chrome 
- Version [e.g. 22] 78.0.3904.97

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by panjf2000** [comment]
@88250 
麻烦看下

**Comment by 88250** [comment]
启动时带个参数 `--server_port=` 值留空试试。

**Comment by panjf2000** [comment]
`--server_port=` 有效，不过我记得默认 80 或 443 是不需要设置它的，以前我也是没有设置，最近这方面有改动？

**Comment by 88250** [comment]
嗯，最近改了下开发框架 Latke。
