### ISSUE TITLE
当没有文章时无法登陆后台管理页面

### ISSUE THREAD

**Issue by okay3r** [b3log/solo#12949]

**Comment by 88250** [comment]
麻烦重试一下，谢谢。

**Comment by okay3r** [comment]
好了，谢谢


    


            在2019年11月23日 22:49，D 写道： 麻烦重试一下，谢谢。



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/b3log/solo/issues/12949?email_source=notifications\u0026email_token=ALYPKK6N4FSLGNH7ZE3DJK3QVE7ILA5CNFSM4JQZZ7O2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE7WTKI#issuecomment-557803945",

"url": "https://github.com/b3log/solo/issues/12949?email_source=notifications\u0026email_token=ALYPKK6N4FSLGNH7ZE3DJK3QVE7ILA5CNFSM4JQZZ7O2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE7WTKI#issuecomment-557803945",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
