### ISSUE TITLE
无缘无故的加载不了 js,css样式了！

### ISSUE THREAD

**Issue by liqitian3344** [b3log/solo#12945]
![image](https://user-images.githubusercontent.com/29157770/68662427-bd18fd00-0577-11ea-9681-6ea64850785f.png)
怎么会无缘无故的 请求到 8080 端口了呢？？？十万火急

**Comment by liqitian3344** [comment]
![image](https://user-images.githubusercontent.com/29157770/68662599-1a14b300-0578-11ea-8784-09df5adb2616.png)
我8080端口根本没有使用的

**Comment by liqitian3344** [comment]
这是 我的启动命令 监听6606端口
![image](https://user-images.githubusercontent.com/29157770/68667809-d6bf4200-0581-11ea-935b-c1bfb6d3153d.png)

下面 我直接 域名:6606访问
![image](https://user-images.githubusercontent.com/29157770/68667855-f2c2e380-0581-11ea-8dd7-852ae0c425b0.png)
js和css转到了8080端口去了，本地已确认没做任何转发操作

**Comment by liqitian3344** [comment]
@88250 help~~~~

**Comment by 88250** [comment]
启动时带个参数 `--server_port=` 值留空。

**Comment by liqitian3344** [comment]
okok感谢~~~
