### ISSUE TITLE
登录失败，一直 401 Unauthorized!

### ISSUE THREAD

**Issue by liqitian3344** [b3log/solo#12941]
![image](https://user-images.githubusercontent.com/29157770/68555796-56f28400-046a-11ea-8e2d-b24f38c0a7e1.png)
help~~~

**Comment by 88250** [comment]
现在应该恢复了 🙏

**Comment by liqitian3344** [comment]
哇🤩，那么迅速~~~
6666666

**Comment by liqitian3344** [comment]
@88250
