### ISSUE TITLE
ubuntu18.04浏览器访问502

### ISSUE THREAD

**Issue by pengdongliang** [b3log/solo#12946]
`docker pull b3log/solo` 安装的, 找不到皮肤......
```
Can't load the default skins, please make sure skin [Pinghsu] is under skins directory and structure correctly
```
![image](https://user-images.githubusercontent.com/30225886/68851782-7eb74580-0711-11ea-8ec2-63537cdbad08.png)

**Comment by 88250** [comment]
如果不挂载皮肤，请勿加皮肤挂载的参数。

**Comment by pengdongliang** [comment]
谢谢, 我刚逛了下社区, 把皮肤克隆下来就可以了

**Comment by pengdongliang** [comment]
> 如果不挂载皮肤，不要加皮肤挂载的参数。

谢谢, 我刚逛了下社区, 把皮肤克隆下来就可以了
