### ISSUE TITLE
黑客派登陆不了的问题

### ISSUE THREAD

**Issue by jetablezhu** [b3log/solo#12952]
使用GitHub登录就显示“因权限不足操作已被禁止”，可是之前我用的好好的啊，有一段时间没来了，就登不上了，啥情况啊？

**Comment by 88250** [comment]
组织因为被人恶意举报导致被封，我们正在和 GitHub 沟通。如果不行的话就重头再来吧 😂 

现在登录方面应该已经恢复，请帮忙试试看。
